from pathlib import Path
from datetime import datetime, timezone
import subprocess
import shutil
import json

from app.network_discovery.network_discovery import discover_network
from app.network_discovery.host_config_templates import *

from app import db
from flask import current_app
import sqlalchemy as sa
from app.system_models import \
    User, \
    UserStatus, \
    NetworkDiscovery, \
    Open_TCP_Services, \
    Open_UDP_Services, \
    SSHCredentials, \
    NCPADeployment, \
    NCPADevicePartition, \
    AgentStatus 
from app.logging import create_network_discovery_status, update_network_discovery_status, calculate_progress
from app.logging.deployment_history import update_ncpa_deployment_status
from app.system_models import DiscoveryStatus, DeploymentStatus
import socket
import ipaddress
import tempfile

# what names to will be placed to ports from nmap
TCP_SERVICE_OVERRIDES = {
    "5693": "ncpa",
    "5666": "nrpe",
    "22": "ssh",
    "80": "http",
    "443": "https",
}

UDP_SERVICE_OVERRIDES = {
    "5666": "nrpe",
    "22": "ssh",
    "80": "http",
    "443": "https",
    "161": "snmp",
}

SNMP_COMMUNITY_STRING = "public"

SNMP_OID = {
    "1.3.6.1.2.1.1.3.0":"Uptime",
    "1.3.6.1.2.1.1.1.0":"System Description",
    "1.3.6.1.2.1.2.2.1.8.3":"LAN Status",
    "1.3.6.1.2.1.2.2.1.10.3":"LAN In Octets",
    "1.3.6.1.2.1.2.2.1.16.3":"LAN Out Octets",
    "1.3.6.1.4.1.2021.4.5.0":"Memory Total",
}

SNMP_PORT = "161"

# for the default hostname given to hosts ip.test.local
# example 192.168.130.10.test.local
DOMAIN = "test.local"

NCPA_PORT = "5693"

# Project root (pin-point/)
PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Folder where generated configs are stored
HOST_CONFIG_DIR = PROJECT_ROOT / "host-config-files"

# Folder where backups of the running config are stored
BACKUP_DIR = PROJECT_ROOT / "running-host-config-backup"

# Any constants above the line should be added to the settings menu (except the Projecdt Root)

# ====================================================================

DEFAULT_TCP_COMMAND = "check_tcp"

DEFAULT_UDP_COMMAND = "check_udp"

PROGRESS_WEIGHT = [40,50,55,60,70,80,90,95,100]

# Progress stages for add_ncpa_port: adding the port to the db, reloading
# hosts, generating the config, validating, and applying it
ADD_NCPA_PORT_PROGRESS_WEIGHT = [40, 55, 70, 85, 100]

# Nagios live config
NAGIOS_HOST_CFG = Path("/usr/local/nagios/etc/objects/hosts.cfg")

# Get the folder for command maps
MAP_DIR = Path(__file__).parent / "command_maps"

# Nagios binary and main config, needed for -v validation
NAGIOS_BIN = Path("/usr/local/nagios/bin/nagios")

NAGIOS_MAIN_CFG = Path("/usr/local/nagios/etc/nagios.cfg")

# get the tcp command map
with open(MAP_DIR / "tcp_commands.json") as f:
    TCP_COMMANDS = json.load(f)

# get the udp command map
with open(MAP_DIR / "udp_commands.json") as f:
    UDP_COMMANDS = json.load(f)

def _add_space(spaces):
    return "\n" * spaces


# this is the function that will give a command based on the service name
# if its not in the map, you'll have to make your own default command
# ex: checkudp!63
def _get_command(service_name, port, command_map, default_command, args=None):

    command = command_map.get(service_name)

    # ------------------------------------------------------------------ #
    # No map entry — fall back to the supplied default                    #
    # ------------------------------------------------------------------ #
    if default_command == DEFAULT_UDP_COMMAND:
        # check_udp requires -s and -e; supply empty strings so the plugin
        # runs and returns a result instead of aborting with an error.
        command = f'{default_command}!{port}!-s "" -e ""'
    else:
        command = f"{default_command}!{port}"

    if args is not None:
        command += f"!{args}"

    return command

def _create_host_cfg_file(discovered_hosts):
    """
    Creates a new host configuration file.

    Returns:
        pathlib.Path: Path to the newly created file.
    """

    HOST_CONFIG_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%d-%m-%Y-%H-%M")
    filename = f"host-{timestamp}.cfg"

    cfg_path = HOST_CONFIG_DIR / filename

    host_config = []

    host_config.append(
        f"""
        ##########################################################################
        #   host.cfg file for Nagios generated by Pin Point
        #   
        #   generated at {timestamp}
        ##########################################################################
        """
    )

    host_config.append(_add_space(4))

    host_config.append(
        f"""

        #
        # Define Contacts
        #  

        """
    )

    users = db.session.scalars(
        sa.select(User).where(
            User.Status == UserStatus.ACTIVE
        )
    ).all()

    for user in users:
        user_information = {
            "contact_name": str(user.Email),
            "use": "generic-contact",
            "full_name": str(user.First_Name + " " + user.Last_Name),
            "email_address": str(user.Email)
        }

        host_config.append(create_contact(user_information))
        host_config.append(_add_space(4))

    # add the users to the contact group
    host_config.append(
        f"""

        #
        # Define Contactgroups
        #  
            
        """
    )

    contact_group = {
        "group_name": "system_users",
        "alias_name": "Nagios Users",
        "member_list": ",".join(user.Email for user in users)
    }

    host_config.append(create_contactgroup(contact_group))

    host_config.append(_add_space(4))


    host_config.append(
        f"""

        #
        # Define Hosts
        # 

        """
    )

    hostgroups = {
                "Linux":{
                    "devices":[]
                },
                "Windows":{
                    "devices":[]
                },
                "Mac OS X":{
                    "devices":[]
                },
                "Android":{
                    "devices":[]
                },
                "iOS":{
                    "devices":[]
                },
                "ChromeOS":{
                    "devices":[]
                },
                "OpenBSD":{
                    "devices":[]
                },
                "NetBSD":{
                    "devices":[]
                },
                "Mikrotik":{
                    "devices":[]
                },
                "OpenWRT":{
                    "devices":[]
                },
                "Cisco":{
                    "devices":[]
                },
                "Unknown":{
                    "devices":[]
                }

            }

    SNMP_Devices = []

    NCPA_Devices = []

    for hosts in discovered_hosts.values():
        for ip, host_data in hosts.items():
            host = {}
            host["host_name"] = host_data["data"]["hostname"] 
            host["alias"] = "alias" 
            host["address"] = ip
            host["contact_groups"] = "system_users"
            host_config.append(create_host(host))
            host_config.append(_add_space(4))

            # Assigns hostgroup's list to be used in creating hostgroups
            
            os_name = host_data["data"]["os"]
            if os_name in hostgroups:
                hostgroups[os_name]["devices"].append(host_data["data"]["hostname"])
            else:
                hostgroups["Unknown"]["devices"].append(host_data["data"]["hostname"])

            host_config.append(
                f"""

                #
                # Define Services of
                # Hostname: {host_data["data"]["hostname"]}
                # IP: {ip}
                #

                """
            )

            tcp_services = host_data["services"]["tcp"]

            for port, service_data in tcp_services.items():
                service_name = f"{service_data['service_name']}-{port}-TCP"

                command = _get_command(service_name,port,TCP_COMMANDS,DEFAULT_TCP_COMMAND)

                service = {
                    "host_name": host_data["data"]["hostname"],
                    "service_name": service_name,
                    "contact_groups": "system_users"
                }

                host_config.append(
                    create_service(service,command)
                )
                host_config.append(_add_space(4))

            udp_services = host_data["services"]["udp"]

            for port, service_data in udp_services.items():
                service_name = f"{service_data['service_name']}-{port}-UDP"

                if service_name == "snmp":
                    SNMP_Devices.append(host_data["data"]["hostname"])
                else:
                    command = _get_command(service_name,port,UDP_COMMANDS,DEFAULT_UDP_COMMAND)

                service = {
                    "host_name": host_data["data"]["hostname"],
                    "service_name": service_name,
                    "contact_groups": "system_users"
                }
            
                host_config.append(
                    create_service(service,command)
                )
                host_config.append(_add_space(4))

    host_config.append(
        f"""

        #
        # Define Hostgroups 
        #  

        """
    )

    host_config.append(_add_space(4))

    host_config.append(
            f"""
    
            #
            # Define OS Groups
            #  
    
            """
    )


    for os, group_devices in hostgroups.items():

        devices = group_devices["devices"]

        if not devices:
            continue

        host_group={
            "group_name": os,
            "alias_name": os,
            "member_list": ",".join(devices)
        } 
        host_config.append(create_hostgroup(host_group))
        host_config.append(_add_space(4))

    if SNMP_Devices is not None:
        host_config.append(
                f"""
            
                #
                # Define SNMP Devices
                #  
            
                """
        )

        host_group={
            "group_name": "snmp-devices",
            "alias_name": "SNMP Devices",
            "member_list": ",".join(SNMP_Devices)
        }

        host_config.append(host_group)

        host_config.append(_add_space(4))

        for oid, description in SNMP_OID.items():
            command = _get_command(
                            "snmp",
                            "161",
                            UDP_COMMANDS,
                            DEFAULT_UDP_COMMAND,
                            f"-C {SNMP_COMMUNITY_STRING} {oid}"
                        )
            snmp_service = create_multi_host_service(
                                "snmp-devices",
                                description,
                                command,
                                "system_users"
                            )
            host_config.append(snmp_service)

        host_config.append(_add_space(4))

    if SNMP_Devices is not None:
        host_config.append(
                f"""
            
                #
                # Define NCPA Service
                #  
            
                """
        )

        devices = db.session.execute(
            sa.select(NetworkDiscovery, NCPADeployment).join(
                NCPADeployment,
                NetworkDiscovery.NetDiscoveryID == NCPADeployment.NetworkDiscoveryID
            ).where(
                NetworkDiscovery.Hostname.in_(NCPA_Devices),
                NetworkDiscovery.NCPA_Eligible.is_(True)
            )
        ).all()

        if devices is not None:
            for device, ncpa_deployment in devices:
                ncpa_cpu_usage = {
                    "hostname":device.Hostname,
                    "service_name": "CPU Usage",
                    "contact_groups": "system_users"
                }
                command = _get_command(
                    "ncpa",
                    NCPA_PORT,
                    UDP_COMMANDS,
                    DEFAULT_TCP_COMMAND,
                    f' -t {ncpa_deployment.Token} -P {NCPA_PORT} -M cpu/percent -w 50 -c 80 -q "aggregate=avg" '
                )
                service = create_service(
                    ncpa_cpu_usage,
                    command
                )

                host_config.append(service)

                ncpa_memory_usage = {
                    "hostname":device.Hostname,
                    "service_name": "Memory Usage",
                    "contact_groups": "system_users"
                }
                command = _get_command(
                    "ncpa",
                    NCPA_PORT,
                    UDP_COMMANDS,
                    DEFAULT_TCP_COMMAND,
                    f' -t {ncpa_deployment.Token} -P {NCPA_PORT} -M memory/virtual/percent -w 50 -c 80 -u Gi '
                )
                service = create_service(
                    ncpa_memory_usage,
                    command
                )

                host_config.append(service)

                # --- Per-partition disk usage services ---
                # Query the partitions that were discovered on this device
                # during NCPA installation and stored in NCPADevicePartition.
                # Each partition gets its own Nagios service so the dashboard
                # can track them individually.
                partitions = db.session.scalars(
                    sa.select(NCPADevicePartition).where(
                        NCPADevicePartition.NCPADeployID == ncpa_deployment.NCPADeployID
                    )
                ).all()

                if partitions:
                    for partition in partitions:
                        ncpa_disk_usage = {
                            "hostname": device.Hostname,
                            "service_name": f"Disk Usage ({partition.Name})",
                            "contact_groups": "system_users"
                        }
                        command = _get_command(
                            "ncpa",
                            NCPA_PORT,
                            UDP_COMMANDS,
                            DEFAULT_TCP_COMMAND,
                            f' -t {ncpa_deployment.Token} -P {NCPA_PORT} -M disk/logical/{partition.Name}/percent -w 70 -c 95 -u Gi'
                        )
                        service = create_service(
                            ncpa_disk_usage,
                            command
                        )
                        host_config.append(service)
                else:
                    # Fallback: no partition data stored — use the generic
                    # disk/logical endpoint so the service is still generated
                    ncpa_disk_usage = {
                        "hostname": device.Hostname,
                        "service_name": "Disk Usage",
                        "contact_groups": "system_users"
                    }
                    command = _get_command(
                        "ncpa",
                        NCPA_PORT,
                        UDP_COMMANDS,
                        DEFAULT_TCP_COMMAND,
                        f' -t {ncpa_deployment.Token} -P {NCPA_PORT} -M disk/logical/percent -w 70 -c 95 '
                    )
                    service = create_service(
                        ncpa_disk_usage,
                        command
                    )
                    host_config.append(service)

    with open(cfg_path, "w") as f:
        # remember to f.write("string") here after you're done with discovering devices
        f.write("".join(host_config))
    return cfg_path

def get_monitoring_server_ips():
    ips = set()

    for info in socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET):
        ip = info[4][0]
        address = ipaddress.ip_address(ip)

        if not address.is_loopback:
            ips.add(ip)

    return ips

def _save_discovered_hosts(discovered_hosts, network_discovery_id, progress_weight):
    total_hosts = sum(len(hosts) for hosts in discovered_hosts.values())
    processed_hosts = 0

    monitoring_server_ips = get_monitoring_server_ips()

    try:
        for network, hosts in discovered_hosts.items():
            
            for ip_address, host_data in hosts.items():

                if ip_address in monitoring_server_ips:
                    continue

                data = host_data["data"]
                services = host_data.get("services", {})

                hostname = data.get("hostname")
                mac_address = data.get("mac_address")
                os_type = data.get("os")

                if mac_address is not None:
                    device = db.session.scalar(
                            sa.select(NetworkDiscovery).where(
                                NetworkDiscovery.MAC_Address == mac_address,
                                NetworkDiscovery.Network == network
                        )
                    )
                else:
                    device = db.session.scalar(
                        sa.select(NetworkDiscovery).where(
                            NetworkDiscovery.IP_Address == ip_address,
                            NetworkDiscovery.Network == network
                        )
                    )

                NCPA_Eligible = False

                if os_type == "Linux":
                    NCPA_Eligible = True

                    

                # -------------------------------------------------
                # Create device if it doesn't exist
                # -------------------------------------------------

                if device is None:
                    device = NetworkDiscovery(
                        Hostname = hostname,
                        IP_Address = ip_address,
                        Network = network,
                        MAC_Address = mac_address,
                        OS_Type = os_type,
                        NCPA_Eligible = NCPA_Eligible,
                        DiscoveryStatusID = network_discovery_id
                    )

                    db.session.add(device)
                    db.session.flush()

                    if device.NCPA_Eligible == True:
                        ssh = SSHCredentials(
                            SSH_Port = int(port_number) ,
                            Key_Installed = False,
                            Key_Fingerprint = None,
                            Created_At = None,
                            NetworkDiscoveryID = device.NetDiscoveryID
                        )
                                                                    
                        db.session.add(ssh)
                                                                    
                        ncpa = NCPADeployment(
                            Agent_Status = AgentStatus.PENDING_NCPA,
                            NetworkDiscoveryID = device.NetDiscoveryID
                        )
                                                                    
                        db.session.add(ncpa)
                        db.session.flush()

                else:
                    NCPA_Eligible = False

                    device.Hostname = hostname
                    device.MAC_Address = mac_address
                    device.OS_Type = os_type
                    device.NCPA_Eligible = NCPA_Eligible
                    device.DiscoveryStatusID = network_discovery_id

                # -------------------------------------------------
                # TCP services — add/update found ports, then
                # remove any DB-stored port not seen in this scan
                # -------------------------------------------------

                scanned_tcp_ports = set()

                for port_number, service_data in services.get("tcp", {}).items():
                    # Model column is an int; scan data comes in as a string —
                    # normalize here so comparisons/deletes below match correctly
                    port_number_int = int(port_number)
                    scanned_tcp_ports.add(port_number_int)

                    existing_service = db.session.scalar(
                        sa.select(Open_TCP_Services).join(
                            NetworkDiscovery,
                            Open_TCP_Services.NetDiscoveryID == NetworkDiscovery.NetDiscoveryID
                        )
                        .where(
                            Open_TCP_Services.NetDiscoveryID == device.NetDiscoveryID,
                            Open_TCP_Services.Port_Number == port_number_int,
                            NetworkDiscovery.Include_Device_In_Scanning.is_(True)
                        )
                    )

                    service_name = service_data.get("service_name", "Unknown")

                    if existing_service is None:

                        new_service = Open_TCP_Services(
                            Port_Number=port_number_int,
                            Service_Name=service_name,
                            NetDiscoveryID=device.NetDiscoveryID
                        )
                        db.session.add(new_service)
                        db.session.flush()
                    else:
                        # Service still open — keep its name in sync in case
                        # nmap's guess changed between scans (e.g. Unknown -> ssh)
                        existing_service.Service_Name = service_name

                # Remove TCP services that were recorded before but weren't
                # seen in this scan — they're no longer open on this host
                stale_tcp_query = sa.select(Open_TCP_Services).where(
                    Open_TCP_Services.NetDiscoveryID == device.NetDiscoveryID
                )
                if scanned_tcp_ports:
                    stale_tcp_query = stale_tcp_query.where(
                        Open_TCP_Services.Port_Number.not_in(scanned_tcp_ports)
                    )

                stale_tcp_services = db.session.scalars(stale_tcp_query).all()
                for stale_service in stale_tcp_services:
                    db.session.delete(stale_service)

                # -------------------------------------------------
                # UDP services — same add/update/remove pattern
                # -------------------------------------------------

                scanned_udp_ports = set()

                for port_number, service_data in services.get("udp", {}).items():
                    port_number_int = int(port_number)
                    scanned_udp_ports.add(port_number_int)

                    existing_service = db.session.scalar(
                        sa.select(Open_UDP_Services).join(
                            NetworkDiscovery,
                            Open_UDP_Services.NetDiscoveryID == NetworkDiscovery.NetDiscoveryID
                        )
                        .where(
                            Open_UDP_Services.NetDiscoveryID == device.NetDiscoveryID,
                            Open_UDP_Services.Port_Number == port_number_int,
                            NetworkDiscovery.Include_Device_In_Scanning.is_(True)
                        )
                    )

                    service_name = service_data.get("service_name", "Unknown")

                    if existing_service is None:
                        new_service = Open_UDP_Services(
                            Port_Number=port_number_int,
                            Service_Name=service_name,
                            NetDiscoveryID=device.NetDiscoveryID
                        )
                        db.session.add(new_service)
                        db.session.flush()
                    else:
                        existing_service.Service_Name = service_name

                stale_udp_query = sa.select(Open_UDP_Services).where(
                    Open_UDP_Services.NetDiscoveryID == device.NetDiscoveryID
                )
                if scanned_udp_ports:
                    stale_udp_query = stale_udp_query.where(
                        Open_UDP_Services.Port_Number.not_in(scanned_udp_ports)
                    )

                stale_udp_services = db.session.scalars(stale_udp_query).all()
                for stale_service in stale_udp_services:
                    db.session.delete(stale_service)

                processed_hosts += 1

                progress = calculate_progress(
                    processed_hosts,
                    total_hosts,
                    progress_weight - 10,
                    progress_weight
                    )

                if processed_hosts % 10 == 0 or processed_hosts == total_hosts:
                    update_network_discovery_status(
                        network_discovery_id,
                        DiscoveryStatus.RUNNING,
                        progress,
                        "Saving hosts to database."
                    )

        # Save everything at once
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        current_app.logger.exception(f"Failed to insert new hosts: {e}")

def _backup_running_host_cfg():
    """
    Creates a backup of Nagios' currently running hosts.cfg.

    Returns:
        pathlib.Path: Path to the backup file.
    """

    BACKUP_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%d-%m-%Y-%H-%M")
    backup_name = f"host-{timestamp}.cfg"

    backup_path = BACKUP_DIR / backup_name

    shutil.copy2(NAGIOS_HOST_CFG, backup_path)

    return backup_path

def _load_monitored_hosts(network_discovery_id=None, progress_weight=None):
    """
    Rebuilds a discovered_hosts dict from the database, in the same
    shape as discover_network()'s output:

        {
            network: {
                ip_address: {
                    "data": {"hostname": ..., "mac_address": ..., "os": ...},
                    "services": {"tcp": {port: {"service_name": ...}}, "udp": {...}}
                }
            }
        }

    Returns:
        dict: discovered_hosts-shaped dict sourced from the DB.
    """
    discovered_hosts = {}

    devices = db.session.scalars(
        sa.select(NetworkDiscovery).where(NetworkDiscovery.Include_Device_In_Scanning.is_(True))
    ).all()

    if not devices:
        return discovered_hosts

    device_ids = [device.NetDiscoveryID for device in devices]

    # Fetch all services in two queries instead of one query per device (N+1)
    tcp_services = db.session.scalars(
        sa.select(Open_TCP_Services).where(
            Open_TCP_Services.NetDiscoveryID.in_(device_ids)
        )
    ).all()

    udp_services = db.session.scalars(
        sa.select(Open_UDP_Services).where(
            Open_UDP_Services.NetDiscoveryID.in_(device_ids)
        )
    ).all()

    # Group services by their owning device, keyed by port
    tcp_by_device = {}
    for service in tcp_services:
        tcp_by_device.setdefault(service.NetDiscoveryID, {})[str(service.Port_Number)] = {
            "service_name": service.Service_Name
        }

    udp_by_device = {}
    for service in udp_services:
        udp_by_device.setdefault(service.NetDiscoveryID, {})[str(service.Port_Number)] = {
            "service_name": service.Service_Name
        }

    total_hosts = len(devices)
    processed_hosts = 0

    for device in devices:
        discovered_hosts.setdefault(device.Network, {})

        discovered_hosts[device.Network][device.IP_Address] = {
            "data": {
                "hostname": device.Hostname,
                "mac_address": device.MAC_Address,
                "os": device.OS_Type,
            },
            "services": {
                "tcp": tcp_by_device.get(device.NetDiscoveryID, {}),
                "udp": udp_by_device.get(device.NetDiscoveryID, {}),
            }
        }

        processed_hosts += 1

        if network_discovery_id is not None and (
            processed_hosts % 10 == 0 or processed_hosts == total_hosts
        ):
            progress = calculate_progress(
                processed_hosts,
                total_hosts,
                progress_weight - 10,
                progress_weight
            )
            update_network_discovery_status(
                network_discovery_id,
                DiscoveryStatus.RUNNING,
                progress,
                "Loading discovered hosts from database"
            )

    return discovered_hosts

def _build_temp_cfg_lines(main_cfg_lines, candidate_cfg_path):
    """
    Takes the real nagios.cfg's lines and returns a new list of lines
    where the line pointing to the live hosts.cfg has been swapped
    to point at our candidate file instead.

    Returns:
        tuple[list[str], bool]: (new_lines, was_replaced)
    """
    new_lines = []
    replaced = False
    for line in main_cfg_lines:
        stripped = line.strip()
        points_to_live_hosts_cfg = (
            stripped.startswith("cfg_file") and str(NAGIOS_HOST_CFG) in stripped
        )

        if points_to_live_hosts_cfg:
            new_lines.append(f"cfg_file={candidate_cfg_path}\n")
            replaced = True
        else:
            new_lines.append(line)

    return new_lines, replaced

def _write_temp_cfg(lines):
    """
    Writes the given lines to a throwaway temp file and returns its path.
    """
    with tempfile.NamedTemporaryFile(mode="w", suffix=".cfg", delete=False) as f:
        f.writelines(lines)
        return Path(f.name)

def _run_nagios_verify(main_cfg_path):
    """
    Runs `nagios -v` against the given main config file.

    Returns:
        tuple[bool, str]: (is_valid, output)
    """
    try:
        result = subprocess.run(
            [str(NAGIOS_BIN), "-v", str(main_cfg_path)],
            capture_output=True,
            text=True,
            timeout=60
        )
        is_valid = result.returncode == 0
        return is_valid, result.stdout + result.stderr

    except subprocess.TimeoutExpired:
        return False, "Nagios validation timed out."

    except FileNotFoundError:
        return False, f"Nagios binary not found at {NAGIOS_BIN}."

def _validate_config(cfg_path):
    """
    Validates a candidate host config file WITHOUT touching the live
    running config.

    How it works, step by step:
      1. Read the real nagios.cfg
      2. Swap its hosts.cfg reference to point at our candidate file instead
      3. Write that as a throwaway temp file
      4. Run `nagios -v` against the temp file
      5. Delete the temp file, return whatever Nagios said

    Args:
        cfg_path (pathlib.Path): Path to the candidate host cfg file.

    Returns:
        tuple[bool, str]: (is_valid, output)
    """
    if not NAGIOS_MAIN_CFG.exists():
        return False, f"Nagios main config not found at {NAGIOS_MAIN_CFG}"

    # Step 1: read the real nagios.cfg
    with open(NAGIOS_MAIN_CFG) as f:
        main_cfg_lines = f.readlines()

    # Step 2: point it at our candidate file instead of the live hosts.cfg
    temp_cfg_lines, replaced = _build_temp_cfg_lines(main_cfg_lines, cfg_path)

    if not replaced:
        return False, (
            f"Could not find a cfg_file directive pointing to {NAGIOS_HOST_CFG} "
            f"inside {NAGIOS_MAIN_CFG}. Nothing was validated."
        )

    # Step 3: write it out as a throwaway file
    temp_cfg_path = _write_temp_cfg(temp_cfg_lines)

    # Step 4: actually run the validation
    try:
        return _run_nagios_verify(temp_cfg_path)

    # Step 5: always clean up the temp file, pass or fail
    finally:
        temp_cfg_path.unlink(missing_ok=True)

def _apply_new_host_cfg(cfg_path):
    """
    Applies a validated candidate host config as the new live Nagios config.

    IMPORTANT: This assumes cfg_path has ALREADY been validated via
    _validate_config(). This function does not re-validate — call order
    matters (see __main__).

    Steps:
      1. Backup the current live hosts.cfg
      2. Copy the candidate config into the live Nagios path
      3. Reload Nagios so it picks up the new config
      4. If the reload fails, roll back to the backup automatically

    Args:
        cfg_path (pathlib.Path): Path to the validated candidate config file.

    Returns:
        tuple[bool, str]: (success, message)
            success - True if the config was applied and Nagios reloaded cleanly
            message - human-readable detail, useful for logging/UI feedback
    """
    try:
        backup_path = _backup_running_host_cfg()
    except Exception as e:
        return False, f"Failed to back up current config, aborting apply: {e}"

    try:
        shutil.copy2(cfg_path, NAGIOS_HOST_CFG)
    except Exception as e:
        return False, f"Failed to copy new config into place: {e}"

    try:
        result = subprocess.run(
            ["sudo", "-n", "systemctl", "reload", "nagios"],
            capture_output=True,
            text=True,
            timeout=30
        )

        if result.returncode != 0:
            current_app.logger.error(result.stdout + result.stderr)

    except Exception as e:
        # Reload failed — roll back to the last known-good config so Nagios
        # never keeps running on a broken/half-applied file
        shutil.copy2(backup_path, NAGIOS_HOST_CFG)
        return False, (
            f"Failed to reload Nagios after applying new config. "
            f"Rolled back to backup at {backup_path}. Error: {e}"
        )

    return True, f"Applied {cfg_path} successfully. Backup stored at {backup_path}"

def _create_hostname(network_discovery_id, discovered_hosts, progress_weight):
    total_hosts = sum(len(hosts) for hosts in discovered_hosts.values())
    processed_hosts = 0

    for hosts in discovered_hosts.values():
        for ip, host_data in hosts.items():
            if host_data["data"]["hostname"] == "Unknown":
                host_data["data"]["hostname"] = f"{ip}.{DOMAIN}"

            processed_hosts += 1

            progress = calculate_progress(
                processed_hosts,
                total_hosts,
                progress_weight - 10,
                progress_weight
            )

            if processed_hosts % 10 == 0 or processed_hosts == total_hosts:
                update_network_discovery_status(
                    network_discovery_id,
                    DiscoveryStatus.RUNNING,
                    progress,
                    "Creating hostnames"
                )

    return discovered_hosts

def _override_service_names(network_discovery_id, discovered_hosts, protocol, service_overrides,progress_weight):
    total_services = sum(
        len(host_data["services"].get(protocol, {}))
        for hosts in discovered_hosts.values()
        for host_data in hosts.values()
    )

    if total_services == 0:
        update_network_discovery_status(
            network_discovery_id,
            DiscoveryStatus.RUNNING,
            progress_weight,
            f"No {protocol.upper()} services to override"
        )
        return discovered_hosts

    processed_services = 0

    for hosts in discovered_hosts.values():

        for host_data in hosts.values():

            services = host_data["services"].get(protocol, {})

            for port_id, service_data in services.items():

                service_name = service_data.get(
                    "service_name",
                    "Unknown"
                )

                # Override Nmap's service name if configured
                service_data["service_name"] = service_overrides.get(
                    port_id,
                    service_name
                )

                processed_services += 1
                    
                progress = calculate_progress(
                                processed_services,
                                total_services,
                                progress_weight - 5,
                                progress_weight
                            )
                    
                if processed_services % 10 == 0 or processed_services == total_services:
                    update_network_discovery_status(
                        network_discovery_id,
                        DiscoveryStatus.RUNNING,
                        progress,
                        f"Overriding {protocol} service names"
                    )

    return discovered_hosts   

def discover_network_create_hosts(app, user_id, stop_event):
    network_discovery_id = None
   
    with app.app_context():
        try:

            print("Created Log")
            network_discovery_id = create_network_discovery_status(user_id).DiscoveryStatusID

            if stop_event.is_set():
                return
            
            # Gets the network info
            print("Discovering Hosts")
            discovered_hosts = discover_network(network_discovery_id, PROGRESS_WEIGHT[0], stop_event)

            if discovered_hosts is None:
                update_network_discovery_status(
                    network_discovery_id,
                    DiscoveryStatus.INTERRUPTED,
                    100,
                    "Network discovery was stopped.",
                    datetime.now(timezone.utc)
                )
                return

            if stop_event.is_set():
                return
            
            # Creates hostnames for hosts that don't have names
            discovered_hosts = _create_hostname(network_discovery_id, discovered_hosts, PROGRESS_WEIGHT[1])

            if stop_event.is_set():
                return
            
            # Overrides services names due to NMAP not always being right
            discovered_hosts = _override_service_names(network_discovery_id, discovered_hosts,"tcp", TCP_SERVICE_OVERRIDES, PROGRESS_WEIGHT[2])
            discovered_hosts = _override_service_names(network_discovery_id, discovered_hosts,"udp", UDP_SERVICE_OVERRIDES, PROGRESS_WEIGHT[3])

            if stop_event.is_set():
                return
            
            # Save it to the database
            _save_discovered_hosts(discovered_hosts, network_discovery_id, PROGRESS_WEIGHT[4])

            if stop_event.is_set():
                return
            
            system_hosts = _load_monitored_hosts(network_discovery_id, PROGRESS_WEIGHT[5])

            if stop_event.is_set():
                return
            
            new_cfg = _create_host_cfg_file(system_hosts)
            print(f"Created: {new_cfg}")
            update_network_discovery_status(
                network_discovery_id,
                DiscoveryStatus.RUNNING,
                PROGRESS_WEIGHT[6],
                "Generated new Nagios configuration"
            )

            if stop_event.is_set():
                return
            
            update_network_discovery_status(
                network_discovery_id,
                DiscoveryStatus.RUNNING,
                PROGRESS_WEIGHT[7],
                "Validating config"
            )
            
            is_valid, result = _validate_config(new_cfg)

            if stop_event.is_set():
                return
            
            if is_valid:
                applied, apply_message = _apply_new_host_cfg(new_cfg)

                if applied:
                    update_network_discovery_status(
                        network_discovery_id,
                        DiscoveryStatus.SUCCESS,
                        PROGRESS_WEIGHT[8],
                        "New host.cfg successfully applied",
                        datetime.now(timezone.utc)
                        )
                    print(apply_message)
                else:
                    update_network_discovery_status(
                        network_discovery_id,
                        DiscoveryStatus.FAILED,
                        PROGRESS_WEIGHT[8],
                        "Config not applied",
                        datetime.now(timezone.utc)
                        )
                    print(apply_message)

            else:
                update_network_discovery_status(
                    network_discovery_id,
                    DiscoveryStatus.FAILED,
                    PROGRESS_WEIGHT[8],
                    "Config failed to validate",
                    datetime.now(timezone.utc),
                    result
                )
                print(result)
        except Exception as e:
            app.logger.exception(
                f"Network discovery failed."
            )
            if network_discovery_id is not None:
                update_network_discovery_status(
                    network_discovery_id,
                    DiscoveryStatus.FAILED,
                    100,
                    "Network discovery failed",
                    datetime.now(timezone.utc),
                    str(e)
                )

def add_ncpa_port(app, successful_device, ncpa_deployment_status_id, stop_event):
    with app.app_context():
        try:
            total_devices = len(successful_device)
            processed_devices = 0

            # Add the NCPA port to Open_TCP_Services for each device that was
            # successfully deployed. Unlike discover_network_create_hosts,
            # there's no nmap scan here — the port was already verified open
            # by the caller (after NCPA install), so we just insert an
            # Open_TCP_Services entry for NCPA_PORT on each device.
            for device_id in successful_device:
                if stop_event.is_set():
                    update_ncpa_deployment_status(
                        ncpa_deployment_status_id,
                        DeploymentStatus.INTERRUPTED,
                        calculate_progress(processed_devices, total_devices, 0, ADD_NCPA_PORT_PROGRESS_WEIGHT[0]),
                        "Adding NCPA port was stopped by user."
                    )
                    return

                existing_service = db.session.scalar(
                    sa.select(Open_TCP_Services)
                    .join(NetworkDiscovery, 
                          Open_TCP_Services.NetDiscoveryID == NetworkDiscovery.NetDiscoveryID)
                    .where(
                        Open_TCP_Services.NetDiscoveryID == device_id,
                        Open_TCP_Services.Port_Number == int(NCPA_PORT),
                        NetworkDiscovery.Include_Device_In_Scanning.is_(True)
                    )
                )

                if existing_service is None:
                    new_service = Open_TCP_Services(
                        Port_Number=int(NCPA_PORT),
                        Service_Name="ncpa",
                        NetDiscoveryID=device_id
                    )
                    db.session.add(new_service)

                processed_devices += 1

                progress = calculate_progress(
                    processed_devices,
                    total_devices,
                    0,
                    ADD_NCPA_PORT_PROGRESS_WEIGHT[0]
                )

                if processed_devices % 10 == 0 or processed_devices == total_devices:
                    update_ncpa_deployment_status(
                        ncpa_deployment_status_id,
                        DeploymentStatus.RUNNING,
                        progress,
                        "Adding NCPA port to database."
                    )

            db.session.commit()

            if stop_event.is_set():
                update_ncpa_deployment_status(
                    ncpa_deployment_status_id,
                    DeploymentStatus.INTERRUPTED,
                    ADD_NCPA_PORT_PROGRESS_WEIGHT[0],
                    "Adding NCPA port was stopped by user."
                )
                return

            # Reload the monitored hosts from the database so the newly added
            # port is reflected in the generated config
            system_hosts = _load_monitored_hosts()
            update_ncpa_deployment_status(
                ncpa_deployment_status_id,
                DeploymentStatus.RUNNING,
                ADD_NCPA_PORT_PROGRESS_WEIGHT[1],
                "Loaded monitored hosts from database."
            )

            if stop_event.is_set():
                update_ncpa_deployment_status(
                    ncpa_deployment_status_id,
                    DeploymentStatus.INTERRUPTED,
                    ADD_NCPA_PORT_PROGRESS_WEIGHT[1],
                    "Adding NCPA port was stopped by user."
                )
                return

            # Generate a new Nagios host config file from the updated hosts
            new_cfg = _create_host_cfg_file(system_hosts)
            print(f"Created: {new_cfg}")
            update_ncpa_deployment_status(
                ncpa_deployment_status_id,
                DeploymentStatus.RUNNING,
                ADD_NCPA_PORT_PROGRESS_WEIGHT[2],
                "Generated new Nagios configuration."
            )

            if stop_event.is_set():
                update_ncpa_deployment_status(
                    ncpa_deployment_status_id,
                    DeploymentStatus.INTERRUPTED,
                    ADD_NCPA_PORT_PROGRESS_WEIGHT[2],
                    "Adding NCPA port was stopped by user."
                )
                return

            # Validate the candidate config against the live nagios.cfg
            # before touching anything live
            is_valid, result = _validate_config(new_cfg)
            update_ncpa_deployment_status(
                ncpa_deployment_status_id,
                DeploymentStatus.RUNNING,
                ADD_NCPA_PORT_PROGRESS_WEIGHT[3],
                "Validated new Nagios configuration."
            )

            if stop_event.is_set():
                update_ncpa_deployment_status(
                    ncpa_deployment_status_id,
                    DeploymentStatus.INTERRUPTED,
                    ADD_NCPA_PORT_PROGRESS_WEIGHT[3],
                    "Adding NCPA port was stopped by user."
                )
                return

            # If valid, apply it as the new live config: backs up the running
            # hosts.cfg, copies the new one into place, reloads Nagios, and
            # rolls back automatically if the reload fails
            if is_valid:
                applied, apply_message = _apply_new_host_cfg(new_cfg)

                if applied:
                    update_ncpa_deployment_status(
                        ncpa_deployment_status_id,
                        DeploymentStatus.SUCCESS,
                        ADD_NCPA_PORT_PROGRESS_WEIGHT[4],
                        "New host.cfg successfully applied.",
                        datetime.now(timezone.utc)
                    )
                else:
                    update_ncpa_deployment_status(
                        ncpa_deployment_status_id,
                        DeploymentStatus.FAILED,
                        ADD_NCPA_PORT_PROGRESS_WEIGHT[4],
                        "Config not applied.",
                        datetime.now(timezone.utc),
                        apply_message
                    )
                print(apply_message)
            else:
                update_ncpa_deployment_status(
                    ncpa_deployment_status_id,
                    DeploymentStatus.FAILED,
                    ADD_NCPA_PORT_PROGRESS_WEIGHT[4],
                    "Config failed to validate.",
                    datetime.now(timezone.utc),
                    result
                )
                print(result)

        except Exception as e:
            db.session.rollback()
            app.logger.exception("Failed to add NCPA port")
            update_ncpa_deployment_status(
                ncpa_deployment_status_id,
                DeploymentStatus.FAILED,
                100,
                "Failed to add NCPA port.",
                datetime.now(timezone.utc),
                str(e)
            )