"""
Plugin registry for the Nagios configuration generated by Network Discovery.

Every monitored service is resolved from a PLUGIN NAME (snmp, ncpa, http, ...)
to a PluginDefinition — never from a port. A port is just one of the plugin's
variables: defaulted by the definition, replaced by the port the service was
actually discovered on, and overridable per host.

Resolution order
----------------
    discovered service name ──► plugin name   (name/alias match, else the
            │                                  generic "tcp" plugin; unmatched
            │                                  UDP ports are skipped)
            ▼
    PluginDefinition ──► transports, variables, checks, command layout
            │
            ▼
    variables = definition defaults
              < app config defaults   (e.g. SNMP_COMMUNITY_STRING, SNMP_OIDS)
              < discovery facts       (port found on, NCPA token, partitions)
              < host overrides        (NetworkDiscovery.Plugin_Variables)
            │
            ▼
    checks(variables) ──► one ServiceCheck per metric (SNMP OID, NCPA metric…)
            │
            ▼
    resolve_plugin_command() ──► "pinpoint_nd_snmp!161!public!1.3.6.1…!"

Each definition renders its own Nagios `define command` object named
pinpoint_nd_<plugin>, so generated configs never depend on which commands
happen to exist in the stock commands.cfg. The pinpoint_nd_ prefix keeps
them distinct from Plugin Manager's own pinpoint_<plugin> commands (see
app/api/plugin/monitoring_config.py).

Adding a plugin — including one that produces many services — only means
adding a PluginDefinition to PLUGIN_DEFINITIONS. Neither the resolver nor
the config generator needs to change.

Security: every variable value ends up inside a Nagios object file and a
shell-executed command line. Values are single-quoted in the generated
command_line and any character that could escape that quoting, split
Nagios arguments (!), expand a macro ($) or start a cfg comment (;) is
rejected. Error messages name the offending variable, never its value, so
secrets such as the NCPA token are not leaked into logs.
"""
import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Callable, Optional

COMMAND_NAME_PREFIX = "pinpoint_nd_"

# Characters that could break out of a single-quoted shell argument, split
# Nagios' "!" argument list, expand a Nagios macro, or start a cfg comment.
FORBIDDEN_VALUE_CHARACTERS = frozenset("'\"`!$;\\\n\r\0")

# Characters Nagios refuses in object names (illegal_object_name_chars
# default), plus whitespace, which would make service names awkward to use.
ILLEGAL_NAME_CHARACTERS = re.compile(r"[`~!$%^&*|'\"<>?,()=\s]")

COMMAND_TEMPLATE = """define command {{
    command_name    {command_name}
    command_line    {command_line}
}}
"""


class Transport(Enum):
    TCP = "TCP"
    UDP = "UDP"


class PluginConfigurationError(ValueError):
    """
    Raised when a plugin cannot be resolved into a valid Nagios command —
    unknown plugin, missing required variable, unsafe value, or a transport
    the plugin does not support. Messages never contain variable values.
    """


@dataclass(frozen=True)
class ServiceCheck:
    """
    One Nagios service produced by a plugin. metric is None for plugins that
    produce a single service (e.g. ssh); otherwise it names the data point
    (e.g. "uptime" for an SNMP OID, "cpu" for an NCPA metric). variables are
    layered on top of the plugin's resolved variables for this service only.
    """
    metric: Optional[str]
    variables: dict = field(default_factory=dict)


def single_check(variables):
    """
    Default checks provider: the plugin produces exactly one service using
    the plugin-level variables unchanged.
    """
    return [ServiceCheck(metric=None)]


def snmp_checks(variables):
    """
    One service per configured OID. Expects variables["oids"] to be a list of
    {"metric": ..., "oid": ...} dicts; any other key in an entry (warning,
    critical, label, units) is passed through as a per-service variable.
    """
    oids = variables.get("oids") or []
    if not isinstance(oids, list):
        raise PluginConfigurationError("SNMP variable 'oids' must be a list.")

    checks = []
    for entry in oids:
        if not isinstance(entry, dict) or not entry.get("oid") or not entry.get("metric"):
            raise PluginConfigurationError("Each SNMP OID entry needs an 'oid' and a 'metric'.")

        per_service = dict(entry)
        metric = per_service.pop("metric")
        checks.append(ServiceCheck(metric=metric, variables=per_service))
    return checks


def ncpa_checks(variables):
    """
    One service per configured NCPA metric. Expects variables["metrics"] to be
    a list of {"metric": ..., "path": ...} dicts. A path containing
    "{partition}" expands to one service per entry in variables["partitions"]
    (discovered during NCPA installation); if no partitions are known, the
    entry's "fallback_path" is used as a single service instead.
    """
    metrics = variables.get("metrics") or []
    partitions = variables.get("partitions") or []
    if not isinstance(metrics, list) or not isinstance(partitions, list):
        raise PluginConfigurationError("NCPA variables 'metrics' and 'partitions' must be lists.")

    checks = []
    for entry in metrics:
        if not isinstance(entry, dict) or not entry.get("path") or not entry.get("metric"):
            raise PluginConfigurationError("Each NCPA metric entry needs a 'path' and a 'metric'.")

        per_service = dict(entry)
        metric = per_service.pop("metric")
        path = per_service.pop("path")
        fallback_path = per_service.pop("fallback_path", None)

        if "{partition}" not in path:
            checks.append(ServiceCheck(metric=metric, variables={**per_service, "metric_path": path}))
        elif partitions:
            for partition in partitions:
                checks.append(ServiceCheck(
                    metric=f"{metric}_{partition}",
                    variables={**per_service, "metric_path": path.replace("{partition}", str(partition))},
                ))
        elif fallback_path:
            checks.append(ServiceCheck(metric=metric, variables={**per_service, "metric_path": fallback_path}))
    return checks


@dataclass(frozen=True)
class PluginDefinition:
    """
    Everything needed to turn a plugin name into Nagios services.

    arguments are (flag, variable) pairs that are always passed, in order, as
    $ARG1$..$ARGn$ — so every one of them is required. options map optional
    variables to their flag; whichever are set are rendered together into the
    final $ARG$. fixed_flags are literal flags every invocation needs.
    config_defaults map variable names to app config keys used as defaults.
    """
    name: str
    check_plugin: str
    transports: tuple
    arguments: tuple = ()
    options: dict = field(default_factory=dict)
    defaults: dict = field(default_factory=dict)
    config_defaults: dict = field(default_factory=dict)
    aliases: tuple = ()
    host_flag: str = "-H"
    fixed_flags: str = ""
    checks: Callable = single_check

    @property
    def command_name(self):
        return f"{COMMAND_NAME_PREFIX}{self.name}"

    @property
    def command_line(self):
        parts = [f"$USER1$/{self.check_plugin}", self.host_flag, "$HOSTADDRESS$"]
        if self.fixed_flags:
            parts.append(self.fixed_flags)
        for index, (flag, _variable) in enumerate(self.arguments, start=1):
            parts.append(f"{flag} '$ARG{index}$'")
        parts.append(f"$ARG{len(self.arguments) + 1}$")
        return " ".join(parts)


# ==========================================================
# PLUGIN DEFINITIONS
# ==========================================================

# Flags follow spec files/Plugins_List.md. check_udp and check_ftp are not
# catalogued there, but both are installed by nagios-plugins 2.4.12 as
# aliases of check_tcp and were already used by the previous command maps.
PLUGIN_DEFINITIONS = {
    definition.name: definition
    for definition in (
        PluginDefinition(
            name="tcp",
            check_plugin="check_tcp",
            transports=(Transport.TCP,),
            arguments=(("-p", "port"),),
            options={"warning": "-w", "critical": "-c"},
        ),
        PluginDefinition(
            name="udp",
            check_plugin="check_udp",
            transports=(Transport.UDP,),
            arguments=(("-p", "port"),),
            # check_udp aborts without -s/-e; empty strings let it run.
            # Network Discovery no longer generates this check: most UDP
            # services ignore an empty probe, so it cannot tell up from down.
            # UDP ports without a protocol plugin are skipped and recorded in
            # SkippedService instead (create_host_cfg.build_host_services).
            # Kept so existing pinpoint_nd_udp services still resolve.
            fixed_flags="-s '' -e ''",
            options={"warning": "-w", "critical": "-c"},
        ),
        PluginDefinition(
            name="snmp",
            check_plugin="check_snmp",
            transports=(Transport.UDP,),
            arguments=(("-p", "port"), ("-C", "community"), ("-o", "oid")),
            options={
                "protocol": "-P",
                "warning": "-w",
                "critical": "-c",
                "label": "-l",
                "units": "-u",
            },
            defaults={"port": 161, "community": "public"},
            config_defaults={
                "port": "SNMP_PORT",
                "community": "SNMP_COMMUNITY_STRING",
                "oids": "SNMP_OIDS",
            },
            checks=snmp_checks,
        ),
        PluginDefinition(
            name="ncpa",
            check_plugin="check_ncpa",
            transports=(Transport.TCP,),
            arguments=(("-P", "port"), ("-t", "token"), ("-M", "metric_path")),
            options={
                "warning": "-w",
                "critical": "-c",
                "units": "-u",
                "queryargs": "-q",
            },
            defaults={"port": 5693},
            config_defaults={"port": "NCPA_PORT", "metrics": "NCPA_METRICS"},
            checks=ncpa_checks,
        ),
        PluginDefinition(
            name="http",
            check_plugin="check_http",
            transports=(Transport.TCP,),
            arguments=(("-p", "port"),),
            options={"url": "-u", "warning": "-w", "critical": "-c"},
            defaults={"port": 80},
        ),
        PluginDefinition(
            name="https",
            check_plugin="check_http",
            transports=(Transport.TCP,),
            arguments=(("-p", "port"),),
            fixed_flags="-S",
            options={"url": "-u", "warning": "-w", "critical": "-c", "certificate_days": "-C"},
            defaults={"port": 443},
        ),
        PluginDefinition(
            name="ssh",
            check_plugin="check_ssh",
            transports=(Transport.TCP,),
            arguments=(("-p", "port"),),
            defaults={"port": 22},
        ),
        PluginDefinition(
            name="ftp",
            check_plugin="check_ftp",
            transports=(Transport.TCP,),
            arguments=(("-p", "port"),),
            options={"warning": "-w", "critical": "-c"},
            defaults={"port": 21},
        ),
        PluginDefinition(
            name="smtp",
            check_plugin="check_smtp",
            transports=(Transport.TCP,),
            arguments=(("-p", "port"),),
            options={"warning": "-w", "critical": "-c"},
            defaults={"port": 25},
        ),
        PluginDefinition(
            name="mysql",
            check_plugin="check_mysql",
            transports=(Transport.TCP,),
            # check_mysql cannot log in without a user; hosts without one
            # configured fall back to a plain TCP port check.
            arguments=(("-P", "port"), ("-u", "user")),
            options={"password": "-p", "database": "-d"},
            defaults={"port": 3306},
        ),
        PluginDefinition(
            name="dns",
            check_plugin="check_dns",
            transports=(Transport.TCP, Transport.UDP),
            # check_dns' -H is the name to LOOK UP; the target server is -s.
            # check_dns has no port option, so port only names the service.
            host_flag="-s",
            arguments=(("-H", "lookup"),),
            options={"expected_address": "-a", "warning": "-w", "critical": "-c"},
            defaults={"port": 53, "lookup": "localhost"},
            aliases=("domain",),
        ),
        PluginDefinition(
            name="ntp",
            check_plugin="check_ntp_time",
            transports=(Transport.UDP,),
            # check_ntp is deprecated per Plugins_List.md; check_ntp_time
            # is its replacement for offset checks.
            arguments=(("-p", "port"),),
            options={"warning": "-w", "critical": "-c"},
            defaults={"port": 123},
        ),
    )
}

GENERIC_PLUGIN_FOR_TRANSPORT = {
    Transport.TCP: "tcp",
    Transport.UDP: "udp",
}


# ==========================================================
# LOOKUPS
# ==========================================================

def get_plugin_definition(plugin_name):
    """
    Return the PluginDefinition registered under plugin_name (case-
    insensitive). Raises PluginConfigurationError if there is none.
    """
    definition = PLUGIN_DEFINITIONS.get(str(plugin_name).lower())
    if definition is None:
        raise PluginConfigurationError(f"Unknown plugin '{plugin_name}'.")
    return definition


def find_plugin_by_name_or_alias(name):
    """
    Return the PluginDefinition whose name or alias matches name
    (case-insensitive), or None.
    """
    key = str(name or "").lower().strip()
    if key in PLUGIN_DEFINITIONS:
        return PLUGIN_DEFINITIONS[key]
    for definition in PLUGIN_DEFINITIONS.values():
        if key in definition.aliases:
            return definition
    return None


def resolve_plugin_name(service_name, transport):
    """
    Map a discovered service name (nmap's guess, after the configured
    overrides) to a plugin name. The service must match a plugin's name or
    alias AND that plugin must support the transport it was found on;
    anything else is monitored by the transport's generic port-check plugin.
    """
    definition = find_plugin_by_name_or_alias(service_name)
    if definition is not None and transport in definition.transports:
        return definition.name
    return GENERIC_PLUGIN_FOR_TRANSPORT[transport]


def plugin_for_command(command_name):
    """
    Return the check plugin (e.g. "check_snmp") behind a Nagios command name
    reported by statusjson.cgi, or None if it is not one this registry
    generates. Arguments after "!" are ignored.
    """
    name = str(command_name or "").split("!")[0].strip()
    if not name.startswith(COMMAND_NAME_PREFIX):
        return None
    definition = PLUGIN_DEFINITIONS.get(name[len(COMMAND_NAME_PREFIX):])
    return definition.check_plugin if definition else None


# ==========================================================
# RESOLUTION
# ==========================================================

def resolve_plugin_variables(plugin_name, app_config=None, discovered=None, overrides=None):
    """
    Merge a plugin's variables from lowest to highest precedence: definition
    defaults, app config defaults, discovery facts (e.g. the port the service
    was found on), then per-host overrides. Returns a new dict; inputs are
    not modified.
    """
    definition = get_plugin_definition(plugin_name)
    variables = dict(definition.defaults)

    for variable, config_key in definition.config_defaults.items():
        if app_config is not None and app_config.get(config_key) is not None:
            variables[variable] = app_config[config_key]

    for layer in (discovered, overrides):
        if layer:
            variables.update({key: value for key, value in layer.items() if value is not None})

    return variables


def validate_variable_value(variable, value):
    """
    Return value as a string if it is safe to place inside a Nagios command
    argument, otherwise raise PluginConfigurationError naming the variable.
    Ports must be integers between 1 and 65535.
    """
    text = str(value)

    if variable == "port":
        if not text.isdigit() or not 1 <= int(text) <= 65535:
            raise PluginConfigurationError("Variable 'port' must be an integer between 1 and 65535.")
        return str(int(text))

    if any(character in FORBIDDEN_VALUE_CHARACTERS for character in text):
        raise PluginConfigurationError(f"Variable '{variable}' contains a forbidden character.")
    return text


def resolve_plugin_command(plugin_name, variables, transport=None):
    """
    Build the Nagios check_command string for one service of plugin_name,
    e.g. "pinpoint_nd_snmp!161!public!1.3.6.1.2.1.1.3.0!".

    Validates that the plugin supports the requested transport, that every
    required variable is present, and that every value is safe. Optional
    variables the plugin knows a flag for are rendered into the final
    argument; unknown variables are ignored.
    """
    definition = get_plugin_definition(plugin_name)

    if transport is not None and transport not in definition.transports:
        raise PluginConfigurationError(
            f"Plugin '{definition.name}' does not support {transport.value}."
        )

    arguments = []
    for _flag, variable in definition.arguments:
        value = variables.get(variable)
        if value is None or str(value) == "":
            raise PluginConfigurationError(
                f"Plugin '{definition.name}' requires variable '{variable}'."
            )
        arguments.append(validate_variable_value(variable, value))

    options = []
    for variable, flag in definition.options.items():
        value = variables.get(variable)
        if value is None or str(value) == "":
            continue
        options.append(f"{flag} '{validate_variable_value(variable, value)}'")

    arguments.append(" ".join(options))
    return "!".join([definition.command_name] + arguments)


def build_service_checks(plugin_name, variables):
    """
    Expand a plugin's resolved variables into its ServiceChecks, each paired
    with the fully-merged variables for that one service. Returns a list of
    (ServiceCheck, service_variables) tuples.
    """
    definition = get_plugin_definition(plugin_name)
    checks = []
    for check in definition.checks(variables):
        checks.append((check, {**variables, **check.variables}))
    return checks


def render_command_definition(plugin_name):
    """
    Return the Nagios `define command` object for plugin_name.
    """
    definition = get_plugin_definition(plugin_name)
    return COMMAND_TEMPLATE.format(
        command_name=definition.command_name,
        command_line=definition.command_line,
    )


def sanitize_name_part(text):
    """
    Make text safe to use inside a Nagios service_description by replacing
    characters Nagios rejects in object names with "_". Returns "unknown"
    for empty input.
    """
    cleaned = ILLEGAL_NAME_CHARACTERS.sub("_", str(text or "").strip())
    return cleaned or "unknown"
