"""
tests/unit/test_plugin_descriptions.py — Plugin descriptions, categories and
documentation links (Plugin Driven Monitoring Plan, Phase 1).

Covers:
  - plugin_catalog_data.py / scripts/build_plugin_descriptions.py: catalog
    coverage, limits, and that the committed file matches its generator
  - plugin_descriptions.py: lookups, --help parsing, fill-if-empty rules
  - scanner.py integration: new, existing and unknown plugins
  - GET /api/plugin/<id>: description, category and documentation_url
"""
import os
import subprocess
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from app.api.plugin.plugin_command_defaults import PLUGIN_COMMAND_DEFAULTS
from app.api.plugin.plugin_catalog_data import PLUGIN_CATALOG
from app.api.plugin.plugin_descriptions import (
    MAX_CATEGORY_LENGTH,
    MAX_DESCRIPTION_LENGTH,
    clean_text,
    documentation_url,
    extract_help_description,
    fill_missing_metadata,
    get_catalog_entry,
    parse_help_description,
)
from app.api.plugin.scanner import scan_plugin_directory, sync_plugin_inventory
from app.network_discovery.plugin_registry import PLUGIN_DEFINITIONS
from app.plugin_models import Plugin, PluginSource, PluginStatus, PluginType

SERVER_DIR = Path(__file__).resolve().parents[2]

REAL_HELP_OUTPUT = """check_ssh v2.4.12 (nagios-plugins 2.4.12)
Copyright (c) 1999 Remi Paulmier <remi@sinfomic.fr>
Copyright (c) 2000-2014 Nagios Plugin Development Team
\t<devel@nagios-plugins.org>

Try to connect to an SSH server at specified server and port

Usage:
 check_ssh [-46] [-t <timeout>] [-r <remote version>] [-p <port>] <host>

Options:
 -h, --help
    Print detailed help screen
"""


def _completed(output=""):
    result = MagicMock()
    result.stdout = output
    result.stderr = ""
    result.returncode = 0
    return result


def _write_fake_plugin(directory, name):
    path = os.path.join(directory, name)
    with open(path, "w") as f:
        f.write("#!/bin/sh\necho placeholder\n")
    return path


def _run_by_flag(version_output, help_output):
    """A subprocess.run replacement that answers --version and --help differently."""
    def fake_run(args, **kwargs):
        return _completed(help_output if "--help" in args else version_output)
    return fake_run


_ALWAYS_EXECUTABLE = patch("app.api.plugin.scanner.is_executable", return_value=True)


# ─── catalog ──────────────────────────────────────────────────────────────────

class TestCatalog:
    def test_covers_every_bundled_plugin_with_a_default_command(self):
        missing = sorted(set(PLUGIN_COMMAND_DEFAULTS) - set(PLUGIN_CATALOG))
        assert missing == []

    def test_covers_every_check_plugin_network_discovery_uses(self):
        used = {definition.check_plugin for definition in PLUGIN_DEFINITIONS.values()}
        assert sorted(used - set(PLUGIN_CATALOG)) == []

    def test_covers_plugins_not_listed_in_plugins_list_md(self):
        # check_ftp and check_udp are generated by Network Discovery but are
        # not in Plugins_List.md, so they come from the official manual.
        assert "check_ftp" in PLUGIN_CATALOG
        assert "check_udp" in PLUGIN_CATALOG

    def test_every_entry_is_complete_and_within_column_limits(self):
        for name, entry in PLUGIN_CATALOG.items():
            assert entry["description"].strip(), name
            assert len(entry["description"]) <= MAX_DESCRIPTION_LENGTH, name
            assert entry["category"].strip(), name
            assert len(entry["category"]) <= MAX_CATEGORY_LENGTH, name
            assert entry["documentation_url"].startswith("https://"), name

    def test_ldaps_shares_the_ldap_manual_page(self):
        assert PLUGIN_CATALOG["check_ldaps"]["documentation_url"].endswith("/check_ldap.html")

    def test_ncpa_links_to_the_ncpa_project_not_nagios_plugins(self):
        assert PLUGIN_CATALOG["check_ncpa"]["documentation_url"] == "https://www.nagios.org/ncpa/"

    def test_committed_file_matches_its_generator(self):
        result = subprocess.run(
            [sys.executable, "scripts/build_plugin_descriptions.py", "--check"],
            cwd=SERVER_DIR, capture_output=True, text=True,
        )
        assert result.returncode == 0, result.stdout + result.stderr


# ─── lookups ──────────────────────────────────────────────────────────────────

class TestLookups:
    def test_known_plugin(self):
        entry = get_catalog_entry("check_ssh")
        assert entry["description"] == "Check SSH server connection."
        assert entry["category"] == "Network Services"

    def test_unknown_plugin(self):
        assert get_catalog_entry("check_not_real") is None
        assert documentation_url("check_not_real") is None

    def test_documentation_url(self):
        assert documentation_url("check_http") == "https://www.nagios-plugins.org/doc/man/check_http.html"


class TestCleanText:
    def test_collapses_whitespace_and_control_characters(self):
        assert clean_text("a \n\t b\x00  c", 50) == "a b c"

    def test_empty_becomes_none(self):
        assert clean_text("  \n ", 50) is None
        assert clean_text(None, 50) is None

    def test_truncates_with_ellipsis(self):
        text = clean_text("word " * 200, 40)
        assert len(text) <= 40
        assert text.endswith("…")


# ─── --help parsing ───────────────────────────────────────────────────────────

class TestParseHelpDescription:
    def test_skips_header_and_stops_at_usage(self):
        assert parse_help_description(REAL_HELP_OUTPUT) == (
            "Try to connect to an SSH server at specified server and port"
        )

    def test_skips_the_warranty_paragraph(self):
        output = (
            "check_foo v1.0 (nagios-plugins 1.0)\n\n"
            "The nagios plugins come with ABSOLUTELY NO WARRANTY. You may redistribute\n"
            "copies of the plugins under the terms of the GNU General Public License.\n\n"
            "This plugin tests foo connections\nwith the specified host.\n\n"
            "Usage:\n check_foo -H host\n"
        )
        assert parse_help_description(output) == (
            "This plugin tests foo connections with the specified host."
        )

    def test_no_description_before_usage(self):
        assert parse_help_description("check_foo v1.0\n\nUsage:\n check_foo\n") is None

    def test_empty_output(self):
        assert parse_help_description("") is None
        assert parse_help_description(None) is None

    def test_version_only_output_is_not_a_description(self):
        assert parse_help_description("v1.0\n\n") is None


class TestExtractHelpDescription:
    def test_runs_help_and_parses_it(self):
        with patch("app.api.plugin.plugin_descriptions.subprocess.run",
                   return_value=_completed(REAL_HELP_OUTPUT)) as run:
            description = extract_help_description("/opt/plugins/check_ssh")

        assert description == "Try to connect to an SSH server at specified server and port"
        assert run.call_args.args[0] == ["/opt/plugins/check_ssh", "--help"]
        assert run.call_args.kwargs["timeout"] > 0

    @pytest.mark.parametrize("error", [subprocess.TimeoutExpired("x", 5), OSError("nope"), PermissionError()])
    def test_failures_return_none(self, error):
        with patch("app.api.plugin.plugin_descriptions.subprocess.run", side_effect=error):
            assert extract_help_description("/opt/plugins/check_ssh") is None


# ─── fill_missing_metadata ────────────────────────────────────────────────────

class TestFillMissingMetadata:
    def test_fills_empty_fields_from_catalog(self):
        plugin = Plugin(Name="check_ssh")
        assert fill_missing_metadata(plugin) is True
        assert plugin.Description == "Check SSH server connection."
        assert plugin.Category == "Network Services"

    def test_never_overwrites_existing_values(self):
        plugin = Plugin(Name="check_ssh", Description="Admin wording", Category="Mine")
        assert fill_missing_metadata(plugin) is False
        assert plugin.Description == "Admin wording"
        assert plugin.Category == "Mine"

    def test_fills_only_the_empty_field(self):
        plugin = Plugin(Name="check_ssh", Description="Admin wording")
        assert fill_missing_metadata(plugin) is True
        assert plugin.Description == "Admin wording"
        assert plugin.Category == "Network Services"

    def test_unknown_plugin_uses_fallback_description_and_no_category(self):
        plugin = Plugin(Name="check_company")
        assert fill_missing_metadata(plugin, "Checks the company thing.") is True
        assert plugin.Description == "Checks the company thing."
        assert plugin.Category is None

    def test_unknown_plugin_without_fallback_changes_nothing(self):
        plugin = Plugin(Name="check_company")
        assert fill_missing_metadata(plugin) is False
        assert plugin.Description is None

    def test_catalog_wins_over_fallback(self):
        plugin = Plugin(Name="check_ssh")
        fill_missing_metadata(plugin, "something from --help")
        assert plugin.Description == "Check SSH server connection."


# ─── scanner integration ──────────────────────────────────────────────────────

def _plugin(db_session, name):
    return db_session.session.execute(
        db_session.select(Plugin).where(Plugin.Name == name)
    ).scalar_one()


class TestScannerFillsDescriptions:
    def test_new_catalogued_plugin_gets_description_without_running_help(self, db_session, tmp_path):
        _write_fake_plugin(tmp_path, "check_ssh")
        calls = []

        def fake_run(args, **kwargs):
            calls.append(args[-1])
            return _completed("check_ssh v2.4.12")

        with _ALWAYS_EXECUTABLE, patch("app.api.plugin.scanner.subprocess.run", side_effect=fake_run):
            sync_plugin_inventory(scan_plugin_directory(str(tmp_path)))

        plugin = _plugin(db_session, "check_ssh")
        assert plugin.Description == "Check SSH server connection."
        assert plugin.Category == "Network Services"
        assert calls == ["--version"]  # --help is only for plugins outside the catalog

    def test_unknown_plugin_description_comes_from_its_help(self, db_session, tmp_path):
        _write_fake_plugin(tmp_path, "check_company")
        help_output = (
            "check_company v1.0\n\nVerify the company intranet answers within a second.\n\nUsage:\n x\n"
        )
        with _ALWAYS_EXECUTABLE, patch("app.api.plugin.scanner.subprocess.run",
                                       side_effect=_run_by_flag("check_company v1.0", help_output)):
            sync_plugin_inventory(scan_plugin_directory(str(tmp_path)))

        plugin = _plugin(db_session, "check_company")
        assert plugin.Description == "Verify the company intranet answers within a second."
        assert plugin.Category is None

    def test_unknown_plugin_with_unusable_help_has_no_description(self, db_session, tmp_path):
        _write_fake_plugin(tmp_path, "check_company")
        with _ALWAYS_EXECUTABLE, patch("app.api.plugin.scanner.subprocess.run",
                                       return_value=_completed("v1.0")):
            sync_plugin_inventory(scan_plugin_directory(str(tmp_path)))

        assert _plugin(db_session, "check_company").Description is None

    def test_rescan_backfills_existing_plugin_and_reports_it_updated(self, db_session, tmp_path):
        db_session.session.add(Plugin(
            Name="check_ping", Plugin_Type=PluginType.NAGIOS, Source=PluginSource.BASELINE_ISO,
            Status=PluginStatus.READY, Executable_Path=os.path.join(tmp_path, "check_ping"),
            Current_Version="2.4.12",
        ))
        db_session.session.commit()
        _write_fake_plugin(tmp_path, "check_ping")

        with _ALWAYS_EXECUTABLE, patch("app.api.plugin.scanner.subprocess.run",
                                       return_value=_completed("check_ping v2.4.12")):
            first = sync_plugin_inventory(scan_plugin_directory(str(tmp_path)))
            second = sync_plugin_inventory(scan_plugin_directory(str(tmp_path)))

        assert first == {"created": 0, "updated": 1, "unchanged": 0}
        assert second == {"created": 0, "updated": 0, "unchanged": 1}
        assert _plugin(db_session, "check_ping").Description == "Ping host and measure response time."

    def test_rescan_keeps_an_administrators_description(self, db_session, tmp_path):
        db_session.session.add(Plugin(
            Name="check_ping", Plugin_Type=PluginType.NAGIOS, Source=PluginSource.BASELINE_ISO,
            Status=PluginStatus.READY, Executable_Path=os.path.join(tmp_path, "check_ping"),
            Current_Version="2.4.12", Description="Our wording", Category="Ours",
        ))
        db_session.session.commit()
        _write_fake_plugin(tmp_path, "check_ping")

        with _ALWAYS_EXECUTABLE, patch("app.api.plugin.scanner.subprocess.run",
                                       return_value=_completed("check_ping v2.4.12")):
            summary = sync_plugin_inventory(scan_plugin_directory(str(tmp_path)))

        assert summary["unchanged"] == 1
        plugin = _plugin(db_session, "check_ping")
        assert plugin.Description == "Our wording"
        assert plugin.Category == "Ours"


# ─── details route ────────────────────────────────────────────────────────────

class TestDetailsRoute:
    def test_details_include_description_category_and_docs_link(self, logged_in_client, db_session):
        plugin = Plugin(Name="check_ssh", Plugin_Type=PluginType.NAGIOS,
                        Source=PluginSource.BASELINE_ISO, Status=PluginStatus.READY)
        fill_missing_metadata(plugin)
        db_session.session.add(plugin)
        db_session.session.commit()

        response = logged_in_client.get(f"/api/plugin/{plugin.PluginID}")

        assert response.status_code == 200
        data = response.get_json()["data"]
        assert data["description"] == "Check SSH server connection."
        assert data["category"] == "Network Services"
        assert data["documentation_url"] == "https://www.nagios-plugins.org/doc/man/check_ssh.html"

    def test_custom_plugin_has_no_documentation_url(self, logged_in_client, db_session):
        plugin = Plugin(Name="check_company", Plugin_Type=PluginType.CUSTOM,
                        Source=PluginSource.ADMINISTRATOR_ADDED, Status=PluginStatus.READY)
        db_session.session.add(plugin)
        db_session.session.commit()

        data = logged_in_client.get(f"/api/plugin/{plugin.PluginID}").get_json()["data"]

        assert data["documentation_url"] is None
        assert data["description"] is None


def test_the_catalog_entry_is_found_for_the_script_filename():
    from app.api.plugin.plugin_descriptions import get_catalog_entry
    assert get_catalog_entry("check_ncpa.py") is get_catalog_entry("check_ncpa")
    assert get_catalog_entry("check_ncpa.py") is not None


class TestCatalogFallbackForUnscannedRows:
    def test_a_row_without_a_description_shows_the_catalog_text(self):
        from types import SimpleNamespace
        from app.api.plugin.service import catalog_fallback

        row = SimpleNamespace(Name="check_ssh", Description=None, Category=None)

        assert catalog_fallback(row, "description") == "Check SSH server connection."
        assert catalog_fallback(row, "category") == "Network Services"

    def test_a_stored_value_wins_and_an_unknown_plugin_stays_empty(self):
        from types import SimpleNamespace
        from app.api.plugin.service import catalog_fallback

        assert catalog_fallback(SimpleNamespace(Name="check_ssh", Description="Mine", Category=None), "description") == "Mine"
        assert catalog_fallback(SimpleNamespace(Name="custom_x", Description=None, Category=None), "description") is None
