from pathlib import Path
from datetime import datetime
import shutil
import json

from network_discovery.network_discovery import discover_network
from network_discovery.host_config_templates import *

from flask import current_app
from app.api.helper.database_access.user_access import get_all_users

# Project root (pin-point/)
PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Folder where generated configs are stored
HOST_CONFIG_DIR = PROJECT_ROOT / "host-config-files"

# Folder where backups of the running config are stored
BACKUP_DIR = PROJECT_ROOT / "running-host-config-backup"

# Nagios live config
NAGIOS_HOST_CFG = Path("/usr/local/nagios/etc/objects/hosts.cfg")

# Get the folder for command maps
MAP_DIR = Path(__file__).parent / "command_maps"

DOMAIN = "test.local"

# get the tcp command map
with open(MAP_DIR / "tcp_commands.json") as f:
    TCP_COMMANDS = json.load(f)

# get the udp command map
with open(MAP_DIR / "udp_commands.json") as f:
    UDP_COMMANDS = json.load(f)

def _add_space(spaces):
    string = ""
    for i in range(spaces):
        string += "\n"


# this is the function that will give a command based on the service name
# if its not in the map, you'll have to make your own default command
# ex: checkudp!63
def _get_command(service_name, port, command_map, default_command):
    command = command_map.get(service_name)

    if command is None:
        command = f"{default_command}!{port}"

    return command


def _create_host_cfg_file(discovered_hosts):
    """
    Creates a new host configuration file.

    Returns:
        pathlib.Path: Path to the newly created file.
    """

    HOST_CONFIG_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%d-%m-%Y-%H-%M")
    filename = f"host-{timestamp}.cfg"

    cfg_path = HOST_CONFIG_DIR / filename

    host_config = []

    host_config.append(
        f"""
        ##########################################################################
        #   host.cfg file for Nagios generated by Pin Point
        #   
        #   generated at {timestamp}
        ##########################################################################
        """
    )

    host_config.append(_add_space(4))

    host_config.append(
        f"""

        #
        # Define Contact Templates
        #

        """
    )

    host_config.append(create_contact_template("generic-contact"))

    host_config.append(_add_space(4))

    host_config.append(
        f"""

        #
        # Define Contacts
        #  

        """
    )

    users = get_all_users()

    for user in users:
        user_information = {
            "contact_name": str(user.Email),
            "use": "generic-contact",
            "full_name": str(user.First_name + " " + user.Last_name),
            "email": str(user.Email)
        }

        host_config.append(create_contact(user_information))
        host_config.append(_add_space(4))

    # add the users to the contact group
    host_config.append(
        f"""

        #
        # Define Contactgroups
        #  
            
        """
    )

    contact_group = {
        "contact_group": "admins",
        "alias_name": "Nagios Users",
        "member_list": ",".join(user.First_name for user in users)
    }

    host_config.append(create_contactgroup(contact_group))

    host_config.append(_add_space(4))


    host_config.append(
        f"""

        #
        # Define Hosts
        # 

        """
    )

    hostgroups = {
                "Linux":{
                    "devices":[]
                },
                "Windows":{
                    "devices":[]
                },
                "Mac OS X":{
                    "devices":[]
                },
                "Android":{
                    "devices":[]
                },
                "iOS":{
                    "devices":[]
                },
                "ChromeOS":{
                    "devices":[]
                },
                "OpenBSD":{
                    "devices":[]
                },
                "NetBSD":{
                    "devices":[]
                },
                "Mikrotik":{
                    "devices":[]
                },
                "OpenWRT":{
                    "devices":[]
                },
                "Cisco":{
                    "devices":[]
                },
                "Unknown":{
                    "devices":[]
                }

            }

    for hosts in discovered_hosts.values():
        for ip, host_data in hosts.items():
            host = {}
            host["host_name"] = host_data["data"]["hostname"] 
            host["alias"] = "alias" 
            host["address"] = ip
            host["contact_groups"] = "admins"
            host_config.append(create_host(host))
            host_config.append(_add_space(4))

            # Assigns hostgroup's list to be used in creating hostgroups
            
            os_name = host_data["data"]["os"]
            if os_name in hostgroups:
                hostgroups[os_name]["devices"].append(host_data["data"]["hostname"])
            else:
                hostgroups["Unknown"]["devices"].append(host_data["data"]["hostname"])

            host_config.append(
                f"""

                #
                # Define Services of
                # Hostname: {host_data["data"]["hostname"]}
                # IP: {ip}
                #

                """
            )

            tcp_services = host_data["services"]["tcp"]

            for port, service_data in tcp_services.items():
                service_name = service_name = f"{service_data['service_name']} ({port}/TCP)"

                command = _get_command(service_name,port,TCP_COMMANDS,"check_tcp")
                service = {
                    "host_name": host_data["data"]["hostname"],
                    "service_name": service_name,
                    "contact_groups": "admins"
                }

                host_config.append(
                    create_service(service,command)
                )
                host_config.append(_add_space(4))

            udp_services = host_data["services"]["udp"]

            for port, service_data in udp_services.items():
                service_name = service_name = f"{service_data['service_name']} ({port}/UDP)"
            
                command = _get_command(service_name,port,UDP_COMMANDS,"check_udp")
                service = {
                    "host_name": host_data["data"]["hostname"],
                    "service_name": service_name,
                    "contact_group": "admins"
                }
            
                host_config.append(
                    create_service(service,command)
                )
                host_config.append(_add_space(4))

    host_config.append(
        f"""

        #
        # Define Hostgroups 
        #  

        """
    )

    for os, group_devices in hostgroups.items():

        devices = group_devices["devices"]

        if not devices:
            continue

        host_group={
            "group_name": os,
            "alias_name": os,
            "member_list": ",".join(devices)
        } 
        host_config.append(create_hostgroup(host_group))
        host_config.append(_add_space(4))


    with open(cfg_path, "w") as f:
        # remember to f.write("string") here after you're done with discovering devices
        f.write("".join(host_config))
    return cfg_path


def _backup_running_host_cfg():
    """
    Creates a backup of Nagios' currently running hosts.cfg.

    Returns:
        pathlib.Path: Path to the backup file.
    """

    BACKUP_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%d-%m-%Y-%H-%M")
    backup_name = f"host-{timestamp}.cfg"

    backup_path = BACKUP_DIR / backup_name

    shutil.copy2(NAGIOS_HOST_CFG, backup_path)

    return backup_path

def _validate_config():
    # use the nagios -v to validate the created host file
    return 0

def _apply_new_host_cfg():
    # this is where you'll apply the new config
    # verify the config first
    # if its good then ovewrite the config
    # if its not, raise an error and say what error Nagios gave
    return 0

def _create_hostname(discovered_hosts):
    for network, hosts in discovered_hosts.items():
        for ip, host_data in hosts.items():
            if host_data["data"]["hostname"] == "Unknown":
                discovered_hosts[network][ip]["data"]["hostname"] = f"{ip}.{DOMAIN}"

    return discovered_hosts
         

if __name__ == "__main__":

    # find a way to run this with elevated permissions "SAFELY"
    discovered_hosts = discover_network()
    discovered_hosts = _create_hostname(discovered_hosts)

    #backup = backup_running_host_cfg()
    new_cfg = _create_host_cfg_file(discovered_hosts)
    #validate_config()
    #apply_new_host_cfg()

    print(f"Created: {new_cfg}")
    #print(f"Backed up: {backup}")