"""Commendted out Closed_At Column to both TCP and UDP services table

Revision ID: 1197cbc2c688
Revises: 7fa1b4f3d944
Create Date: 2026-08-12 18:48:31.940451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1197cbc2c688'
down_revision = '7fa1b4f3d944'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OPEN_TCP_Services', schema=None) as batch_op:
        batch_op.drop_column('Closed_At')

    with op.batch_alter_table('OPEN_UDP_Services', schema=None) as batch_op:
        batch_op.drop_column('Closed_At')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OPEN_UDP_Services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Closed_At', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('OPEN_TCP_Services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Closed_At', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

