"""added Include_Device_In_Scanning column in Network Discovery

Revision ID: 24f4c1d7af8f
Revises: e768816b6af1
Create Date: 2026-08-09 15:08:55.380905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f4c1d7af8f'
down_revision = 'e768816b6af1'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Include_Device_In_Scanning', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.drop_column('Include_Device_In_Scanning')

    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

