"""add plugin manager tables

Revision ID: 25c5ca54e532
Revises: c99d23ea7ae6
Create Date: 2026-09-24 08:16:29.507950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c5ca54e532'
down_revision = 'c99d23ea7ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PLUGIN',
    sa.Column('PluginID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Display_Name', sa.String(length=150), nullable=True),
    sa.Column('Description', sa.String(length=500), nullable=True),
    sa.Column('Author', sa.String(length=100), nullable=True),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.Column('Plugin_Type', sa.Enum('NAGIOS', 'CUSTOM', name='plugintype'), nullable=False),
    sa.Column('Source', sa.Enum('BASELINE_ISO', 'ADMINISTRATOR_ADDED', name='pluginsource'), nullable=False),
    sa.Column('Current_Version', sa.String(length=20), nullable=True),
    sa.Column('Status', sa.Enum('AVAILABLE', 'READY', 'INSTALLED', 'ENABLED', 'ACTIVE', 'DISABLED', 'UPDATE_AVAILABLE', 'VALIDATION_FAILED', 'DEPENDENCY_FAILED', 'INSTALLATION_FAILED', 'CONFIGURATION_FAILED', 'ROLLBACK', name='pluginstatus'), nullable=False),
    sa.Column('Executable_Path', sa.String(length=255), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('PluginID')
    )
    with op.batch_alter_table('PLUGIN', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_Name'), ['Name'], unique=True)

    op.create_table('PLUGIN_COMMAND',
    sa.Column('PluginCommandID', sa.Integer(), nullable=False),
    sa.Column('Command_Name', sa.String(length=100), nullable=False),
    sa.Column('Command_Definition', sa.String(length=500), nullable=False),
    sa.Column('Is_Default', sa.Boolean(), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.Column('PluginID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PluginID'], ['PLUGIN.PluginID'], ),
    sa.PrimaryKeyConstraint('PluginCommandID')
    )
    with op.batch_alter_table('PLUGIN_COMMAND', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_COMMAND_PluginID'), ['PluginID'], unique=False)

    op.create_table('PLUGIN_DEPENDENCY',
    sa.Column('PluginDependencyID', sa.Integer(), nullable=False),
    sa.Column('Dependency_Name', sa.String(length=100), nullable=False),
    sa.Column('Dependency_Type', sa.Enum('BINARY', 'LIBRARY', 'PACKAGE', 'RUNTIME', 'CAPABILITY', name='dependencytype'), nullable=False),
    sa.Column('Required_Version', sa.String(length=20), nullable=True),
    sa.Column('Status', sa.Enum('OK', 'MISSING', 'INCOMPATIBLE', name='dependencystatus'), nullable=False),
    sa.Column('PluginID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PluginID'], ['PLUGIN.PluginID'], ),
    sa.PrimaryKeyConstraint('PluginDependencyID')
    )
    with op.batch_alter_table('PLUGIN_DEPENDENCY', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_DEPENDENCY_PluginID'), ['PluginID'], unique=False)

    op.create_table('PLUGIN_VERSION',
    sa.Column('PluginVersionID', sa.Integer(), nullable=False),
    sa.Column('Version', sa.String(length=20), nullable=False),
    sa.Column('Executable_Path', sa.String(length=255), nullable=True),
    sa.Column('Checksum', sa.String(length=64), nullable=True),
    sa.Column('Source', sa.String(length=100), nullable=True),
    sa.Column('Is_Current', sa.Boolean(), nullable=False),
    sa.Column('Installed_At', sa.DateTime(), nullable=False),
    sa.Column('Removed_At', sa.DateTime(), nullable=True),
    sa.Column('PluginID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PluginID'], ['PLUGIN.PluginID'], ),
    sa.PrimaryKeyConstraint('PluginVersionID'),
    sa.UniqueConstraint('PluginID', 'Version', name='uq_plugin_version')
    )
    with op.batch_alter_table('PLUGIN_VERSION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_VERSION_PluginID'), ['PluginID'], unique=False)

    op.create_table('PLUGIN_COMMAND_OVERRIDE',
    sa.Column('PluginCommandOverrideID', sa.Integer(), nullable=False),
    sa.Column('Original_Command', sa.String(length=500), nullable=False),
    sa.Column('Override_Command', sa.String(length=500), nullable=False),
    sa.Column('Is_Active', sa.Boolean(), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.Column('PluginCommandID', sa.Integer(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.ForeignKeyConstraint(['PluginCommandID'], ['PLUGIN_COMMAND.PluginCommandID'], ),
    sa.PrimaryKeyConstraint('PluginCommandOverrideID')
    )
    with op.batch_alter_table('PLUGIN_COMMAND_OVERRIDE', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_COMMAND_OVERRIDE_LogID'), ['LogID'], unique=False)
        batch_op.create_index(batch_op.f('ix_PLUGIN_COMMAND_OVERRIDE_PluginCommandID'), ['PluginCommandID'], unique=False)

    op.create_table('PLUGIN_HISTORY',
    sa.Column('PluginHistoryID', sa.Integer(), nullable=False),
    sa.Column('Action', sa.Enum('INSTALL', 'UPDATE', 'ENABLE', 'DISABLE', 'CONFIGURE', 'COMMAND_OVERRIDE', 'VALIDATE', 'ROLLBACK', 'REMOVE', name='pluginhistoryaction'), nullable=False),
    sa.Column('Old_Value', sa.String(length=255), nullable=True),
    sa.Column('New_Value', sa.String(length=255), nullable=True),
    sa.Column('Result', sa.Enum('SUCCESS', 'FAILED', name='pluginactionresult'), nullable=False),
    sa.Column('Message', sa.String(length=500), nullable=True),
    sa.Column('PluginID', sa.Integer(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.ForeignKeyConstraint(['PluginID'], ['PLUGIN.PluginID'], ),
    sa.PrimaryKeyConstraint('PluginHistoryID')
    )
    with op.batch_alter_table('PLUGIN_HISTORY', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_HISTORY_LogID'), ['LogID'], unique=False)
        batch_op.create_index(batch_op.f('ix_PLUGIN_HISTORY_PluginID'), ['PluginID'], unique=False)

    op.create_table('PLUGIN_SCAN_STATUS',
    sa.Column('PluginScanStatusID', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='pluginscanstatusvalue'), nullable=False),
    sa.Column('Progress', sa.Integer(), nullable=False),
    sa.Column('Message', sa.String(length=100), nullable=False),
    sa.Column('Start_At', sa.DateTime(), nullable=False),
    sa.Column('Completed_At', sa.DateTime(), nullable=True),
    sa.Column('Error', sa.String(), nullable=True),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('PluginScanStatusID')
    )
    with op.batch_alter_table('PLUGIN_SCAN_STATUS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_SCAN_STATUS_LogID'), ['LogID'], unique=False)

    op.create_table('PLUGIN_CONFIGURATION',
    sa.Column('PluginConfigurationID', sa.Integer(), nullable=False),
    sa.Column('Service_Description', sa.String(length=200), nullable=True),
    sa.Column('Status', sa.Enum('PENDING', 'APPLIED', 'FAILED', name='pluginconfigurationstatus'), nullable=False),
    sa.Column('Configuration_Data', sa.JSON(), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.Column('PluginID', sa.Integer(), nullable=False),
    sa.Column('NetDiscoveryID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['NetDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.ForeignKeyConstraint(['PluginID'], ['PLUGIN.PluginID'], ),
    sa.PrimaryKeyConstraint('PluginConfigurationID')
    )
    with op.batch_alter_table('PLUGIN_CONFIGURATION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_CONFIGURATION_NetDiscoveryID'), ['NetDiscoveryID'], unique=False)
        batch_op.create_index(batch_op.f('ix_PLUGIN_CONFIGURATION_PluginID'), ['PluginID'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PLUGIN_CONFIGURATION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_CONFIGURATION_PluginID'))
        batch_op.drop_index(batch_op.f('ix_PLUGIN_CONFIGURATION_NetDiscoveryID'))

    op.drop_table('PLUGIN_CONFIGURATION')
    with op.batch_alter_table('PLUGIN_SCAN_STATUS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_SCAN_STATUS_LogID'))

    op.drop_table('PLUGIN_SCAN_STATUS')
    with op.batch_alter_table('PLUGIN_HISTORY', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_HISTORY_PluginID'))
        batch_op.drop_index(batch_op.f('ix_PLUGIN_HISTORY_LogID'))

    op.drop_table('PLUGIN_HISTORY')
    with op.batch_alter_table('PLUGIN_COMMAND_OVERRIDE', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_COMMAND_OVERRIDE_PluginCommandID'))
        batch_op.drop_index(batch_op.f('ix_PLUGIN_COMMAND_OVERRIDE_LogID'))

    op.drop_table('PLUGIN_COMMAND_OVERRIDE')
    with op.batch_alter_table('PLUGIN_VERSION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_VERSION_PluginID'))

    op.drop_table('PLUGIN_VERSION')
    with op.batch_alter_table('PLUGIN_DEPENDENCY', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_DEPENDENCY_PluginID'))

    op.drop_table('PLUGIN_DEPENDENCY')
    with op.batch_alter_table('PLUGIN_COMMAND', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_COMMAND_PluginID'))

    op.drop_table('PLUGIN_COMMAND')
    with op.batch_alter_table('PLUGIN', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_Name'))

    op.drop_table('PLUGIN')
    # ### end Alembic commands ###
