"""empty message

Revision ID: 2c0f9a5814f7
Revises: bdde02188d1d
Create Date: 2026-06-11 17:00:29.203234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0f9a5814f7'
down_revision = 'bdde02188d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SSH_CREDENTIALS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Key_Installed', sa.Boolean(), nullable=False))
        batch_op.drop_column('SSH_Password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SSH_CREDENTIALS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SSH_Password', sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('Key_Installed')

    # ### end Alembic commands ###
