"""add plugin scan status

Revision ID: 33dd6ecd273f
Revises: 24a7641ffecc
Create Date: 2026-09-01 11:44:48.276451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33dd6ecd273f'
down_revision = '24a7641ffecc'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PLUGIN_SCAN_STATUS',
    sa.Column('PluginScanStatusID', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='pluginscanstatusvalue'), nullable=False),
    sa.Column('Progress', sa.Integer(), nullable=False),
    sa.Column('Message', sa.String(length=100), nullable=False),
    sa.Column('Start_At', sa.DateTime(), nullable=False),
    sa.Column('Completed_At', sa.DateTime(), nullable=True),
    sa.Column('Error', sa.String(), nullable=True),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('PluginScanStatusID')
    )
    with op.batch_alter_table('PLUGIN_SCAN_STATUS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_SCAN_STATUS_LogID'), ['LogID'], unique=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PLUGIN_SCAN_STATUS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_SCAN_STATUS_LogID'))

    op.drop_table('PLUGIN_SCAN_STATUS')
    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

