"""empty message

Revision ID: 368239534543
Revises: d6150bbf8780
Create Date: 2026-08-09 11:38:00.753850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368239534543'
down_revision = 'd6150bbf8780'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OPEN_TCP_PORTS',
    sa.Column('OpenPortID', sa.Integer(), nullable=False),
    sa.Column('Port_Number', sa.Integer(), nullable=False),
    sa.Column('Serivce_Name', sa.String(length=255), nullable=False),
    sa.Column('NetDiscoveryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NetDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('OpenPortID')
    )
    with op.batch_alter_table('OPEN_TCP_PORTS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_OPEN_TCP_PORTS_NetDiscoveryID'), ['NetDiscoveryID'], unique=False)

    op.create_table('OPEN_UDP_PORTS',
    sa.Column('OpenPortID', sa.Integer(), nullable=False),
    sa.Column('Port_Number', sa.Integer(), nullable=False),
    sa.Column('Service_Name', sa.String(length=255), nullable=False),
    sa.Column('NetDiscoveryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NetDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('OpenPortID')
    )
    with op.batch_alter_table('OPEN_UDP_PORTS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_OPEN_UDP_PORTS_NetDiscoveryID'), ['NetDiscoveryID'], unique=False)

    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Network', sa.String(length=16), nullable=False))
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_Subnet_Mask'))
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_Network'), ['Network'], unique=False)
        batch_op.drop_column('Subnet_Mask')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Subnet_Mask', sa.VARCHAR(length=16), nullable=False))
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_Network'))
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_Subnet_Mask'), ['Subnet_Mask'], unique=False)
        batch_op.drop_column('Network')

    with op.batch_alter_table('OPEN_UDP_PORTS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_OPEN_UDP_PORTS_NetDiscoveryID'))

    op.drop_table('OPEN_UDP_PORTS')
    with op.batch_alter_table('OPEN_TCP_PORTS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_OPEN_TCP_PORTS_NetDiscoveryID'))

    op.drop_table('OPEN_TCP_PORTS')
    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

