"""fixed status of Role to Is_Active:

Revision ID: 4641fc286f93
Revises: 6daa329ce6f1
Create Date: 2026-06-17 12:16:24.349898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4641fc286f93'
down_revision = '6daa329ce6f1'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ROLE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Is_Active', sa.Boolean(), nullable=False))
        batch_op.drop_column('Role_Status')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ROLE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Role_Status', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('Is_Active')

    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

