"""empty message

Revision ID: 4c8bddea3761
Revises: 2c0f9a5814f7
Create Date: 2026-06-13 18:46:12.957382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8bddea3761'
down_revision = '2c0f9a5814f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PERMISSION',
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.Column('Permission', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('PermissionID')
    )
    op.create_table('ROLE_PERMISSION',
    sa.Column('RolePermissionID', sa.Integer(), nullable=False),
    sa.Column('Has_Permission', sa.Boolean(), nullable=False),
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PermissionID'], ['PERMISSION.PermissionID'], ),
    sa.ForeignKeyConstraint(['RoleID'], ['ROLE.RoleID'], ),
    sa.PrimaryKeyConstraint('RolePermissionID')
    )
    with op.batch_alter_table('ROLE_PERMISSION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ROLE_PERMISSION_PermissionID'), ['PermissionID'], unique=False)
        batch_op.create_index(batch_op.f('ix_ROLE_PERMISSION_RoleID'), ['RoleID'], unique=False)

    op.create_table('USER_PERMISSION',
    sa.Column('UserPermissionID', sa.Integer(), nullable=False),
    sa.Column('Has_Permission', sa.Boolean(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PermissionID'], ['PERMISSION.PermissionID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['USER.UserID'], ),
    sa.PrimaryKeyConstraint('UserPermissionID')
    )
    with op.batch_alter_table('USER_PERMISSION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_USER_PERMISSION_PermissionID'), ['PermissionID'], unique=False)
        batch_op.create_index(batch_op.f('ix_USER_PERMISSION_UserID'), ['UserID'], unique=False)

    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MAC_Address', sa.String(length=17), nullable=True))
        batch_op.alter_column('Hostname',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_IP_Address'), ['IP_Address'], unique=False)
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_MAC_Address'), ['MAC_Address'], unique=False)
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_Subnet_Mask'), ['Subnet_Mask'], unique=False)

    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.alter_column('Updated_At',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.alter_column('Updated_At',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_Subnet_Mask'))
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_MAC_Address'))
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_IP_Address'))
        batch_op.alter_column('Hostname',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
        batch_op.drop_column('MAC_Address')

    with op.batch_alter_table('USER_PERMISSION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_USER_PERMISSION_UserID'))
        batch_op.drop_index(batch_op.f('ix_USER_PERMISSION_PermissionID'))

    op.drop_table('USER_PERMISSION')
    with op.batch_alter_table('ROLE_PERMISSION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ROLE_PERMISSION_RoleID'))
        batch_op.drop_index(batch_op.f('ix_ROLE_PERMISSION_PermissionID'))

    op.drop_table('ROLE_PERMISSION')
    op.drop_table('PERMISSION')
    # ### end Alembic commands ###
