"""add capability dependency type

Revision ID: 4dd5d938ee33
Revises: cd33c9245d9d
Create Date: 2026-09-05 01:28:28.229437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd5d938ee33'
down_revision = 'cd33c9245d9d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PLUGIN_DEPENDENCY', schema=None) as batch_op:
        batch_op.alter_column('Dependency_Type',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('BINARY', 'LIBRARY', 'PACKAGE', 'RUNTIME', 'CAPABILITY', name='dependencytype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PLUGIN_DEPENDENCY', schema=None) as batch_op:
        batch_op.alter_column('Dependency_Type',
               existing_type=sa.Enum('BINARY', 'LIBRARY', 'PACKAGE', 'RUNTIME', 'CAPABILITY', name='dependencytype'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

