"""fixed the typo of Service_Name in Open_TCP_Services

Revision ID: 67b375a40115
Revises: f1e91f0e3f83
Create Date: 2026-08-21 18:42:00.977034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b375a40115'
down_revision = 'f1e91f0e3f83'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OPEN_TCP_Services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Service_Name', sa.String(length=255), nullable=False))
        batch_op.drop_column('Serivce_Name')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OPEN_TCP_Services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Serivce_Name', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('Service_Name')

    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

