"""initial

Revision ID: 6937fa6c1100
Revises: 
Create Date: 2026-08-26 10:32:05.662034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6937fa6c1100'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PERMISSION',
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('PermissionID')
    )
    with op.batch_alter_table('PERMISSION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PERMISSION_Name'), ['Name'], unique=True)

    op.create_table('ROLE',
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Is_Active', sa.Boolean(), nullable=False),
    sa.Column('Description', sa.String(length=150), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('RoleID')
    )
    with op.batch_alter_table('ROLE', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ROLE_Name'), ['Name'], unique=True)

    op.create_table('ROLE_PERMISSION',
    sa.Column('RolePermissionID', sa.Integer(), nullable=False),
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PermissionID'], ['PERMISSION.PermissionID'], ),
    sa.ForeignKeyConstraint(['RoleID'], ['ROLE.RoleID'], ),
    sa.PrimaryKeyConstraint('RolePermissionID'),
    sa.UniqueConstraint('RoleID', 'PermissionID', name='uq_role_permission')
    )
    with op.batch_alter_table('ROLE_PERMISSION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ROLE_PERMISSION_PermissionID'), ['PermissionID'], unique=False)
        batch_op.create_index(batch_op.f('ix_ROLE_PERMISSION_RoleID'), ['RoleID'], unique=False)

    op.create_table('USER',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('First_Name', sa.String(length=120), nullable=False),
    sa.Column('Last_Name', sa.String(length=120), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('Hashed_Password', sa.String(length=256), nullable=False),
    sa.Column('Status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['RoleID'], ['ROLE.RoleID'], ),
    sa.PrimaryKeyConstraint('UserID')
    )
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_USER_Email'), ['Email'], unique=True)
        batch_op.create_index(batch_op.f('ix_USER_RoleID'), ['RoleID'], unique=False)

    op.create_table('ACTIVITY_LOG',
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.Column('Action_Type', sa.String(length=255), nullable=False),
    sa.Column('Performed_At', sa.DateTime(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['USER.UserID'], ),
    sa.PrimaryKeyConstraint('LogID')
    )
    with op.batch_alter_table('ACTIVITY_LOG', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ACTIVITY_LOG_UserID'), ['UserID'], unique=False)

    op.create_table('SYSTEM_SETTINGS',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('System_Language', sa.String(length=20), nullable=False),
    sa.Column('Theme', sa.String(length=10), nullable=False),
    sa.Column('Time_Zone', sa.String(length=20), nullable=False),
    sa.Column('Date_Time_Format', sa.String(length=20), nullable=False),
    sa.Column('System_Font', sa.String(length=30), nullable=False),
    sa.Column('System_Font_Size', sa.String(length=10), nullable=False),
    sa.Column('Dashboard_Refresh_Rate', sa.Integer(), nullable=False),
    sa.Column('Scan_Frequency', sa.Integer(), nullable=False),
    sa.Column('Dashboard_Layout', sa.String(length=15), nullable=False),
    sa.Column('Notifications', sa.Boolean(), nullable=False),
    sa.Column('Export_Formats', sa.String(length=50), nullable=False),
    sa.Column('Session_Timeout', sa.Integer(), nullable=False),
    sa.Column('Strong_Password_Policy', sa.Boolean(), nullable=False),
    sa.Column('Failed_Login_Monitoring', sa.Boolean(), nullable=False),
    sa.Column('Audit_Logging', sa.Boolean(), nullable=False),
    sa.Column('Security_Check_Frequency', sa.String(length=10), nullable=False),
    sa.Column('System_Update_Frequency', sa.String(length=10), nullable=False),
    sa.Column('Maintenance_Mode', sa.Boolean(), nullable=False),
    sa.Column('Automatic_Backups', sa.Boolean(), nullable=False),
    sa.Column('Log_Retention_Days', sa.Integer(), nullable=False),
    sa.Column('Diagnostic_History_Retention_Days', sa.Integer(), nullable=False),
    sa.Column('Version', sa.Integer(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_By', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Updated_By'], ['USER.UserID'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('SYSTEM_SETTINGS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SYSTEM_SETTINGS_Updated_By'), ['Updated_By'], unique=False)

    op.create_table('CONFIGURATION_CHANGES',
    sa.Column('ConfChangesID', sa.Integer(), nullable=False),
    sa.Column('Conf_Type', sa.String(length=25), nullable=False),
    sa.Column('Parameter_Name', sa.String(length=50), nullable=False),
    sa.Column('Old_Value', sa.String(length=100), nullable=False),
    sa.Column('New_Value', sa.String(length=100), nullable=False),
    sa.Column('Changed_At', sa.DateTime(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('ConfChangesID')
    )
    with op.batch_alter_table('CONFIGURATION_CHANGES', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_CONFIGURATION_CHANGES_LogID'), ['LogID'], unique=False)

    op.create_table('EXPORT_LOG',
    sa.Column('ExportID', sa.Integer(), nullable=False),
    sa.Column('Report_Type', sa.String(length=25), nullable=False),
    sa.Column('Export_Format', sa.Enum('CSV', 'PDF', name='exportformat'), nullable=False),
    sa.Column('Start_Date', sa.DateTime(), nullable=False),
    sa.Column('End_Date', sa.DateTime(), nullable=False),
    sa.Column('Exported_At', sa.DateTime(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('ExportID')
    )
    with op.batch_alter_table('EXPORT_LOG', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_EXPORT_LOG_LogID'), ['LogID'], unique=False)

    op.create_table('NCPA_DEPLOYMENT_STATUS',
    sa.Column('NCPADeployStatusID', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL_FAILURE', 'FAILED', 'INTERRUPTED', name='deploymentstatus'), nullable=False),
    sa.Column('Progress', sa.Integer(), nullable=False),
    sa.Column('Message', sa.String(length=100), nullable=False),
    sa.Column('Start_At', sa.DateTime(), nullable=False),
    sa.Column('Completed_At', sa.DateTime(), nullable=True),
    sa.Column('Error', sa.String(), nullable=True),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('NCPADeployStatusID')
    )
    op.create_table('NETWORK_DISCOVERY_STATUS',
    sa.Column('DiscoveryStatusID', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', 'INTERRUPTED', name='discoverystatus'), nullable=False),
    sa.Column('Progress', sa.Integer(), nullable=False),
    sa.Column('Message', sa.String(length=100), nullable=False),
    sa.Column('Start_At', sa.DateTime(), nullable=False),
    sa.Column('Completed_At', sa.DateTime(), nullable=True),
    sa.Column('Error', sa.String(), nullable=True),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('DiscoveryStatusID')
    )
    with op.batch_alter_table('NETWORK_DISCOVERY_STATUS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_STATUS_LogID'), ['LogID'], unique=False)

    op.create_table('NETWORK_DISCOVERY',
    sa.Column('NetDiscoveryID', sa.Integer(), nullable=False),
    sa.Column('Hostname', sa.String(length=100), nullable=True),
    sa.Column('IP_Address', sa.String(length=16), nullable=False),
    sa.Column('Network', sa.String(length=16), nullable=False),
    sa.Column('MAC_Address', sa.String(length=17), nullable=True),
    sa.Column('OS_Type', sa.String(length=25), nullable=True),
    sa.Column('Device_Type', sa.String(length=25), nullable=True),
    sa.Column('NCPA_Eligible', sa.Boolean(), nullable=False),
    sa.Column('Scanned_At', sa.DateTime(), nullable=False),
    sa.Column('Include_Device_In_Scanning', sa.Boolean(), nullable=False),
    sa.Column('DiscoveryStatusID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DiscoveryStatusID'], ['NETWORK_DISCOVERY_STATUS.DiscoveryStatusID'], ),
    sa.PrimaryKeyConstraint('NetDiscoveryID')
    )
    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_DiscoveryStatusID'), ['DiscoveryStatusID'], unique=False)
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_IP_Address'), ['IP_Address'], unique=False)
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_MAC_Address'), ['MAC_Address'], unique=False)
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_Network'), ['Network'], unique=False)

    op.create_table('NCPA_DEPLOYMENT',
    sa.Column('NCPADeployID', sa.Integer(), nullable=False),
    sa.Column('Deployement_Method', sa.Enum('AUTOMATIC', 'MANUAL', name='deploymentmethod'), nullable=True),
    sa.Column('Token', sa.String(length=32), nullable=True),
    sa.Column('Agent_Status', sa.Enum('PENDING_NCPA', 'DEPLOYED', 'FAILED', 'EXCLUDED', 'INCOMPATIBLE', name='agentstatus'), nullable=True),
    sa.Column('Error', sa.String(), nullable=True),
    sa.Column('NCPADeploymentStatusID', sa.Integer(), nullable=True),
    sa.Column('NetworkDiscoveryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NCPADeploymentStatusID'], ['NCPA_DEPLOYMENT_STATUS.NCPADeployStatusID'], ),
    sa.ForeignKeyConstraint(['NetworkDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('NCPADeployID')
    )
    with op.batch_alter_table('NCPA_DEPLOYMENT', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NCPA_DEPLOYMENT_NetworkDiscoveryID'), ['NetworkDiscoveryID'], unique=False)

    op.create_table('OPEN_TCP_Services',
    sa.Column('OpenPortID', sa.Integer(), nullable=False),
    sa.Column('Port_Number', sa.Integer(), nullable=False),
    sa.Column('Service_Name', sa.String(length=255), nullable=False),
    sa.Column('NetDiscoveryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NetDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('OpenPortID')
    )
    with op.batch_alter_table('OPEN_TCP_Services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_OPEN_TCP_Services_NetDiscoveryID'), ['NetDiscoveryID'], unique=False)

    op.create_table('OPEN_UDP_Services',
    sa.Column('OpenPortID', sa.Integer(), nullable=False),
    sa.Column('Port_Number', sa.Integer(), nullable=False),
    sa.Column('Service_Name', sa.String(length=255), nullable=False),
    sa.Column('NetDiscoveryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NetDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('OpenPortID')
    )
    with op.batch_alter_table('OPEN_UDP_Services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_OPEN_UDP_Services_NetDiscoveryID'), ['NetDiscoveryID'], unique=False)

    op.create_table('SSH_CREDENTIALS',
    sa.Column('SSHID', sa.Integer(), nullable=False),
    sa.Column('SSH_Port', sa.Integer(), nullable=False),
    sa.Column('Key_Installed', sa.Boolean(), nullable=False),
    sa.Column('Key_Fingerprint', sa.String(), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=True),
    sa.Column('NetworkDiscoveryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NetworkDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('SSHID')
    )
    with op.batch_alter_table('SSH_CREDENTIALS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SSH_CREDENTIALS_NetworkDiscoveryID'), ['NetworkDiscoveryID'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SSH_CREDENTIALS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SSH_CREDENTIALS_NetworkDiscoveryID'))

    op.drop_table('SSH_CREDENTIALS')
    with op.batch_alter_table('OPEN_UDP_Services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_OPEN_UDP_Services_NetDiscoveryID'))

    op.drop_table('OPEN_UDP_Services')
    with op.batch_alter_table('OPEN_TCP_Services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_OPEN_TCP_Services_NetDiscoveryID'))

    op.drop_table('OPEN_TCP_Services')
    with op.batch_alter_table('NCPA_DEPLOYMENT', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NCPA_DEPLOYMENT_NetworkDiscoveryID'))

    op.drop_table('NCPA_DEPLOYMENT')
    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_Network'))
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_MAC_Address'))
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_IP_Address'))
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_DiscoveryStatusID'))

    op.drop_table('NETWORK_DISCOVERY')
    with op.batch_alter_table('NETWORK_DISCOVERY_STATUS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_STATUS_LogID'))

    op.drop_table('NETWORK_DISCOVERY_STATUS')
    op.drop_table('NCPA_DEPLOYMENT_STATUS')
    with op.batch_alter_table('EXPORT_LOG', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_EXPORT_LOG_LogID'))

    op.drop_table('EXPORT_LOG')
    with op.batch_alter_table('CONFIGURATION_CHANGES', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONFIGURATION_CHANGES_LogID'))

    op.drop_table('CONFIGURATION_CHANGES')
    with op.batch_alter_table('SYSTEM_SETTINGS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SYSTEM_SETTINGS_Updated_By'))

    op.drop_table('SYSTEM_SETTINGS')
    with op.batch_alter_table('ACTIVITY_LOG', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ACTIVITY_LOG_UserID'))

    op.drop_table('ACTIVITY_LOG')
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_USER_RoleID'))
        batch_op.drop_index(batch_op.f('ix_USER_Email'))

    op.drop_table('USER')
    with op.batch_alter_table('ROLE_PERMISSION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ROLE_PERMISSION_RoleID'))
        batch_op.drop_index(batch_op.f('ix_ROLE_PERMISSION_PermissionID'))

    op.drop_table('ROLE_PERMISSION')
    with op.batch_alter_table('ROLE', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ROLE_Name'))

    op.drop_table('ROLE')
    with op.batch_alter_table('PERMISSION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PERMISSION_Name'))

    op.drop_table('PERMISSION')
    # ### end Alembic commands ###
