"""added Role status

Revision ID: 6daa329ce6f1
Revises: d39f95f919be
Create Date: 2026-06-17 11:51:27.734442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6daa329ce6f1'
down_revision = 'd39f95f919be'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ROLE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Role_Status', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ROLE', schema=None) as batch_op:
        batch_op.drop_column('Role_Status')

    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

