"""add discovery settings

Revision ID: 7d2e4b9a1c05
Revises: c3610bb0fc54
Create Date: 2026-09-30 17:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2e4b9a1c05'
down_revision = 'c3610bb0fc54'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DISCOVERY_SETTINGS',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Networks', sa.JSON(), nullable=True),
    sa.Column('TCP_Ports', sa.JSON(), nullable=True),
    sa.Column('UDP_Ports', sa.JSON(), nullable=True),
    sa.Column('TCP_Service_Overrides', sa.JSON(), nullable=True),
    sa.Column('UDP_Service_Overrides', sa.JSON(), nullable=True),
    sa.Column('Version', sa.Integer(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_By', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Updated_By'], ['USER.UserID'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('DISCOVERY_SETTINGS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_DISCOVERY_SETTINGS_Updated_By'), ['Updated_By'], unique=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DISCOVERY_SETTINGS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DISCOVERY_SETTINGS_Updated_By'))

    op.drop_table('DISCOVERY_SETTINGS')
    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
