"""Added Closed_At Column to both TCP and UDP services table

Revision ID: 7fa1b4f3d944
Revises: ed7028ad2a64
Create Date: 2026-08-12 18:46:54.335241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa1b4f3d944'
down_revision = 'ed7028ad2a64'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NETWORK_DISCOVERY_STATUS', schema=None) as batch_op:
        batch_op.alter_column('Status',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('RUNNING', 'SUCCESS', 'FAILED', 'INTERUPPTED', name='discoverystatus'),
               existing_nullable=False)

    with op.batch_alter_table('OPEN_TCP_Services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Closed_At', sa.DateTime(), nullable=True))

    with op.batch_alter_table('OPEN_UDP_Services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Closed_At', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OPEN_UDP_Services', schema=None) as batch_op:
        batch_op.drop_column('Closed_At')

    with op.batch_alter_table('OPEN_TCP_Services', schema=None) as batch_op:
        batch_op.drop_column('Closed_At')

    with op.batch_alter_table('NETWORK_DISCOVERY_STATUS', schema=None) as batch_op:
        batch_op.alter_column('Status',
               existing_type=sa.Enum('RUNNING', 'SUCCESS', 'FAILED', 'INTERUPPTED', name='discoverystatus'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=False)

    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

