"""split user preferences from system settings

Revision ID: 84b373a12347
Revises: 6937fa6c1100
Create Date: 2026-08-26 12:43:06.655256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b373a12347'
down_revision = '6937fa6c1100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER_PREFERENCES',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('System_Language', sa.String(length=20), nullable=False),
    sa.Column('Theme', sa.String(length=10), nullable=False),
    sa.Column('Time_Zone', sa.String(length=20), nullable=False),
    sa.Column('Date_Time_Format', sa.String(length=20), nullable=False),
    sa.Column('System_Font', sa.String(length=30), nullable=False),
    sa.Column('System_Font_Size', sa.String(length=10), nullable=False),
    sa.Column('Dashboard_Layout', sa.String(length=15), nullable=False),
    sa.Column('Dashboard_Refresh_Rate', sa.Integer(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['USER.UserID'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('USER_PREFERENCES', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_USER_PREFERENCES_UserID'), ['UserID'], unique=True)

    with op.batch_alter_table('SYSTEM_SETTINGS', schema=None) as batch_op:
        batch_op.drop_column('Time_Zone')
        batch_op.drop_column('Theme')
        batch_op.drop_column('Date_Time_Format')
        batch_op.drop_column('Dashboard_Refresh_Rate')
        batch_op.drop_column('System_Font')
        batch_op.drop_column('Dashboard_Layout')
        batch_op.drop_column('System_Language')
        batch_op.drop_column('System_Font_Size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SYSTEM_SETTINGS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('System_Font_Size', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('System_Language', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('Dashboard_Layout', sa.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('System_Font', sa.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('Dashboard_Refresh_Rate', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('Date_Time_Format', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('Theme', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('Time_Zone', sa.VARCHAR(length=20), nullable=False))

    with op.batch_alter_table('USER_PREFERENCES', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_USER_PREFERENCES_UserID'))

    op.drop_table('USER_PREFERENCES')
    # ### end Alembic commands ###
