"""fixed some namaing inconsistencies

Revision ID: b9c2e137e702
Revises: d4bf2a41e04d
Create Date: 2026-06-18 09:07:44.267455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c2e137e702'
down_revision = 'd4bf2a41e04d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ROLE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.String(length=50), nullable=False))
        batch_op.drop_column('Role_Name')

    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.add_column(sa.Column('First_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('Last_name', sa.String(length=120), nullable=False))
        batch_op.drop_column('Lastname')
        batch_op.drop_column('Firstname')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Firstname', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('Lastname', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('Last_name')
        batch_op.drop_column('First_name')

    with op.batch_alter_table('ROLE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Role_Name', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('Name')

    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

