"""made initial db

Revision ID: bdde02188d1d
Revises: 
Create Date: 2026-06-11 16:26:50.297648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdde02188d1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ROLE',
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('Role_Name', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=150), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('RoleID')
    )
    op.create_table('USER',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Firstname', sa.String(length=120), nullable=False),
    sa.Column('Lastname', sa.String(length=120), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('Hashed_Password', sa.String(length=120), nullable=False),
    sa.Column('Status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=True),
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['RoleID'], ['ROLE.RoleID'], ),
    sa.PrimaryKeyConstraint('UserID')
    )
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_USER_Email'), ['Email'], unique=False)
        batch_op.create_index(batch_op.f('ix_USER_RoleID'), ['RoleID'], unique=False)

    op.create_table('ACTIVITY_LOG',
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.Column('Action_Type', sa.String(length=255), nullable=False),
    sa.Column('Performed_At', sa.DateTime(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['USER.UserID'], ),
    sa.PrimaryKeyConstraint('LogID')
    )
    with op.batch_alter_table('ACTIVITY_LOG', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ACTIVITY_LOG_UserID'), ['UserID'], unique=False)

    op.create_table('CONFIGURATION_CHANGES',
    sa.Column('ConfChangesID', sa.Integer(), nullable=False),
    sa.Column('Conf_Type', sa.String(length=25), nullable=False),
    sa.Column('Parameter_Name', sa.String(length=50), nullable=False),
    sa.Column('Old_Value', sa.String(length=100), nullable=False),
    sa.Column('New_Value', sa.String(length=100), nullable=False),
    sa.Column('Changed_At', sa.DateTime(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('ConfChangesID')
    )
    with op.batch_alter_table('CONFIGURATION_CHANGES', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_CONFIGURATION_CHANGES_LogID'), ['LogID'], unique=False)

    op.create_table('DEPLOYMENT_HISTORY',
    sa.Column('DeploymentID', sa.Integer(), nullable=False),
    sa.Column('Notes', sa.String(length=255), nullable=True),
    sa.Column('Deployment_Status', sa.Enum('FAILED', 'SUCCESS', name='deploymentstatus'), nullable=False),
    sa.Column('Deployed_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('DeploymentID')
    )
    with op.batch_alter_table('DEPLOYMENT_HISTORY', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_DEPLOYMENT_HISTORY_LogID'), ['LogID'], unique=False)

    op.create_table('EXPORT_LOG',
    sa.Column('ExportID', sa.Integer(), nullable=False),
    sa.Column('Report_Type', sa.String(length=25), nullable=False),
    sa.Column('Export_Format', sa.Enum('CSV', 'PDF', name='exportformat'), nullable=False),
    sa.Column('Start_Date', sa.DateTime(), nullable=False),
    sa.Column('End_Date', sa.DateTime(), nullable=False),
    sa.Column('Exported_At', sa.DateTime(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('ExportID')
    )
    with op.batch_alter_table('EXPORT_LOG', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_EXPORT_LOG_LogID'), ['LogID'], unique=False)

    op.create_table('NETWORK_DISCOVERY',
    sa.Column('NetDiscoveryID', sa.Integer(), nullable=False),
    sa.Column('Hostname', sa.String(length=25), nullable=False),
    sa.Column('IP_Address', sa.String(length=16), nullable=False),
    sa.Column('Subnet_Mask', sa.String(length=16), nullable=False),
    sa.Column('OS_Type', sa.String(length=25), nullable=True),
    sa.Column('Device_Type', sa.String(length=25), nullable=True),
    sa.Column('NRPE_Eligible', sa.Boolean(), nullable=False),
    sa.Column('Scan_Status', sa.Enum('PENDING', 'DEPLOYING', 'DEPLOYED', 'FAILED', 'UNREACHABLE', 'UNINSTALLED', name='scanstatus'), nullable=False),
    sa.Column('Scanned_At', sa.DateTime(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('NetDiscoveryID')
    )
    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_LogID'), ['LogID'], unique=False)

    op.create_table('NRPE_DEPLOYMENT',
    sa.Column('NRPEID', sa.Integer(), nullable=False),
    sa.Column('NRPE_Port', sa.Integer(), nullable=False),
    sa.Column('Plugin_Installed', sa.Boolean(), nullable=False),
    sa.Column('Agent_Status', sa.Enum('DISCOVERED', 'PENDING_NRPE', 'MONITORED', 'UNREACHABLE', 'EXCLUDED', name='agentstatus'), nullable=False),
    sa.Column('NetworkDiscoveryID', sa.Integer(), nullable=False),
    sa.Column('DeploymentID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DeploymentID'], ['DEPLOYMENT_HISTORY.DeploymentID'], ),
    sa.ForeignKeyConstraint(['NetworkDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('NRPEID')
    )
    with op.batch_alter_table('NRPE_DEPLOYMENT', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NRPE_DEPLOYMENT_DeploymentID'), ['DeploymentID'], unique=False)
        batch_op.create_index(batch_op.f('ix_NRPE_DEPLOYMENT_NetworkDiscoveryID'), ['NetworkDiscoveryID'], unique=False)

    op.create_table('SSH_CREDENTIALS',
    sa.Column('SSHID', sa.Integer(), nullable=False),
    sa.Column('SSH_Username', sa.String(length=50), nullable=False),
    sa.Column('SSH_Password', sa.String(length=256), nullable=False),
    sa.Column('SSH_Port', sa.Integer(), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('NetworkDiscoveryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NetworkDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('SSHID')
    )
    with op.batch_alter_table('SSH_CREDENTIALS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SSH_CREDENTIALS_NetworkDiscoveryID'), ['NetworkDiscoveryID'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SSH_CREDENTIALS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SSH_CREDENTIALS_NetworkDiscoveryID'))

    op.drop_table('SSH_CREDENTIALS')
    with op.batch_alter_table('NRPE_DEPLOYMENT', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NRPE_DEPLOYMENT_NetworkDiscoveryID'))
        batch_op.drop_index(batch_op.f('ix_NRPE_DEPLOYMENT_DeploymentID'))

    op.drop_table('NRPE_DEPLOYMENT')
    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_LogID'))

    op.drop_table('NETWORK_DISCOVERY')
    with op.batch_alter_table('EXPORT_LOG', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_EXPORT_LOG_LogID'))

    op.drop_table('EXPORT_LOG')
    with op.batch_alter_table('DEPLOYMENT_HISTORY', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DEPLOYMENT_HISTORY_LogID'))

    op.drop_table('DEPLOYMENT_HISTORY')
    with op.batch_alter_table('CONFIGURATION_CHANGES', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONFIGURATION_CHANGES_LogID'))

    op.drop_table('CONFIGURATION_CHANGES')
    with op.batch_alter_table('ACTIVITY_LOG', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ACTIVITY_LOG_UserID'))

    op.drop_table('ACTIVITY_LOG')
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_USER_RoleID'))
        batch_op.drop_index(batch_op.f('ix_USER_Email'))

    op.drop_table('USER')
    op.drop_table('ROLE')
    # ### end Alembic commands ###
