"""Added tables for TCP and UDP Serivces

Revision ID: c3d581a49635
Revises: 368239534543
Create Date: 2026-08-09 11:39:58.843117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d581a49635'
down_revision = '368239534543'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OPEN_TCP_Services',
    sa.Column('OpenPortID', sa.Integer(), nullable=False),
    sa.Column('Port_Number', sa.Integer(), nullable=False),
    sa.Column('Serivce_Name', sa.String(length=255), nullable=False),
    sa.Column('NetDiscoveryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NetDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('OpenPortID')
    )
    with op.batch_alter_table('OPEN_TCP_Services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_OPEN_TCP_Services_NetDiscoveryID'), ['NetDiscoveryID'], unique=False)

    op.create_table('OPEN_UDP_Services',
    sa.Column('OpenPortID', sa.Integer(), nullable=False),
    sa.Column('Port_Number', sa.Integer(), nullable=False),
    sa.Column('Service_Name', sa.String(length=255), nullable=False),
    sa.Column('NetDiscoveryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NetDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('OpenPortID')
    )
    with op.batch_alter_table('OPEN_UDP_Services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_OPEN_UDP_Services_NetDiscoveryID'), ['NetDiscoveryID'], unique=False)

    with op.batch_alter_table('OPEN_TCP_PORTS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_OPEN_TCP_PORTS_NetDiscoveryID'))

    op.drop_table('OPEN_TCP_PORTS')
    with op.batch_alter_table('OPEN_UDP_PORTS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_OPEN_UDP_PORTS_NetDiscoveryID'))

    op.drop_table('OPEN_UDP_PORTS')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OPEN_UDP_PORTS',
    sa.Column('OpenPortID', sa.INTEGER(), nullable=False),
    sa.Column('Port_Number', sa.INTEGER(), nullable=False),
    sa.Column('Service_Name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('NetDiscoveryID', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['NetDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('OpenPortID')
    )
    with op.batch_alter_table('OPEN_UDP_PORTS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_OPEN_UDP_PORTS_NetDiscoveryID'), ['NetDiscoveryID'], unique=False)

    op.create_table('OPEN_TCP_PORTS',
    sa.Column('OpenPortID', sa.INTEGER(), nullable=False),
    sa.Column('Port_Number', sa.INTEGER(), nullable=False),
    sa.Column('Serivce_Name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('NetDiscoveryID', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['NetDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('OpenPortID')
    )
    with op.batch_alter_table('OPEN_TCP_PORTS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_OPEN_TCP_PORTS_NetDiscoveryID'), ['NetDiscoveryID'], unique=False)

    with op.batch_alter_table('OPEN_UDP_Services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_OPEN_UDP_Services_NetDiscoveryID'))

    op.drop_table('OPEN_UDP_Services')
    with op.batch_alter_table('OPEN_TCP_Services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_OPEN_TCP_Services_NetDiscoveryID'))

    op.drop_table('OPEN_TCP_Services')
    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

