"""remove language preference

Revision ID: c99d23ea7ae6
Revises: 84b373a12347
Create Date: 2026-08-26 13:41:57.545246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99d23ea7ae6'
down_revision = '84b373a12347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER_PREFERENCES', schema=None) as batch_op:
        batch_op.drop_column('System_Language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER_PREFERENCES', schema=None) as batch_op:
        batch_op.add_column(sa.Column('System_Language', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
