"""initial schema

Revision ID: cd33c9245d9d
Revises: 
Create Date: 2026-09-04 22:59:25.303542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd33c9245d9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PERMISSION',
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('PermissionID')
    )
    with op.batch_alter_table('PERMISSION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PERMISSION_Name'), ['Name'], unique=True)

    op.create_table('PLUGIN',
    sa.Column('PluginID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Display_Name', sa.String(length=150), nullable=True),
    sa.Column('Description', sa.String(length=500), nullable=True),
    sa.Column('Author', sa.String(length=100), nullable=True),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.Column('Plugin_Type', sa.Enum('NAGIOS', 'CUSTOM', name='plugintype'), nullable=False),
    sa.Column('Source', sa.Enum('BASELINE_ISO', 'ADMINISTRATOR_ADDED', name='pluginsource'), nullable=False),
    sa.Column('Current_Version', sa.String(length=20), nullable=True),
    sa.Column('Status', sa.Enum('AVAILABLE', 'READY', 'INSTALLED', 'ENABLED', 'ACTIVE', 'DISABLED', 'UPDATE_AVAILABLE', 'VALIDATION_FAILED', 'DEPENDENCY_FAILED', 'INSTALLATION_FAILED', 'CONFIGURATION_FAILED', 'ROLLBACK', name='pluginstatus'), nullable=False),
    sa.Column('Executable_Path', sa.String(length=255), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('PluginID')
    )
    with op.batch_alter_table('PLUGIN', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_Name'), ['Name'], unique=True)

    op.create_table('ROLE',
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Is_Active', sa.Boolean(), nullable=False),
    sa.Column('Description', sa.String(length=150), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('RoleID')
    )
    with op.batch_alter_table('ROLE', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ROLE_Name'), ['Name'], unique=True)

    op.create_table('PLUGIN_COMMAND',
    sa.Column('PluginCommandID', sa.Integer(), nullable=False),
    sa.Column('Command_Name', sa.String(length=100), nullable=False),
    sa.Column('Command_Definition', sa.String(length=500), nullable=False),
    sa.Column('Is_Default', sa.Boolean(), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.Column('PluginID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PluginID'], ['PLUGIN.PluginID'], ),
    sa.PrimaryKeyConstraint('PluginCommandID')
    )
    with op.batch_alter_table('PLUGIN_COMMAND', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_COMMAND_PluginID'), ['PluginID'], unique=False)

    op.create_table('PLUGIN_CONFIGURATION',
    sa.Column('PluginConfigurationID', sa.Integer(), nullable=False),
    sa.Column('Configuration_Data', sa.JSON(), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.Column('PluginID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PluginID'], ['PLUGIN.PluginID'], ),
    sa.PrimaryKeyConstraint('PluginConfigurationID')
    )
    with op.batch_alter_table('PLUGIN_CONFIGURATION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_CONFIGURATION_PluginID'), ['PluginID'], unique=False)

    op.create_table('PLUGIN_DEPENDENCY',
    sa.Column('PluginDependencyID', sa.Integer(), nullable=False),
    sa.Column('Dependency_Name', sa.String(length=100), nullable=False),
    sa.Column('Dependency_Type', sa.Enum('BINARY', 'LIBRARY', 'PACKAGE', 'RUNTIME', name='dependencytype'), nullable=False),
    sa.Column('Required_Version', sa.String(length=20), nullable=True),
    sa.Column('Status', sa.Enum('OK', 'MISSING', 'INCOMPATIBLE', name='dependencystatus'), nullable=False),
    sa.Column('PluginID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PluginID'], ['PLUGIN.PluginID'], ),
    sa.PrimaryKeyConstraint('PluginDependencyID')
    )
    with op.batch_alter_table('PLUGIN_DEPENDENCY', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_DEPENDENCY_PluginID'), ['PluginID'], unique=False)

    op.create_table('PLUGIN_VERSION',
    sa.Column('PluginVersionID', sa.Integer(), nullable=False),
    sa.Column('Version', sa.String(length=20), nullable=False),
    sa.Column('Executable_Path', sa.String(length=255), nullable=True),
    sa.Column('Checksum', sa.String(length=64), nullable=True),
    sa.Column('Source', sa.String(length=100), nullable=True),
    sa.Column('Is_Current', sa.Boolean(), nullable=False),
    sa.Column('Installed_At', sa.DateTime(), nullable=False),
    sa.Column('Removed_At', sa.DateTime(), nullable=True),
    sa.Column('PluginID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PluginID'], ['PLUGIN.PluginID'], ),
    sa.PrimaryKeyConstraint('PluginVersionID'),
    sa.UniqueConstraint('PluginID', 'Version', name='uq_plugin_version')
    )
    with op.batch_alter_table('PLUGIN_VERSION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_VERSION_PluginID'), ['PluginID'], unique=False)

    op.create_table('ROLE_PERMISSION',
    sa.Column('RolePermissionID', sa.Integer(), nullable=False),
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PermissionID'], ['PERMISSION.PermissionID'], ),
    sa.ForeignKeyConstraint(['RoleID'], ['ROLE.RoleID'], ),
    sa.PrimaryKeyConstraint('RolePermissionID'),
    sa.UniqueConstraint('RoleID', 'PermissionID', name='uq_role_permission')
    )
    with op.batch_alter_table('ROLE_PERMISSION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ROLE_PERMISSION_PermissionID'), ['PermissionID'], unique=False)
        batch_op.create_index(batch_op.f('ix_ROLE_PERMISSION_RoleID'), ['RoleID'], unique=False)

    op.create_table('USER',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('First_Name', sa.String(length=120), nullable=False),
    sa.Column('Last_Name', sa.String(length=120), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('Hashed_Password', sa.String(length=256), nullable=False),
    sa.Column('Status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['RoleID'], ['ROLE.RoleID'], ),
    sa.PrimaryKeyConstraint('UserID')
    )
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_USER_Email'), ['Email'], unique=True)
        batch_op.create_index(batch_op.f('ix_USER_RoleID'), ['RoleID'], unique=False)

    op.create_table('ACK_HISTORY',
    sa.Column('AckHistoryID', sa.Integer(), nullable=False),
    sa.Column('Hostname', sa.String(length=100), nullable=False),
    sa.Column('Service_Name', sa.String(length=150), nullable=True),
    sa.Column('Action', sa.Enum('ACKNOWLEDGED', 'UNACKNOWLEDGED', 'AUTO_RESOLVED', name='ackaction'), nullable=False),
    sa.Column('Actioned_At', sa.DateTime(), nullable=False),
    sa.Column('ActorUserID', sa.Integer(), nullable=True),
    sa.Column('Comment', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ActorUserID'], ['USER.UserID'], ),
    sa.PrimaryKeyConstraint('AckHistoryID')
    )
    with op.batch_alter_table('ACK_HISTORY', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ACK_HISTORY_Actioned_At'), ['Actioned_At'], unique=False)
        batch_op.create_index(batch_op.f('ix_ACK_HISTORY_ActorUserID'), ['ActorUserID'], unique=False)
        batch_op.create_index(batch_op.f('ix_ACK_HISTORY_Hostname'), ['Hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_ACK_HISTORY_Service_Name'), ['Service_Name'], unique=False)

    op.create_table('ACTIVITY_LOG',
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.Column('Action_Type', sa.String(length=255), nullable=False),
    sa.Column('Performed_At', sa.DateTime(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['USER.UserID'], ),
    sa.PrimaryKeyConstraint('LogID')
    )
    with op.batch_alter_table('ACTIVITY_LOG', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ACTIVITY_LOG_UserID'), ['UserID'], unique=False)

    op.create_table('ALERT_ACKNOWLEDGEMENT',
    sa.Column('AckID', sa.Integer(), nullable=False),
    sa.Column('Hostname', sa.String(length=100), nullable=False),
    sa.Column('Service_Name', sa.String(length=150), nullable=True),
    sa.Column('Comment', sa.String(length=500), nullable=False),
    sa.Column('Acknowledged_At', sa.DateTime(), nullable=False),
    sa.Column('AcknowledgedBy', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AcknowledgedBy'], ['USER.UserID'], ),
    sa.PrimaryKeyConstraint('AckID'),
    sa.UniqueConstraint('Hostname', 'Service_Name', name='uq_alert_acknowledgement_host_service')
    )
    with op.batch_alter_table('ALERT_ACKNOWLEDGEMENT', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ALERT_ACKNOWLEDGEMENT_AcknowledgedBy'), ['AcknowledgedBy'], unique=False)
        batch_op.create_index(batch_op.f('ix_ALERT_ACKNOWLEDGEMENT_Hostname'), ['Hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_ALERT_ACKNOWLEDGEMENT_Service_Name'), ['Service_Name'], unique=False)

    op.create_table('NOTIFICATION_CURSOR',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('last_seen_ts', sa.BigInteger(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['USER.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_table('SYSTEM_SETTINGS',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('System_Language', sa.String(length=20), nullable=False),
    sa.Column('Theme', sa.String(length=10), nullable=False),
    sa.Column('Time_Zone', sa.String(length=20), nullable=False),
    sa.Column('Date_Time_Format', sa.String(length=20), nullable=False),
    sa.Column('System_Font', sa.String(length=30), nullable=False),
    sa.Column('System_Font_Size', sa.String(length=10), nullable=False),
    sa.Column('Dashboard_Refresh_Rate', sa.Integer(), nullable=False),
    sa.Column('Scan_Frequency', sa.Integer(), nullable=False),
    sa.Column('Dashboard_Layout', sa.String(length=15), nullable=False),
    sa.Column('Notifications', sa.Boolean(), nullable=False),
    sa.Column('Export_Formats', sa.String(length=50), nullable=False),
    sa.Column('Session_Timeout', sa.Integer(), nullable=False),
    sa.Column('Strong_Password_Policy', sa.Boolean(), nullable=False),
    sa.Column('Failed_Login_Monitoring', sa.Boolean(), nullable=False),
    sa.Column('Audit_Logging', sa.Boolean(), nullable=False),
    sa.Column('Security_Check_Frequency', sa.String(length=10), nullable=False),
    sa.Column('System_Update_Frequency', sa.String(length=10), nullable=False),
    sa.Column('Maintenance_Mode', sa.Boolean(), nullable=False),
    sa.Column('Automatic_Backups', sa.Boolean(), nullable=False),
    sa.Column('Log_Retention_Days', sa.Integer(), nullable=False),
    sa.Column('Diagnostic_History_Retention_Days', sa.Integer(), nullable=False),
    sa.Column('Version', sa.Integer(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_By', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Updated_By'], ['USER.UserID'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('SYSTEM_SETTINGS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SYSTEM_SETTINGS_Updated_By'), ['Updated_By'], unique=False)

    op.create_table('CONFIGURATION_CHANGES',
    sa.Column('ConfChangesID', sa.Integer(), nullable=False),
    sa.Column('Conf_Type', sa.String(length=25), nullable=False),
    sa.Column('Parameter_Name', sa.String(length=50), nullable=False),
    sa.Column('Old_Value', sa.String(length=100), nullable=False),
    sa.Column('New_Value', sa.String(length=100), nullable=False),
    sa.Column('Changed_At', sa.DateTime(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('ConfChangesID')
    )
    with op.batch_alter_table('CONFIGURATION_CHANGES', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_CONFIGURATION_CHANGES_LogID'), ['LogID'], unique=False)

    op.create_table('EXPORT_LOG',
    sa.Column('ExportID', sa.Integer(), nullable=False),
    sa.Column('Report_Type', sa.String(length=25), nullable=False),
    sa.Column('Export_Format', sa.Enum('CSV', 'PDF', name='exportformat'), nullable=False),
    sa.Column('Start_Date', sa.DateTime(), nullable=False),
    sa.Column('End_Date', sa.DateTime(), nullable=False),
    sa.Column('Exported_At', sa.DateTime(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('ExportID')
    )
    with op.batch_alter_table('EXPORT_LOG', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_EXPORT_LOG_LogID'), ['LogID'], unique=False)

    op.create_table('NCPA_DEPLOYMENT_STATUS',
    sa.Column('NCPADeployStatusID', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL_FAILURE', 'FAILED', 'INTERRUPTED', name='deploymentstatus'), nullable=False),
    sa.Column('Progress', sa.Integer(), nullable=False),
    sa.Column('Message', sa.String(length=100), nullable=False),
    sa.Column('Start_At', sa.DateTime(), nullable=False),
    sa.Column('Completed_At', sa.DateTime(), nullable=True),
    sa.Column('Error', sa.String(), nullable=True),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('NCPADeployStatusID')
    )
    op.create_table('NETWORK_DISCOVERY_STATUS',
    sa.Column('DiscoveryStatusID', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', 'INTERRUPTED', name='discoverystatus'), nullable=False),
    sa.Column('Progress', sa.Integer(), nullable=False),
    sa.Column('Message', sa.String(length=100), nullable=False),
    sa.Column('Start_At', sa.DateTime(), nullable=False),
    sa.Column('Completed_At', sa.DateTime(), nullable=True),
    sa.Column('Error', sa.String(), nullable=True),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('DiscoveryStatusID')
    )
    with op.batch_alter_table('NETWORK_DISCOVERY_STATUS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_STATUS_LogID'), ['LogID'], unique=False)

    op.create_table('PLUGIN_COMMAND_OVERRIDE',
    sa.Column('PluginCommandOverrideID', sa.Integer(), nullable=False),
    sa.Column('Original_Command', sa.String(length=500), nullable=False),
    sa.Column('Override_Command', sa.String(length=500), nullable=False),
    sa.Column('Is_Active', sa.Boolean(), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.Column('PluginCommandID', sa.Integer(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.ForeignKeyConstraint(['PluginCommandID'], ['PLUGIN_COMMAND.PluginCommandID'], ),
    sa.PrimaryKeyConstraint('PluginCommandOverrideID')
    )
    with op.batch_alter_table('PLUGIN_COMMAND_OVERRIDE', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_COMMAND_OVERRIDE_LogID'), ['LogID'], unique=False)
        batch_op.create_index(batch_op.f('ix_PLUGIN_COMMAND_OVERRIDE_PluginCommandID'), ['PluginCommandID'], unique=False)

    op.create_table('PLUGIN_HISTORY',
    sa.Column('PluginHistoryID', sa.Integer(), nullable=False),
    sa.Column('Action', sa.Enum('INSTALL', 'UPDATE', 'ENABLE', 'DISABLE', 'CONFIGURE', 'COMMAND_OVERRIDE', 'VALIDATE', 'ROLLBACK', 'REMOVE', name='pluginhistoryaction'), nullable=False),
    sa.Column('Old_Value', sa.String(length=255), nullable=True),
    sa.Column('New_Value', sa.String(length=255), nullable=True),
    sa.Column('Result', sa.Enum('SUCCESS', 'FAILED', name='pluginactionresult'), nullable=False),
    sa.Column('Message', sa.String(length=500), nullable=True),
    sa.Column('PluginID', sa.Integer(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.ForeignKeyConstraint(['PluginID'], ['PLUGIN.PluginID'], ),
    sa.PrimaryKeyConstraint('PluginHistoryID')
    )
    with op.batch_alter_table('PLUGIN_HISTORY', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_HISTORY_LogID'), ['LogID'], unique=False)
        batch_op.create_index(batch_op.f('ix_PLUGIN_HISTORY_PluginID'), ['PluginID'], unique=False)

    op.create_table('PLUGIN_SCAN_STATUS',
    sa.Column('PluginScanStatusID', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='pluginscanstatusvalue'), nullable=False),
    sa.Column('Progress', sa.Integer(), nullable=False),
    sa.Column('Message', sa.String(length=100), nullable=False),
    sa.Column('Start_At', sa.DateTime(), nullable=False),
    sa.Column('Completed_At', sa.DateTime(), nullable=True),
    sa.Column('Error', sa.String(), nullable=True),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('PluginScanStatusID')
    )
    with op.batch_alter_table('PLUGIN_SCAN_STATUS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PLUGIN_SCAN_STATUS_LogID'), ['LogID'], unique=False)

    op.create_table('NETWORK_DISCOVERY',
    sa.Column('NetDiscoveryID', sa.Integer(), nullable=False),
    sa.Column('Hostname', sa.String(length=100), nullable=True),
    sa.Column('IP_Address', sa.String(length=16), nullable=False),
    sa.Column('Network', sa.String(length=16), nullable=False),
    sa.Column('MAC_Address', sa.String(length=17), nullable=True),
    sa.Column('OS_Type', sa.String(length=25), nullable=True),
    sa.Column('Device_Type', sa.String(length=25), nullable=True),
    sa.Column('NCPA_Eligible', sa.Boolean(), nullable=False),
    sa.Column('Scanned_At', sa.DateTime(), nullable=False),
    sa.Column('Include_Device_In_Scanning', sa.Boolean(), nullable=False),
    sa.Column('DiscoveryStatusID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DiscoveryStatusID'], ['NETWORK_DISCOVERY_STATUS.DiscoveryStatusID'], ),
    sa.PrimaryKeyConstraint('NetDiscoveryID')
    )
    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_DiscoveryStatusID'), ['DiscoveryStatusID'], unique=False)
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_IP_Address'), ['IP_Address'], unique=False)
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_MAC_Address'), ['MAC_Address'], unique=False)
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_Network'), ['Network'], unique=False)

    op.create_table('NCPA_DEPLOYMENT',
    sa.Column('NCPADeployID', sa.Integer(), nullable=False),
    sa.Column('Deployement_Method', sa.Enum('AUTOMATIC', 'MANUAL', name='deploymentmethod'), nullable=True),
    sa.Column('Token', sa.String(length=32), nullable=True),
    sa.Column('Agent_Status', sa.Enum('PENDING_NCPA', 'DEPLOYED', 'FAILED', 'EXCLUDED', 'INCOMPATIBLE', name='agentstatus'), nullable=True),
    sa.Column('Error', sa.String(), nullable=True),
    sa.Column('NCPADeploymentStatusID', sa.Integer(), nullable=True),
    sa.Column('NetworkDiscoveryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NCPADeploymentStatusID'], ['NCPA_DEPLOYMENT_STATUS.NCPADeployStatusID'], ),
    sa.ForeignKeyConstraint(['NetworkDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('NCPADeployID')
    )
    with op.batch_alter_table('NCPA_DEPLOYMENT', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NCPA_DEPLOYMENT_NetworkDiscoveryID'), ['NetworkDiscoveryID'], unique=False)

    op.create_table('OPEN_TCP_Services',
    sa.Column('OpenPortID', sa.Integer(), nullable=False),
    sa.Column('Port_Number', sa.Integer(), nullable=False),
    sa.Column('Service_Name', sa.String(length=255), nullable=False),
    sa.Column('NetDiscoveryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NetDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('OpenPortID')
    )
    with op.batch_alter_table('OPEN_TCP_Services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_OPEN_TCP_Services_NetDiscoveryID'), ['NetDiscoveryID'], unique=False)

    op.create_table('OPEN_UDP_Services',
    sa.Column('OpenPortID', sa.Integer(), nullable=False),
    sa.Column('Port_Number', sa.Integer(), nullable=False),
    sa.Column('Service_Name', sa.String(length=255), nullable=False),
    sa.Column('NetDiscoveryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NetDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('OpenPortID')
    )
    with op.batch_alter_table('OPEN_UDP_Services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_OPEN_UDP_Services_NetDiscoveryID'), ['NetDiscoveryID'], unique=False)

    op.create_table('SSH_CREDENTIALS',
    sa.Column('SSHID', sa.Integer(), nullable=False),
    sa.Column('SSH_Port', sa.Integer(), nullable=False),
    sa.Column('Key_Installed', sa.Boolean(), nullable=False),
    sa.Column('Key_Fingerprint', sa.String(), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=True),
    sa.Column('NetworkDiscoveryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NetworkDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('SSHID')
    )
    with op.batch_alter_table('SSH_CREDENTIALS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SSH_CREDENTIALS_NetworkDiscoveryID'), ['NetworkDiscoveryID'], unique=False)

    op.create_table('NCPA_DEVICE_PARTITION',
    sa.Column('PartitionID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=False),
    sa.Column('NCPADeployID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NCPADeployID'], ['NCPA_DEPLOYMENT.NCPADeployID'], ),
    sa.PrimaryKeyConstraint('PartitionID')
    )
    with op.batch_alter_table('NCPA_DEVICE_PARTITION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NCPA_DEVICE_PARTITION_NCPADeployID'), ['NCPADeployID'], unique=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NCPA_DEVICE_PARTITION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NCPA_DEVICE_PARTITION_NCPADeployID'))

    op.drop_table('NCPA_DEVICE_PARTITION')
    with op.batch_alter_table('SSH_CREDENTIALS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SSH_CREDENTIALS_NetworkDiscoveryID'))

    op.drop_table('SSH_CREDENTIALS')
    with op.batch_alter_table('OPEN_UDP_Services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_OPEN_UDP_Services_NetDiscoveryID'))

    op.drop_table('OPEN_UDP_Services')
    with op.batch_alter_table('OPEN_TCP_Services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_OPEN_TCP_Services_NetDiscoveryID'))

    op.drop_table('OPEN_TCP_Services')
    with op.batch_alter_table('NCPA_DEPLOYMENT', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NCPA_DEPLOYMENT_NetworkDiscoveryID'))

    op.drop_table('NCPA_DEPLOYMENT')
    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_Network'))
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_MAC_Address'))
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_IP_Address'))
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_DiscoveryStatusID'))

    op.drop_table('NETWORK_DISCOVERY')
    with op.batch_alter_table('PLUGIN_SCAN_STATUS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_SCAN_STATUS_LogID'))

    op.drop_table('PLUGIN_SCAN_STATUS')
    with op.batch_alter_table('PLUGIN_HISTORY', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_HISTORY_PluginID'))
        batch_op.drop_index(batch_op.f('ix_PLUGIN_HISTORY_LogID'))

    op.drop_table('PLUGIN_HISTORY')
    with op.batch_alter_table('PLUGIN_COMMAND_OVERRIDE', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_COMMAND_OVERRIDE_PluginCommandID'))
        batch_op.drop_index(batch_op.f('ix_PLUGIN_COMMAND_OVERRIDE_LogID'))

    op.drop_table('PLUGIN_COMMAND_OVERRIDE')
    with op.batch_alter_table('NETWORK_DISCOVERY_STATUS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_STATUS_LogID'))

    op.drop_table('NETWORK_DISCOVERY_STATUS')
    op.drop_table('NCPA_DEPLOYMENT_STATUS')
    with op.batch_alter_table('EXPORT_LOG', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_EXPORT_LOG_LogID'))

    op.drop_table('EXPORT_LOG')
    with op.batch_alter_table('CONFIGURATION_CHANGES', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONFIGURATION_CHANGES_LogID'))

    op.drop_table('CONFIGURATION_CHANGES')
    with op.batch_alter_table('SYSTEM_SETTINGS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SYSTEM_SETTINGS_Updated_By'))

    op.drop_table('SYSTEM_SETTINGS')
    op.drop_table('NOTIFICATION_CURSOR')
    with op.batch_alter_table('ALERT_ACKNOWLEDGEMENT', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ALERT_ACKNOWLEDGEMENT_Service_Name'))
        batch_op.drop_index(batch_op.f('ix_ALERT_ACKNOWLEDGEMENT_Hostname'))
        batch_op.drop_index(batch_op.f('ix_ALERT_ACKNOWLEDGEMENT_AcknowledgedBy'))

    op.drop_table('ALERT_ACKNOWLEDGEMENT')
    with op.batch_alter_table('ACTIVITY_LOG', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ACTIVITY_LOG_UserID'))

    op.drop_table('ACTIVITY_LOG')
    with op.batch_alter_table('ACK_HISTORY', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ACK_HISTORY_Service_Name'))
        batch_op.drop_index(batch_op.f('ix_ACK_HISTORY_Hostname'))
        batch_op.drop_index(batch_op.f('ix_ACK_HISTORY_ActorUserID'))
        batch_op.drop_index(batch_op.f('ix_ACK_HISTORY_Actioned_At'))

    op.drop_table('ACK_HISTORY')
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_USER_RoleID'))
        batch_op.drop_index(batch_op.f('ix_USER_Email'))

    op.drop_table('USER')
    with op.batch_alter_table('ROLE_PERMISSION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ROLE_PERMISSION_RoleID'))
        batch_op.drop_index(batch_op.f('ix_ROLE_PERMISSION_PermissionID'))

    op.drop_table('ROLE_PERMISSION')
    with op.batch_alter_table('PLUGIN_VERSION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_VERSION_PluginID'))

    op.drop_table('PLUGIN_VERSION')
    with op.batch_alter_table('PLUGIN_DEPENDENCY', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_DEPENDENCY_PluginID'))

    op.drop_table('PLUGIN_DEPENDENCY')
    with op.batch_alter_table('PLUGIN_CONFIGURATION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_CONFIGURATION_PluginID'))

    op.drop_table('PLUGIN_CONFIGURATION')
    with op.batch_alter_table('PLUGIN_COMMAND', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_COMMAND_PluginID'))

    op.drop_table('PLUGIN_COMMAND')
    with op.batch_alter_table('ROLE', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ROLE_Name'))

    op.drop_table('ROLE')
    with op.batch_alter_table('PLUGIN', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PLUGIN_Name'))

    op.drop_table('PLUGIN')
    with op.batch_alter_table('PERMISSION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PERMISSION_Name'))

    op.drop_table('PERMISSION')
    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HOST_STATUS',
    sa.Column('HostStatusID', sa.Integer(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.Column('Hostname', sa.String(length=100), nullable=False),
    sa.Column('Current_State', sa.Enum('UP', 'DOWN', 'UNREACHABLE', name='hoststatetype'), nullable=False),
    sa.Column('Plugin_Status', sa.Enum('OK', 'WARNING', 'CRITICAL', 'UNKNOWN', name='pluginstatustype'), nullable=False),
    sa.Column('Plugin_Output', sa.String(length=255), nullable=False),
    sa.Column('State_Type', sa.Enum('SOFT', 'HARD', name='connectionstatetype'), nullable=False),
    sa.Column('Current_Attempt', sa.Integer(), nullable=False),
    sa.Column('Max_Attempts', sa.Integer(), nullable=False),
    sa.Column('Last_Check', sa.DateTime(), nullable=False),
    sa.Column('Next_Check', sa.DateTime(), nullable=False),
    sa.Column('Last_State_Change', sa.DateTime(), nullable=True),
    sa.Column('Last_Hard_State_Change', sa.DateTime(), nullable=True),
    sa.Column('Last_Time_Up', sa.DateTime(), nullable=True),
    sa.Column('Last_Time_Down', sa.DateTime(), nullable=True),
    sa.Column('Last_Time_Unreachable', sa.DateTime(), nullable=True),
    sa.Column('Check_Latency', sa.Float(precision=6), nullable=False),
    sa.Column('Check_Execution_Time', sa.Float(precision=6), nullable=False),
    sa.Column('Is_Flapping', sa.Boolean(), nullable=False),
    sa.Column('Acknowledgement_Type', sa.Enum('NOACK', 'NORMACK', 'STICKYACK', name='acknowledgementtype'), nullable=False),
    sa.Column('Scheduled_Downtime_Depth', sa.Integer(), nullable=False),
    sa.Column('Notification_Enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('HostStatusID')
    )
    with op.batch_alter_table('HOST_STATUS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_HOST_STATUS_Hostname'), ['Hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_HOST_STATUS_Timestamp'), ['Timestamp'], unique=False)

    op.create_table('PROGRAM_STATUS',
    sa.Column('ProgramStatusID', sa.Integer(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.Column('Version', sa.String(length=20), nullable=True),
    sa.Column('Update_Available', sa.Boolean(), nullable=False),
    sa.Column('New_Version', sa.String(length=20), nullable=True),
    sa.Column('Last_Update_Check', sa.DateTime(), nullable=False),
    sa.Column('NagiosPID', sa.Integer(), nullable=True),
    sa.Column('Enable_Notifications', sa.Boolean(), nullable=False),
    sa.Column('Enable_Flap_Detection', sa.Boolean(), nullable=False),
    sa.Column('Daemon_Mode', sa.Boolean(), nullable=False),
    sa.Column('Program_Start_Time', sa.DateTime(), nullable=False),
    sa.Column('Passive_Host_Checks_Enabled', sa.Boolean(), nullable=False),
    sa.Column('Active_Host_Checks_Enabled', sa.Boolean(), nullable=False),
    sa.Column('Passive_Service_Checks_Enabled', sa.Boolean(), nullable=False),
    sa.Column('Active_Service_Checks_Enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ProgramStatusID')
    )
    with op.batch_alter_table('PROGRAM_STATUS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PROGRAM_STATUS_Timestamp'), ['Timestamp'], unique=False)

    op.create_table('SERVICE_STATUS',
    sa.Column('ServiceStatusID', sa.Integer(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.Column('Hostname', sa.String(length=100), nullable=False),
    sa.Column('Service', sa.String(length=150), nullable=False),
    sa.Column('Current_State', sa.Enum('OK', 'WARNING', 'CRITICAL', 'UNKNOWN', name='servicestatetype'), nullable=False),
    sa.Column('Plugin_Output', sa.String(length=255), nullable=False),
    sa.Column('State_Type', sa.Enum('SOFT', 'HARD', name='connectionstatetype'), nullable=False),
    sa.Column('Last_Time_Ok', sa.DateTime(), nullable=True),
    sa.Column('Last_Time_Warning', sa.DateTime(), nullable=True),
    sa.Column('Last_Time_Critical', sa.DateTime(), nullable=True),
    sa.Column('Last_Time_Unknown', sa.DateTime(), nullable=True),
    sa.Column('Current_Attempt', sa.Integer(), nullable=False),
    sa.Column('Max_Attempts', sa.Integer(), nullable=False),
    sa.Column('Last_Check', sa.DateTime(), nullable=False),
    sa.Column('Next_Check', sa.DateTime(), nullable=False),
    sa.Column('Last_State_Change', sa.DateTime(), nullable=True),
    sa.Column('Last_Hard_State_Change', sa.DateTime(), nullable=True),
    sa.Column('Check_Latency', sa.Float(precision=6), nullable=False),
    sa.Column('Check_Execution_Time', sa.Float(precision=6), nullable=False),
    sa.Column('Notification_Enabled', sa.Boolean(), nullable=False),
    sa.Column('Acknowledgement_Type', sa.Enum('NOACK', 'NORMACK', 'STICKYACK', name='acknowledgementtype'), nullable=False),
    sa.Column('Is_Flapping', sa.Boolean(), nullable=False),
    sa.Column('Scheduled_Downtime_Depth', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ServiceStatusID')
    )
    with op.batch_alter_table('SERVICE_STATUS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SERVICE_STATUS_Hostname'), ['Hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_SERVICE_STATUS_Timestamp'), ['Timestamp'], unique=False)

    op.create_table('HOST_PERF_DATA',
    sa.Column('HostPerfDataID', sa.Integer(), nullable=False),
    sa.Column('Metric', sa.String(length=50), nullable=False),
    sa.Column('Measured_Value', sa.Float(precision=6), nullable=False),
    sa.Column('Unit', sa.String(length=5), nullable=True),
    sa.Column('Warning_Threshold', sa.Float(precision=6), nullable=True),
    sa.Column('Critical_Threshold', sa.Float(precision=6), nullable=True),
    sa.Column('Minimum', sa.Float(precision=6), nullable=True),
    sa.Column('Maximum', sa.Float(precision=6), nullable=True),
    sa.Column('HostStatusID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['HostStatusID'], ['HOST_STATUS.HostStatusID'], ),
    sa.PrimaryKeyConstraint('HostPerfDataID')
    )
    with op.batch_alter_table('HOST_PERF_DATA', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_HOST_PERF_DATA_HostStatusID'), ['HostStatusID'], unique=False)

    op.create_table('SERVICE_PERF_DATA',
    sa.Column('ServicePerfDataID', sa.Integer(), nullable=False),
    sa.Column('Metric', sa.String(length=50), nullable=False),
    sa.Column('Measured_Value', sa.Float(precision=6), nullable=False),
    sa.Column('Unit', sa.String(length=5), nullable=True),
    sa.Column('Warning_Threshold', sa.Float(precision=6), nullable=True),
    sa.Column('Critical_Threshold', sa.Float(precision=6), nullable=True),
    sa.Column('Minimum', sa.Float(precision=6), nullable=True),
    sa.Column('Maximum', sa.Float(precision=6), nullable=True),
    sa.Column('ServiceStatusID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ServiceStatusID'], ['SERVICE_STATUS.ServiceStatusID'], ),
    sa.PrimaryKeyConstraint('ServicePerfDataID')
    )
    with op.batch_alter_table('SERVICE_PERF_DATA', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SERVICE_PERF_DATA_ServiceStatusID'), ['ServiceStatusID'], unique=False)

    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SERVICE_PERF_DATA', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SERVICE_PERF_DATA_ServiceStatusID'))

    op.drop_table('SERVICE_PERF_DATA')
    with op.batch_alter_table('HOST_PERF_DATA', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_HOST_PERF_DATA_HostStatusID'))

    op.drop_table('HOST_PERF_DATA')
    with op.batch_alter_table('SERVICE_STATUS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SERVICE_STATUS_Timestamp'))
        batch_op.drop_index(batch_op.f('ix_SERVICE_STATUS_Hostname'))

    op.drop_table('SERVICE_STATUS')
    with op.batch_alter_table('PROGRAM_STATUS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PROGRAM_STATUS_Timestamp'))

    op.drop_table('PROGRAM_STATUS')
    with op.batch_alter_table('HOST_STATUS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_HOST_STATUS_Timestamp'))
        batch_op.drop_index(batch_op.f('ix_HOST_STATUS_Hostname'))

    op.drop_table('HOST_STATUS')
    # ### end Alembic commands ###

