"""added missing fields

Revision ID: d39f95f919be
Revises: e75590552a35
Create Date: 2026-06-15 18:15:24.233260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39f95f919be'
down_revision = 'e75590552a35'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HOST_LOG', schema=None) as batch_op:
        batch_op.alter_column('Plugin_Output',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('NAGIOS_STATUS_INFO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Version', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('Update_Available', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('New_Version', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('Last_Update_Check', sa.DateTime(), nullable=False))
        batch_op.drop_column('Entry_Type')

    with op.batch_alter_table('PROGRAM_STATUS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NagiosPID', sa.Integer(), nullable=True))

    with op.batch_alter_table('SERVICE_LOG', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Attempt_Count', sa.Integer(), nullable=False))
        batch_op.drop_column('Attempt_count')

    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SERVICE_LOG', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Attempt_count', sa.INTEGER(), nullable=False))
        batch_op.drop_column('Attempt_Count')

    with op.batch_alter_table('PROGRAM_STATUS', schema=None) as batch_op:
        batch_op.drop_column('NagiosPID')

    with op.batch_alter_table('NAGIOS_STATUS_INFO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Entry_Type', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('Last_Update_Check')
        batch_op.drop_column('New_Version')
        batch_op.drop_column('Update_Available')
        batch_op.drop_column('Version')

    with op.batch_alter_table('HOST_LOG', schema=None) as batch_op:
        batch_op.alter_column('Plugin_Output',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###

