"""initial database schema

Revision ID: d6150bbf8780
Revises: 
Create Date: 2026-07-12 15:40:06.220600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6150bbf8780'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PERMISSION',
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('PermissionID')
    )
    with op.batch_alter_table('PERMISSION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PERMISSION_Name'), ['Name'], unique=True)

    op.create_table('ROLE',
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Is_Active', sa.Boolean(), nullable=False),
    sa.Column('Description', sa.String(length=150), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('RoleID')
    )
    with op.batch_alter_table('ROLE', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ROLE_Name'), ['Name'], unique=True)

    op.create_table('ROLE_PERMISSION',
    sa.Column('RolePermissionID', sa.Integer(), nullable=False),
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PermissionID'], ['PERMISSION.PermissionID'], ),
    sa.ForeignKeyConstraint(['RoleID'], ['ROLE.RoleID'], ),
    sa.PrimaryKeyConstraint('RolePermissionID'),
    sa.UniqueConstraint('RoleID', 'PermissionID', name='uq_role_permission')
    )
    with op.batch_alter_table('ROLE_PERMISSION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ROLE_PERMISSION_PermissionID'), ['PermissionID'], unique=False)
        batch_op.create_index(batch_op.f('ix_ROLE_PERMISSION_RoleID'), ['RoleID'], unique=False)

    op.create_table('USER',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('First_name', sa.String(length=120), nullable=False),
    sa.Column('Last_name', sa.String(length=120), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('Hashed_Password', sa.String(length=256), nullable=False),
    sa.Column('Status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['RoleID'], ['ROLE.RoleID'], ),
    sa.PrimaryKeyConstraint('UserID')
    )
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_USER_Email'), ['Email'], unique=True)
        batch_op.create_index(batch_op.f('ix_USER_RoleID'), ['RoleID'], unique=False)

    op.create_table('ACTIVITY_LOG',
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.Column('Action_Type', sa.String(length=255), nullable=False),
    sa.Column('Performed_At', sa.DateTime(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['USER.UserID'], ),
    sa.PrimaryKeyConstraint('LogID')
    )
    with op.batch_alter_table('ACTIVITY_LOG', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ACTIVITY_LOG_UserID'), ['UserID'], unique=False)

    op.create_table('CONFIGURATION_CHANGES',
    sa.Column('ConfChangesID', sa.Integer(), nullable=False),
    sa.Column('Conf_Type', sa.String(length=25), nullable=False),
    sa.Column('Parameter_Name', sa.String(length=50), nullable=False),
    sa.Column('Old_Value', sa.String(length=100), nullable=False),
    sa.Column('New_Value', sa.String(length=100), nullable=False),
    sa.Column('Changed_At', sa.DateTime(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('ConfChangesID')
    )
    with op.batch_alter_table('CONFIGURATION_CHANGES', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_CONFIGURATION_CHANGES_LogID'), ['LogID'], unique=False)

    op.create_table('DEPLOYMENT_HISTORY',
    sa.Column('DeploymentID', sa.Integer(), nullable=False),
    sa.Column('Notes', sa.String(length=255), nullable=True),
    sa.Column('Deployment_Status', sa.Enum('FAILED', 'SUCCESS', name='deploymentstatus'), nullable=False),
    sa.Column('Deployed_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('DeploymentID')
    )
    with op.batch_alter_table('DEPLOYMENT_HISTORY', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_DEPLOYMENT_HISTORY_LogID'), ['LogID'], unique=False)

    op.create_table('EXPORT_LOG',
    sa.Column('ExportID', sa.Integer(), nullable=False),
    sa.Column('Report_Type', sa.String(length=25), nullable=False),
    sa.Column('Export_Format', sa.Enum('CSV', 'PDF', name='exportformat'), nullable=False),
    sa.Column('Start_Date', sa.DateTime(), nullable=False),
    sa.Column('End_Date', sa.DateTime(), nullable=False),
    sa.Column('Exported_At', sa.DateTime(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('ExportID')
    )
    with op.batch_alter_table('EXPORT_LOG', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_EXPORT_LOG_LogID'), ['LogID'], unique=False)

    op.create_table('NETWORK_DISCOVERY',
    sa.Column('NetDiscoveryID', sa.Integer(), nullable=False),
    sa.Column('Hostname', sa.String(length=100), nullable=True),
    sa.Column('IP_Address', sa.String(length=16), nullable=False),
    sa.Column('Subnet_Mask', sa.String(length=16), nullable=False),
    sa.Column('MAC_Address', sa.String(length=17), nullable=True),
    sa.Column('OS_Type', sa.String(length=25), nullable=True),
    sa.Column('Device_Type', sa.String(length=25), nullable=True),
    sa.Column('NRPE_Eligible', sa.Boolean(), nullable=False),
    sa.Column('Scan_Status', sa.Enum('PENDING', 'DEPLOYING', 'DEPLOYED', 'FAILED', 'UNREACHABLE', 'UNINSTALLED', name='scanstatus'), nullable=False),
    sa.Column('Scanned_At', sa.DateTime(), nullable=False),
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LogID'], ['ACTIVITY_LOG.LogID'], ),
    sa.PrimaryKeyConstraint('NetDiscoveryID')
    )
    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_IP_Address'), ['IP_Address'], unique=False)
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_LogID'), ['LogID'], unique=False)
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_MAC_Address'), ['MAC_Address'], unique=False)
        batch_op.create_index(batch_op.f('ix_NETWORK_DISCOVERY_Subnet_Mask'), ['Subnet_Mask'], unique=False)

    op.create_table('NRPE_DEPLOYMENT',
    sa.Column('NRPEID', sa.Integer(), nullable=False),
    sa.Column('NRPE_Port', sa.Integer(), nullable=False),
    sa.Column('Plugin_Installed', sa.Boolean(), nullable=False),
    sa.Column('Agent_Status', sa.Enum('DISCOVERED', 'PENDING_NRPE', 'MONITORED', 'UNREACHABLE', 'EXCLUDED', name='agentstatus'), nullable=False),
    sa.Column('NetworkDiscoveryID', sa.Integer(), nullable=False),
    sa.Column('DeploymentID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DeploymentID'], ['DEPLOYMENT_HISTORY.DeploymentID'], ),
    sa.ForeignKeyConstraint(['NetworkDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('NRPEID')
    )
    with op.batch_alter_table('NRPE_DEPLOYMENT', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NRPE_DEPLOYMENT_DeploymentID'), ['DeploymentID'], unique=False)
        batch_op.create_index(batch_op.f('ix_NRPE_DEPLOYMENT_NetworkDiscoveryID'), ['NetworkDiscoveryID'], unique=False)

    op.create_table('SSH_CREDENTIALS',
    sa.Column('SSHID', sa.Integer(), nullable=False),
    sa.Column('SSH_Username', sa.String(length=50), nullable=False),
    sa.Column('SSH_Port', sa.Integer(), nullable=False),
    sa.Column('Key_Installed', sa.Boolean(), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('NetworkDiscoveryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NetworkDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('SSHID')
    )
    with op.batch_alter_table('SSH_CREDENTIALS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SSH_CREDENTIALS_NetworkDiscoveryID'), ['NetworkDiscoveryID'], unique=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SSH_CREDENTIALS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SSH_CREDENTIALS_NetworkDiscoveryID'))

    op.drop_table('SSH_CREDENTIALS')
    with op.batch_alter_table('NRPE_DEPLOYMENT', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NRPE_DEPLOYMENT_NetworkDiscoveryID'))
        batch_op.drop_index(batch_op.f('ix_NRPE_DEPLOYMENT_DeploymentID'))

    op.drop_table('NRPE_DEPLOYMENT')
    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_Subnet_Mask'))
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_MAC_Address'))
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_LogID'))
        batch_op.drop_index(batch_op.f('ix_NETWORK_DISCOVERY_IP_Address'))

    op.drop_table('NETWORK_DISCOVERY')
    with op.batch_alter_table('EXPORT_LOG', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_EXPORT_LOG_LogID'))

    op.drop_table('EXPORT_LOG')
    with op.batch_alter_table('DEPLOYMENT_HISTORY', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DEPLOYMENT_HISTORY_LogID'))

    op.drop_table('DEPLOYMENT_HISTORY')
    with op.batch_alter_table('CONFIGURATION_CHANGES', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONFIGURATION_CHANGES_LogID'))

    op.drop_table('CONFIGURATION_CHANGES')
    with op.batch_alter_table('ACTIVITY_LOG', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ACTIVITY_LOG_UserID'))

    op.drop_table('ACTIVITY_LOG')
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_USER_RoleID'))
        batch_op.drop_index(batch_op.f('ix_USER_Email'))

    op.drop_table('USER')
    with op.batch_alter_table('ROLE_PERMISSION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ROLE_PERMISSION_RoleID'))
        batch_op.drop_index(batch_op.f('ix_ROLE_PERMISSION_PermissionID'))

    op.drop_table('ROLE_PERMISSION')
    with op.batch_alter_table('ROLE', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ROLE_Name'))

    op.drop_table('ROLE')
    with op.batch_alter_table('PERMISSION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PERMISSION_Name'))

    op.drop_table('PERMISSION')
    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HOST_STATUS',
    sa.Column('HostStatusID', sa.Integer(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.Column('Hostname', sa.String(length=100), nullable=False),
    sa.Column('Current_State', sa.Enum('UP', 'DOWN', 'UNREACHABLE', name='hoststatetype'), nullable=False),
    sa.Column('Plugin_Status', sa.Enum('OK', 'WARNING', 'CRITICAL', 'UNKNOWN', name='pluginstatustype'), nullable=False),
    sa.Column('Plugin_Output', sa.String(length=255), nullable=False),
    sa.Column('State_Type', sa.Enum('SOFT', 'HARD', name='connectionstatetype'), nullable=False),
    sa.Column('Current_Attempt', sa.Integer(), nullable=False),
    sa.Column('Max_Attempts', sa.Integer(), nullable=False),
    sa.Column('Last_Check', sa.DateTime(), nullable=False),
    sa.Column('Next_Check', sa.DateTime(), nullable=False),
    sa.Column('Last_State_Change', sa.DateTime(), nullable=True),
    sa.Column('Last_Hard_State_Change', sa.DateTime(), nullable=True),
    sa.Column('Last_Time_Up', sa.DateTime(), nullable=True),
    sa.Column('Last_Time_Down', sa.DateTime(), nullable=True),
    sa.Column('Last_Time_Unreachable', sa.DateTime(), nullable=True),
    sa.Column('Check_Latency', sa.Float(precision=6), nullable=False),
    sa.Column('Check_Execution_Time', sa.Float(precision=6), nullable=False),
    sa.Column('Is_Flapping', sa.Boolean(), nullable=False),
    sa.Column('Acknowledgement_Type', sa.Enum('NOACK', 'NORMACK', 'STICKYACK', name='acknowledgementtype'), nullable=False),
    sa.Column('Scheduled_Downtime_Depth', sa.Integer(), nullable=False),
    sa.Column('Notification_Enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('HostStatusID')
    )
    with op.batch_alter_table('HOST_STATUS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_HOST_STATUS_Hostname'), ['Hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_HOST_STATUS_Timestamp'), ['Timestamp'], unique=False)

    op.create_table('PROGRAM_STATUS',
    sa.Column('ProgramStatusID', sa.Integer(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.Column('Version', sa.String(length=20), nullable=True),
    sa.Column('Update_Available', sa.Boolean(), nullable=False),
    sa.Column('New_Version', sa.String(length=20), nullable=True),
    sa.Column('Last_Update_Check', sa.DateTime(), nullable=False),
    sa.Column('NagiosPID', sa.Integer(), nullable=True),
    sa.Column('Enable_Notifications', sa.Boolean(), nullable=False),
    sa.Column('Enable_Flap_Detection', sa.Boolean(), nullable=False),
    sa.Column('Daemon_Mode', sa.Boolean(), nullable=False),
    sa.Column('Program_Start_Time', sa.DateTime(), nullable=False),
    sa.Column('Passive_Host_Checks_Enabled', sa.Boolean(), nullable=False),
    sa.Column('Active_Host_Checks_Enabled', sa.Boolean(), nullable=False),
    sa.Column('Passive_Service_Checks_Enabled', sa.Boolean(), nullable=False),
    sa.Column('Active_Service_Checks_Enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ProgramStatusID')
    )
    with op.batch_alter_table('PROGRAM_STATUS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PROGRAM_STATUS_Timestamp'), ['Timestamp'], unique=False)

    op.create_table('SERVICE_STATUS',
    sa.Column('ServiceStatusID', sa.Integer(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.Column('Hostname', sa.String(length=100), nullable=False),
    sa.Column('Service', sa.String(length=150), nullable=False),
    sa.Column('Current_State', sa.Enum('OK', 'WARNING', 'CRITICAL', 'UNKNOWN', name='servicestatetype'), nullable=False),
    sa.Column('Plugin_Output', sa.String(length=255), nullable=False),
    sa.Column('State_Type', sa.Enum('SOFT', 'HARD', name='connectionstatetype'), nullable=False),
    sa.Column('Last_Time_Ok', sa.DateTime(), nullable=True),
    sa.Column('Last_Time_Warning', sa.DateTime(), nullable=True),
    sa.Column('Last_Time_Critical', sa.DateTime(), nullable=True),
    sa.Column('Last_Time_Unknown', sa.DateTime(), nullable=True),
    sa.Column('Current_Attempt', sa.Integer(), nullable=False),
    sa.Column('Max_Attempts', sa.Integer(), nullable=False),
    sa.Column('Last_Check', sa.DateTime(), nullable=False),
    sa.Column('Next_Check', sa.DateTime(), nullable=False),
    sa.Column('Last_State_Change', sa.DateTime(), nullable=True),
    sa.Column('Last_Hard_State_Change', sa.DateTime(), nullable=True),
    sa.Column('Check_Latency', sa.Float(precision=6), nullable=False),
    sa.Column('Check_Execution_Time', sa.Float(precision=6), nullable=False),
    sa.Column('Notification_Enabled', sa.Boolean(), nullable=False),
    sa.Column('Acknowledgement_Type', sa.Enum('NOACK', 'NORMACK', 'STICKYACK', name='acknowledgementtype'), nullable=False),
    sa.Column('Is_Flapping', sa.Boolean(), nullable=False),
    sa.Column('Scheduled_Downtime_Depth', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ServiceStatusID')
    )
    with op.batch_alter_table('SERVICE_STATUS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SERVICE_STATUS_Hostname'), ['Hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_SERVICE_STATUS_Timestamp'), ['Timestamp'], unique=False)

    op.create_table('HOST_PERF_DATA',
    sa.Column('HostPerfDataID', sa.Integer(), nullable=False),
    sa.Column('Metric', sa.String(length=50), nullable=False),
    sa.Column('Measured_Value', sa.Float(precision=6), nullable=False),
    sa.Column('Unit', sa.String(length=5), nullable=True),
    sa.Column('Warning_Threshold', sa.Float(precision=6), nullable=True),
    sa.Column('Critical_Threshold', sa.Float(precision=6), nullable=True),
    sa.Column('Minimum', sa.Float(precision=6), nullable=True),
    sa.Column('Maximum', sa.Float(precision=6), nullable=True),
    sa.Column('HostStatusID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['HostStatusID'], ['HOST_STATUS.HostStatusID'], ),
    sa.PrimaryKeyConstraint('HostPerfDataID')
    )
    with op.batch_alter_table('HOST_PERF_DATA', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_HOST_PERF_DATA_HostStatusID'), ['HostStatusID'], unique=False)

    op.create_table('SERVICE_PERF_DATA',
    sa.Column('ServicePerfDataID', sa.Integer(), nullable=False),
    sa.Column('Metric', sa.String(length=50), nullable=False),
    sa.Column('Measured_Value', sa.Float(precision=6), nullable=False),
    sa.Column('Unit', sa.String(length=5), nullable=True),
    sa.Column('Warning_Threshold', sa.Float(precision=6), nullable=True),
    sa.Column('Critical_Threshold', sa.Float(precision=6), nullable=True),
    sa.Column('Minimum', sa.Float(precision=6), nullable=True),
    sa.Column('Maximum', sa.Float(precision=6), nullable=True),
    sa.Column('ServiceStatusID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ServiceStatusID'], ['SERVICE_STATUS.ServiceStatusID'], ),
    sa.PrimaryKeyConstraint('ServicePerfDataID')
    )
    with op.batch_alter_table('SERVICE_PERF_DATA', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SERVICE_PERF_DATA_ServiceStatusID'), ['ServiceStatusID'], unique=False)

    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SERVICE_PERF_DATA', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SERVICE_PERF_DATA_ServiceStatusID'))

    op.drop_table('SERVICE_PERF_DATA')
    with op.batch_alter_table('HOST_PERF_DATA', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_HOST_PERF_DATA_HostStatusID'))

    op.drop_table('HOST_PERF_DATA')
    with op.batch_alter_table('SERVICE_STATUS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SERVICE_STATUS_Timestamp'))
        batch_op.drop_index(batch_op.f('ix_SERVICE_STATUS_Hostname'))

    op.drop_table('SERVICE_STATUS')
    with op.batch_alter_table('PROGRAM_STATUS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PROGRAM_STATUS_Timestamp'))

    op.drop_table('PROGRAM_STATUS')
    with op.batch_alter_table('HOST_STATUS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_HOST_STATUS_Timestamp'))
        batch_op.drop_index(batch_op.f('ix_HOST_STATUS_Hostname'))

    op.drop_table('HOST_STATUS')
    # ### end Alembic commands ###

