"""add plugin configuration target and status (Phase 10)

Revision ID: e47789ff90f3
Revises: 4dd5d938ee33
Create Date: 2026-09-22 12:00:00.000000

Hand-written rather than autogenerated: `flask db migrate` refuses to
run while two independent migration chains coexist in this repo (see
`flask db heads` — 4dd5d938ee33 and c99d23ea7ae6, neither descended
from the other, a pre-existing inconsistency unrelated to Plugin
Manager). Attempting `flask db upgrade heads` to resolve it hits a
SEPARATE, also pre-existing bug: one of that other chain's migrations
was written without this project's multidb-aware upgrade(engine_name)
signature, so it can't run against this repo's actual dual-database
(system.db + history.db) setup at all. Both issues belong to whichever
migration chain introduced the "settings" tables, not to Plugin
Manager, so this migration is deliberately written by hand against
our own chain's real head (4dd5d938ee33) instead, following the exact
structure Alembic itself generates elsewhere in this repo.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47789ff90f3'
down_revision = '4dd5d938ee33'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    with op.batch_alter_table('PLUGIN_CONFIGURATION', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Service_Description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column(
            'Status',
            sa.Enum('PENDING', 'APPLIED', 'FAILED', name='pluginconfigurationstatus'),
            nullable=False,
            server_default='PENDING',
        ))
        batch_op.add_column(sa.Column('NetDiscoveryID', sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f('ix_PLUGIN_CONFIGURATION_NetDiscoveryID'), ['NetDiscoveryID'], unique=False,
        )
        batch_op.create_foreign_key(
            'fk_plugin_configuration_net_discovery',
            'NETWORK_DISCOVERY', ['NetDiscoveryID'], ['NetDiscoveryID'],
        )


def downgrade_():
    with op.batch_alter_table('PLUGIN_CONFIGURATION', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plugin_configuration_net_discovery', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_PLUGIN_CONFIGURATION_NetDiscoveryID'))
        batch_op.drop_column('NetDiscoveryID')
        batch_op.drop_column('Status')
        batch_op.drop_column('Service_Description')


def upgrade_history():
    # PLUGIN_CONFIGURATION lives on the default bind — nothing to do here.
    pass


def downgrade_history():
    pass
