"""Changed NCPA to NRPE

Revision ID: e768816b6af1
Revises: c3d581a49635
Create Date: 2026-08-09 12:25:05.333893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e768816b6af1'
down_revision = 'c3d581a49635'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NCPA_DEPLOYMENT',
    sa.Column('NCPAID', sa.Integer(), nullable=False),
    sa.Column('NCPA_Port', sa.Integer(), nullable=False),
    sa.Column('Plugin_Installed', sa.Boolean(), nullable=False),
    sa.Column('Agent_Status', sa.Enum('DISCOVERED', 'PENDING_NRPE', 'MONITORED', 'UNREACHABLE', 'EXCLUDED', name='agentstatus'), nullable=False),
    sa.Column('NetworkDiscoveryID', sa.Integer(), nullable=False),
    sa.Column('DeploymentID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DeploymentID'], ['DEPLOYMENT_HISTORY.DeploymentID'], ),
    sa.ForeignKeyConstraint(['NetworkDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('NCPAID')
    )
    with op.batch_alter_table('NCPA_DEPLOYMENT', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NCPA_DEPLOYMENT_DeploymentID'), ['DeploymentID'], unique=False)
        batch_op.create_index(batch_op.f('ix_NCPA_DEPLOYMENT_NetworkDiscoveryID'), ['NetworkDiscoveryID'], unique=False)

    with op.batch_alter_table('NRPE_DEPLOYMENT', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NRPE_DEPLOYMENT_DeploymentID'))
        batch_op.drop_index(batch_op.f('ix_NRPE_DEPLOYMENT_NetworkDiscoveryID'))

    op.drop_table('NRPE_DEPLOYMENT')
    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NCPA_Eligible', sa.Boolean(), nullable=False))
        batch_op.drop_column('NRPE_Eligible')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NRPE_Eligible', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('NCPA_Eligible')

    op.create_table('NRPE_DEPLOYMENT',
    sa.Column('NRPEID', sa.INTEGER(), nullable=False),
    sa.Column('NRPE_Port', sa.INTEGER(), nullable=False),
    sa.Column('Plugin_Installed', sa.BOOLEAN(), nullable=False),
    sa.Column('Agent_Status', sa.VARCHAR(length=12), nullable=False),
    sa.Column('NetworkDiscoveryID', sa.INTEGER(), nullable=False),
    sa.Column('DeploymentID', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['DeploymentID'], ['DEPLOYMENT_HISTORY.DeploymentID'], ),
    sa.ForeignKeyConstraint(['NetworkDiscoveryID'], ['NETWORK_DISCOVERY.NetDiscoveryID'], ),
    sa.PrimaryKeyConstraint('NRPEID')
    )
    with op.batch_alter_table('NRPE_DEPLOYMENT', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NRPE_DEPLOYMENT_NetworkDiscoveryID'), ['NetworkDiscoveryID'], unique=False)
        batch_op.create_index(batch_op.f('ix_NRPE_DEPLOYMENT_DeploymentID'), ['DeploymentID'], unique=False)

    with op.batch_alter_table('NCPA_DEPLOYMENT', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NCPA_DEPLOYMENT_NetworkDiscoveryID'))
        batch_op.drop_index(batch_op.f('ix_NCPA_DEPLOYMENT_DeploymentID'))

    op.drop_table('NCPA_DEPLOYMENT')
    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

