"""added unique, index and made hostname longer

Revision ID: ec429f135306
Revises: b9c2e137e702
Create Date: 2026-06-18 15:22:48.544212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec429f135306'
down_revision = 'b9c2e137e702'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.alter_column('Hostname',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('PERMISSION', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PERMISSION_Name'), ['Name'], unique=True)

    with op.batch_alter_table('ROLE', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ROLE_Name'), ['Name'], unique=True)

    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_USER_Email'))
        batch_op.create_index(batch_op.f('ix_USER_Email'), ['Email'], unique=True)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_USER_Email'))
        batch_op.create_index(batch_op.f('ix_USER_Email'), ['Email'], unique=False)

    with op.batch_alter_table('ROLE', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ROLE_Name'))

    with op.batch_alter_table('PERMISSION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PERMISSION_Name'))

    with op.batch_alter_table('NETWORK_DISCOVERY', schema=None) as batch_op:
        batch_op.alter_column('Hostname',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)

    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

