"""Fixed typo at Network Discovery Status Table

Revision ID: ed7028ad2a64
Revises: f711a171a49f
Create Date: 2026-08-12 10:34:39.511800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7028ad2a64'
down_revision = 'f711a171a49f'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NETWORK_DISCOVERY_STATUS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Completed_At', sa.DateTime(), nullable=True))
        batch_op.drop_column('Comppleted_At')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NETWORK_DISCOVERY_STATUS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Comppleted_At', sa.DATETIME(), nullable=True))
        batch_op.drop_column('Completed_At')

    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

