"""
monitoring_config.py — Phase 10 (Monitoring Configuration): generates,
validates, and applies Nagios `command`/`service` objects wiring a
Plugin Manager plugin to a specific NetworkDiscovery target device.

Deliberately reuses the EXACT pattern already proven in
network_discovery/create_host_cfg.py (_validate_config/
_apply_new_host_cfg: temp-swap-and-verify, backup-copy-reload-with-
auto-rollback) rather than inventing a new one — same shape, pointed
at PLUGIN_SERVICE_CFG instead of NAGIOS_HOST_CFG.

Confirmed scope decisions (see PHASE_10 summary for the full reasoning):
  - PLUGIN_SERVICE_CFG is a SEPARATE file from NAGIOS_HOST_CFG.
    Network Discovery fully regenerates hosts.cfg from scratch on
    every scan (create_host_cfg.py:406-480) — if Plugin Manager wrote
    services into that same file, they'd be silently wiped out.
    Nagios merges every cfg_file/cfg_dir it's given into one runtime
    model, so a service here can still reference a host_name defined
    entirely in hosts.cfg; splitting files loses nothing.
  - Targets are always an existing NetworkDiscovery device — the only
    source of real Nagios host objects in this codebase.
  - Plugin Manager generates its OWN Nagios `command` object per
    plugin, namespaced as pinpoint_<plugin_name> to avoid colliding
    with stock nagios-plugins command names (e.g. check_tcp) that
    Network Discovery's own command maps already reference directly.
"""
import os
import shutil
import subprocess
import tempfile
from datetime import datetime
from pathlib import Path

from flask import current_app

from app.network_discovery.host_config_templates import create_service

COMMAND_NAME_PREFIX = "pinpoint_"

COMMAND_TEMPLATE = """define command{{
    command_name    {command_name}
    command_line    {command_line}
}}
"""

FILE_HEADER_TEMPLATE = """##########################################################################
#   plugin-services.cfg — generated by PinPoint Plugin Manager
#   generated at {timestamp}
#   DO NOT EDIT BY HAND: this file is fully regenerated on every apply.
##########################################################################
"""


def generate_command_name(plugin_name):
    """pinpoint_<plugin_name> — confirmed namespacing to avoid
    colliding with stock nagios-plugins command definitions."""
    return f"{COMMAND_NAME_PREFIX}{plugin_name}"


def render_command_object(command_name, command_line):
    return COMMAND_TEMPLATE.format(command_name=command_name, command_line=command_line)


def render_service_object(host_name, service_description, command_name, contact_groups="system_users"):
    """Reuses network_discovery's own create_service() template
    directly rather than duplicating it."""
    return create_service(
        {
            "host_name": host_name,
            "service_name": service_description,
            "contact_groups": contact_groups,
        },
        command_name,
    )


def generate_plugin_services_cfg(configurations):
    """
    Builds the FULL contents of plugin-services.cfg from a list of
    (host_name, service_description, command_name, command_line)
    tuples — one full-rebuild pass, matching Network Discovery's own
    established convention for its file (create_host_cfg.py) rather
    than incrementally patching.

    Returns:
        str: the complete file contents.
    """
    lines = [FILE_HEADER_TEMPLATE.format(timestamp=datetime.now().strftime("%d-%m-%Y-%H-%M"))]

    seen_commands = set()
    for host_name, service_description, command_name, command_line in configurations:
        if command_name not in seen_commands:
            lines.append(render_command_object(command_name, command_line))
            lines.append("\n")
            seen_commands.add(command_name)

    for host_name, service_description, command_name, command_line in configurations:
        lines.append(render_service_object(host_name, service_description, command_name))
        lines.append("\n")

    return "".join(lines)


def write_staged_cfg(contents):
    """Writes candidate plugin-services.cfg contents to a fresh
    staging file. Returns the staged path."""
    staging_dir = current_app.config['PLUGIN_SERVICE_STAGING_DIR']
    staging_dir.mkdir(exist_ok=True, parents=True)
    timestamp = datetime.now().strftime("%d-%m-%Y-%H-%M-%S")
    staged_path = staging_dir / f"plugin-services-{timestamp}.cfg"
    staged_path.write_text(contents)
    return staged_path


def _directive_line(cfg_path):
    return f"cfg_file={cfg_path}\n"


def ensure_cfg_file_directive():
    """
    One-time, idempotent bootstrap: adds PLUGIN_SERVICE_CFG's
    cfg_file= line to the REAL nagios.cfg if it isn't already there.
    Without this, Nagios would never load our file at all, even if
    its contents are perfectly valid on their own.

    Backs up nagios.cfg itself first, same auto-rollback-on-failure
    discipline as everywhere else this project touches live Nagios
    state — this is the one Phase 10 operation that modifies
    nagios.cfg, so it gets the same safety net.

    Returns:
        bool: True if the directive was added (or already present),
        False if the add failed and was rolled back.
    """
    NAGIOS_MAIN_CFG = current_app.config['NAGIOS_MAIN_CFG']
    PLUGIN_SERVICE_CFG = current_app.config['PLUGIN_SERVICE_CFG']
    PLUGIN_SERVICE_BACKUP_DIR = current_app.config['PLUGIN_SERVICE_BACKUP_DIR']

    if not NAGIOS_MAIN_CFG.exists():
        return False

    with open(NAGIOS_MAIN_CFG) as f:
        lines = f.readlines()

    already_present = any(
        line.strip().startswith("cfg_file") and str(PLUGIN_SERVICE_CFG) in line
        for line in lines
    )
    if already_present:
        return True

    PLUGIN_SERVICE_BACKUP_DIR.mkdir(exist_ok=True, parents=True)
    timestamp = datetime.now().strftime("%d-%m-%Y-%H-%M-%S")
    backup_path = PLUGIN_SERVICE_BACKUP_DIR / f"nagios-{timestamp}.cfg"
    shutil.copy2(NAGIOS_MAIN_CFG, backup_path)

    try:
        # Ensure our own file exists (even if empty) before Nagios is
        # told to load it — an empty file is valid Nagios config, a
        # missing one is not.
        if not PLUGIN_SERVICE_CFG.exists():
            PLUGIN_SERVICE_CFG.parent.mkdir(exist_ok=True, parents=True)
            PLUGIN_SERVICE_CFG.write_text(
                FILE_HEADER_TEMPLATE.format(timestamp=datetime.now().strftime("%d-%m-%Y-%H-%M"))
            )

        with open(NAGIOS_MAIN_CFG, "a") as f:
            f.write(_directive_line(PLUGIN_SERVICE_CFG))
        return True

    except Exception:
        shutil.copy2(backup_path, NAGIOS_MAIN_CFG)
        return False


def _build_temp_main_cfg_lines(main_cfg_lines, candidate_cfg_path):
    """
    Same swap-or-append logic as Network Discovery's
    _build_temp_cfg_lines, adapted for our own directive: if
    nagios.cfg already references PLUGIN_SERVICE_CFG, swap that line
    to point at the candidate instead; if it doesn't yet (first-ever
    apply, before ensure_cfg_file_directive has run for real), append
    a line pointing at the candidate so validation still reflects
    what WOULD happen once the directive is added for real.
    """
    PLUGIN_SERVICE_CFG = current_app.config['PLUGIN_SERVICE_CFG']
    new_lines = []
    replaced = False
    for line in main_cfg_lines:
        stripped = line.strip()
        if stripped.startswith("cfg_file") and str(PLUGIN_SERVICE_CFG) in stripped:
            new_lines.append(_directive_line(candidate_cfg_path))
            replaced = True
        else:
            new_lines.append(line)

    if not replaced:
        new_lines.append(_directive_line(candidate_cfg_path))

    return new_lines


def validate_plugin_services_config(candidate_path):
    """
    Validates a candidate plugin-services.cfg WITHOUT touching the
    live running config — same shape as Network Discovery's
    _validate_config: swap/append the directive in a throwaway copy
    of nagios.cfg, run `nagios -v` against that, clean up.

    Returns:
        tuple[bool, str]: (is_valid, output)
    """
    NAGIOS_MAIN_CFG = current_app.config['NAGIOS_MAIN_CFG']
    NAGIOS_BIN = current_app.config['NAGIOS_BIN']

    if not NAGIOS_MAIN_CFG.exists():
        return False, f"Nagios main config not found at {NAGIOS_MAIN_CFG}"

    with open(NAGIOS_MAIN_CFG) as f:
        main_cfg_lines = f.readlines()

    temp_lines = _build_temp_main_cfg_lines(main_cfg_lines, candidate_path)

    with tempfile.NamedTemporaryFile(mode="w", suffix=".cfg", delete=False) as f:
        f.writelines(temp_lines)
        temp_cfg_path = Path(f.name)

    try:
        result = subprocess.run(
            [str(NAGIOS_BIN), "-v", str(temp_cfg_path)],
            capture_output=True, text=True, timeout=60,
        )
        return result.returncode == 0, result.stdout + result.stderr
    except subprocess.TimeoutExpired:
        return False, "Nagios validation timed out."
    except FileNotFoundError:
        return False, f"Nagios binary not found at {NAGIOS_BIN}."
    finally:
        temp_cfg_path.unlink(missing_ok=True)


def apply_plugin_services_config(candidate_path):
    """
    Applies a validated candidate plugin-services.cfg as the new live
    file — same shape as Network Discovery's _apply_new_host_cfg:
    backup the current live file, copy the candidate into place,
    reload Nagios, auto-rollback if the reload fails.

    IMPORTANT: assumes candidate_path has ALREADY been validated via
    validate_plugin_services_config(). Does not re-validate.

    Returns:
        tuple[bool, str]: (success, message)
    """
    PLUGIN_SERVICE_CFG = current_app.config['PLUGIN_SERVICE_CFG']
    PLUGIN_SERVICE_BACKUP_DIR = current_app.config['PLUGIN_SERVICE_BACKUP_DIR']

    PLUGIN_SERVICE_BACKUP_DIR.mkdir(exist_ok=True, parents=True)
    timestamp = datetime.now().strftime("%d-%m-%Y-%H-%M-%S")
    backup_path = PLUGIN_SERVICE_BACKUP_DIR / f"plugin-services-{timestamp}.cfg"

    try:
        if PLUGIN_SERVICE_CFG.exists():
            shutil.copy2(PLUGIN_SERVICE_CFG, backup_path)
    except Exception as e:
        return False, f"Failed to back up current config, aborting apply: {e}"

    try:
        PLUGIN_SERVICE_CFG.parent.mkdir(exist_ok=True, parents=True)
        shutil.copy2(candidate_path, PLUGIN_SERVICE_CFG)
    except Exception as e:
        return False, f"Failed to copy new config into place: {e}"

    try:
        result = subprocess.run(
            ["sudo", "-n", "systemctl", "reload", "nagios"],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode != 0:
            current_app.logger.error(result.stdout + result.stderr)
    except Exception as e:
        if backup_path.exists():
            shutil.copy2(backup_path, PLUGIN_SERVICE_CFG)
        return False, (
            f"Failed to reload Nagios after applying new config. "
            f"Rolled back to backup at {backup_path}. Error: {e}"
        )

    return True, f"Applied {candidate_path} successfully. Backup stored at {backup_path}"
