PLUGIN_DESCRIPTIONS = {
    "check_apt": "Checks a Debian/Ubuntu server for pending package updates and flags security updates.",
    "check_breeze": "Reads the signal strength of Breezecom wireless equipment over SNMP.",
    "check_by_ssh": "Runs a check command on a remote machine over SSH and reports its result.",
    "check_cluster": "Combines the states of several hosts or services into one cluster status.",
    "check_dbi": "Connects to a database through the generic DBI layer and checks a query result.",
    "check_dhcp": "Tests whether a DHCP server answers requests on the network.",
    "check_dig": "Looks up a DNS record with dig and checks the answer and response time.",
    "check_disk": "Checks free disk space and inodes on a local filesystem.",
    "check_disk_smb": "Checks free space on a Windows/SMB network share.",
    "check_dns": "Checks that a DNS server resolves a name and how fast it responds.",
    "check_dummy": "Returns a fixed status and message; used for testing and passive checks.",
    "check_file_age": "Checks how old a file is and, optionally, how large it is.",
    "check_flexlm": "Checks the status of a FlexLM license server.",
    "check_fping": "Pings a host quickly with fping and reports packet loss and round-trip time.",
    "check_game": "Checks whether a game server is up and how many players it has.",
    "check_hpjd": "Reads the status of an HP JetDirect printer over SNMP (paper, toner, errors).",
    "check_http": "Checks a web server over HTTP or HTTPS: response, status code, content and certificate expiry.",
    "check_icmp": "Pings one or more hosts with ICMP and reports packet loss and round-trip time.",
    "check_ide_smart": "Checks the S.M.A.R.T. health of an IDE/ATA disk.",
    "check_ifoperstatus": "Checks whether one network interface is up, using SNMP.",
    "check_ifstatus": "Checks all network interfaces of a device over SNMP and counts those that are down.",
    "check_ircd": "Checks an IRC server and the number of users connected to it.",
    "check_ldap": "Connects to an LDAP server and checks that a search works.",
    "check_ldaps": "Connects to an LDAP server over SSL/TLS and checks that a search works.",
    "check_load": "Checks the system load averages of the local machine.",
    "check_log": "Scans a log file for a text pattern and reports new matches since the last run.",
    "check_mailq": "Checks how many messages are waiting in the local mail queue.",
    "check_mrtg": "Checks a value recorded in an MRTG log file against thresholds.",
    "check_mrtgtraf": "Checks network traffic recorded in an MRTG log file.",
    "check_mysql": "Connects to a MySQL/MariaDB server and checks that it responds.",
    "check_mysql_query": "Runs an SQL query on a MySQL/MariaDB server and checks the result.",
    "check_nagios": "Checks that the Nagios process is running and its status log is recent.",
    "check_ncpa": "Reads CPU, memory, disk, network and process metrics from a device running the NCPA agent.",
    "check_nt": "Checks a Windows machine through the NSClient service (CPU, memory, disk, services).",
    "check_ntp": "Checks a machine's clock against an NTP server (offset and jitter).",
    "check_ntp_peer": "Checks the health of an NTP server as a time source.",
    "check_ntp_time": "Checks how far a machine's clock differs from an NTP server.",
    "check_nwstat": "Checks statistics of a Novell NetWare server.",
    "check_oracle": "Checks the status of an Oracle database.",
    "check_overcr": "Checks an Over-CR collector daemon.",
    "check_pgsql": "Connects to a PostgreSQL server and checks that it responds.",
    "check_ping": "Pings a host and reports packet loss and round-trip time.",
    "check_procs": "Counts running processes and checks them against thresholds.",
    "check_radius": "Tests that a RADIUS server accepts an authentication request.",
    "check_real": "Checks a RealMedia/RTSP streaming server.",
    "check_rpc": "Checks that an RPC program is registered and available on a host.",
    "check_sensors": "Reads hardware sensors (temperature, fans, voltage) through lm_sensors.",
    "check_smtp": "Connects to a mail server over SMTP and checks the response.",
    "check_snmp": "Reads a value from a device over SNMP and checks it against thresholds.",
    "check_ssh": "Checks that an SSH server accepts connections.",
    "check_ssl_validity": "Checks an SSL/TLS certificate: validity, expiry date and revocation.",
    "check_swap": "Checks swap space usage on the local machine.",
    "check_tcp": "Checks that a TCP port accepts connections and how fast it answers.",
    "check_time": "Checks the time difference between this server and a remote host.",
    "check_ups": "Reads the status of a UPS (battery, load, power) through Network UPS Tools.",
    "check_uptime": "Checks how long the local machine has been running.",
    "check_users": "Counts the users logged in to the local machine.",
    "check_wave": "Reads the signal strength of WaveLAN/Intersil wireless devices over SNMP.",
}


def get_default_description(plugin_name):
    return PLUGIN_DESCRIPTIONS.get(plugin_name)
