"""
plugin_catalog_data.py - Descriptions, categories and documentation links for
the bundled nagios-plugins 2.4.12 set.

GENERATED by server/scripts/build_plugin_descriptions.py. Do not edit by hand;
change the script's inputs and re-run it. Lookup helpers live in
plugin_descriptions.py.
"""

PLUGIN_CATALOG = {
    'check_apt': {
        'description': 'Check for available package updates (Debian/Ubuntu).',
        'category': 'System',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_apt.html',
    },
    'check_breeze': {
        'description': 'Check Breezecom wireless equipment signal strength via SNMP.',
        'category': 'SNMP & Devices',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_breeze.html',
    },
    'check_by_ssh': {
        'description': 'Execute remote commands via SSH.',
        'category': 'Network Services',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_by_ssh.html',
    },
    'check_cluster': {
        'description': 'Aggregate host/service cluster status.',
        'category': 'Utility',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_cluster.html',
    },
    'check_dbi': {
        'description': 'Database-independent checks via DBI.',
        'category': 'Database',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_dbi.html',
    },
    'check_dhcp': {
        'description': 'Test DHCP server availability.',
        'category': 'Connectivity',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_dhcp.html',
    },
    'check_dig': {
        'description': 'DNS lookup using dig command.',
        'category': 'DNS & Time',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_dig.html',
    },
    'check_disk': {
        'description': 'Check disk space and inode usage.',
        'category': 'Storage',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_disk.html',
    },
    'check_disk_smb': {
        'description': 'Check disk space on SMB/CIFS shares via smbclient.',
        'category': 'Storage',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_disk_smb.html',
    },
    'check_dns': {
        'description': 'Check DNS server response.',
        'category': 'DNS & Time',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_dns.html',
    },
    'check_dummy': {
        'description': 'Return a specified state with message.',
        'category': 'Utility',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_dummy.html',
    },
    'check_file_age': {
        'description': 'Check age and/or size of a file.',
        'category': 'System',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_file_age.html',
    },
    'check_flexlm': {
        'description': 'Check FlexLM license server status via lmstat.',
        'category': 'Utility',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_flexlm.html',
    },
    'check_fping': {
        'description': 'Fast ping using fping.',
        'category': 'Connectivity',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_fping.html',
    },
    'check_ftp': {
        'description': 'Test FTP connections with the specified host (or unix socket).',
        'category': 'Network Services',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_ftp.html',
    },
    'check_game': {
        'description': 'Check game server status via qstat.',
        'category': 'Network Services',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_game.html',
    },
    'check_hpjd': {
        'description': 'Check HP JetDirect printer status via SNMP.',
        'category': 'SNMP & Devices',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_hpjd.html',
    },
    'check_http': {
        'description': 'Check HTTP/HTTPS web server.',
        'category': 'Web',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_http.html',
    },
    'check_icmp': {
        'description': 'ICMP ping with high precision.',
        'category': 'Connectivity',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_icmp.html',
    },
    'check_ide_smart': {
        'description': 'Check IDE/S.M.A.R.T. disk health.',
        'category': 'Hardware',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_ide_smart.html',
    },
    'check_ifoperstatus': {
        'description': 'Check individual SNMP interface operational status.',
        'category': 'SNMP & Devices',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_ifoperstatus.html',
    },
    'check_ifstatus': {
        'description': 'Check bulk SNMP interface status (up/down counts).',
        'category': 'SNMP & Devices',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_ifstatus.html',
    },
    'check_ircd': {
        'description': 'Check IRC daemon user count.',
        'category': 'Network Services',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_ircd.html',
    },
    'check_ldap': {
        'description': 'Check LDAP server connection and search.',
        'category': 'Network Services',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_ldap.html',
    },
    'check_ldaps': {
        'description': 'Check LDAP server connection and search.',
        'category': 'Network Services',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_ldap.html',
    },
    'check_load': {
        'description': 'Check system load averages.',
        'category': 'System',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_load.html',
    },
    'check_log': {
        'description': 'Scan log files for pattern matches (stateful — tracks previous runs).',
        'category': 'System',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_log.html',
    },
    'check_mailq': {
        'description': 'Check mail queue length for multiple MTA backends.',
        'category': 'Mail',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_mailq.html',
    },
    'check_mrtg': {
        'description': 'Check MRTG log file values.',
        'category': 'SNMP & Devices',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_mrtg.html',
    },
    'check_mrtgtraf': {
        'description': 'Check MRTG traffic log files.',
        'category': 'SNMP & Devices',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_mrtgtraf.html',
    },
    'check_mysql': {
        'description': 'Check MySQL server connection and status.',
        'category': 'Database',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_mysql.html',
    },
    'check_mysql_query': {
        'description': 'Run arbitrary SQL and check result.',
        'category': 'Database',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_mysql_query.html',
    },
    'check_nagios': {
        'description': 'Check Nagios process and status log freshness.',
        'category': 'System',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_nagios.html',
    },
    'check_ncpa': {
        'description': 'Check metrics via NCPA (Nagios Cross-Platform Agent) API.',
        'category': 'Agents',
        'documentation_url': 'https://www.nagios.org/ncpa/',
    },
    'check_nt': {
        'description': 'Check Windows NT/2000/XP/2003 server via NSClient.',
        'category': 'Agents',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_nt.html',
    },
    'check_ntp': {
        'description': 'Check NTP time offset and jitter via ntpdate + ntpq. The older C build is deprecated; prefer check_ntp_time or check_ntp_peer.',
        'category': 'DNS & Time',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_ntp.html',
    },
    'check_ntp_peer': {
        'description': 'Check NTP server peer health.',
        'category': 'DNS & Time',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_ntp_peer.html',
    },
    'check_ntp_time': {
        'description': 'Check NTP time offset.',
        'category': 'DNS & Time',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_ntp_time.html',
    },
    'check_nwstat': {
        'description': 'Check Novell NetWare server statistics.',
        'category': 'Agents',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_nwstat.html',
    },
    'check_oracle': {
        'description': 'Check Oracle database status via multiple methods.',
        'category': 'Database',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_oracle.html',
    },
    'check_overcr': {
        'description': 'Check Over-CR collector daemon.',
        'category': 'Agents',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_overcr.html',
    },
    'check_pgsql': {
        'description': 'Check PostgreSQL database connection.',
        'category': 'Database',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_pgsql.html',
    },
    'check_ping': {
        'description': 'Ping host and measure response time.',
        'category': 'Connectivity',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_ping.html',
    },
    'check_procs': {
        'description': 'Check process count and resources.',
        'category': 'System',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_procs.html',
    },
    'check_radius': {
        'description': 'Test RADIUS server authentication.',
        'category': 'Network Services',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_radius.html',
    },
    'check_real': {
        'description': 'Check REAL/RTSP streaming server.',
        'category': 'Network Services',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_real.html',
    },
    'check_rpc': {
        'description': 'Check RPC program availability via rpcinfo.',
        'category': 'Network Services',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_rpc.html',
    },
    'check_sensors': {
        'description': 'Check hardware sensor status via lm_sensors.',
        'category': 'Hardware',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_sensors.html',
    },
    'check_smtp': {
        'description': 'Check SMTP server connection.',
        'category': 'Mail',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_smtp.html',
    },
    'check_snmp': {
        'description': 'Check remote machines via SNMP.',
        'category': 'SNMP & Devices',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_snmp.html',
    },
    'check_ssh': {
        'description': 'Check SSH server connection.',
        'category': 'Network Services',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_ssh.html',
    },
    'check_ssl_validity': {
        'description': 'Check SSL certificate validity, expiration, and revocation.',
        'category': 'Web',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_ssl_validity.html',
    },
    'check_swap': {
        'description': 'Check swap space usage.',
        'category': 'System',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_swap.html',
    },
    'check_tcp': {
        'description': 'Check TCP port connectivity.',
        'category': 'Connectivity',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_tcp.html',
    },
    'check_time': {
        'description': 'Check time difference with remote host.',
        'category': 'DNS & Time',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_time.html',
    },
    'check_udp': {
        'description': 'Test UDP connections with the specified host (or unix socket).',
        'category': 'Connectivity',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_udp.html',
    },
    'check_ups': {
        'description': 'Check UPS status via NUT (Network UPS Tools).',
        'category': 'Hardware',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_ups.html',
    },
    'check_uptime': {
        'description': 'Check system uptime.',
        'category': 'System',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_uptime.html',
    },
    'check_users': {
        'description': 'Check number of logged-in users.',
        'category': 'System',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_users.html',
    },
    'check_wave': {
        'description': 'Check wireless signal strength via SNMP (WaveLAN/Intersil).',
        'category': 'SNMP & Devices',
        'documentation_url': 'https://www.nagios-plugins.org/doc/man/check_wave.html',
    },
}
