"""
statistics.py — Shared aggregation helpers for the dashboard and network health routes.

These are plain functions, not Flask routes. They query the history database
and return plain Python dicts/lists that the route handlers serialize into JSON.

Sections covered:
  - latest_snapshot()           : most-recent HostStatus + ServiceStatus rows per entity
  - host_counts()               : UP/DOWN/UNREACHABLE breakdown
  - service_counts()            : OK/WARNING/CRITICAL/UNKNOWN breakdown
  - active_alerts()             : hosts and services currently in a problem state
  - avg_ping_metrics()          : network-wide average RTA and packet loss (§1.3, §2.4)
  - ncpa_averages()             : network-wide NCPA CPU/disk/memory averages (§1.4, §2.4)
  - service_health_by_plugin()  : per-plugin state breakdown (§2.5)
  - perf_trends()               : time-bucketed performance data for trend charts (§2.4)
  - nagios_server_resources()   : check_load / check_disk / check_swap for localhost (§1.1, §2.4)
"""

from __future__ import annotations

import json
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

import sqlalchemy as sa

from app import db
from app.history_models import (
    HostStatus,
    HostPerfData,
    ServiceStatus,
    ServicePerfData,
    HostStateType,
    ServiceStateType,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Hostname of the Nagios server itself — its own resource checks
# (check_load, check_disk, check_swap) appear under this hostname.
NAGIOS_HOST = "localhost"

# Plugins whose perf data counts as NCPA resource metrics.
NCPA_PLUGIN_PREFIX = "check_ncpa"

# Plugins that report RTA / packet loss.
PING_PLUGINS = {"check_ping", "check_icmp", "check_fping"}

# Nagios server local resource plugins.
LOAD_PLUGIN  = "check_load"
DISK_PLUGIN  = "check_disk"
SWAP_PLUGIN  = "check_swap"

# Combined TCP + UDP command map used by _plugin_key() to resolve a bare
# service name prefix to its check command.  Loaded once at import time from
# the same JSON files that create_host_cfg.py uses, so there is a single
# source of truth for service-name → plugin mappings.
_MAP_DIR = Path(__file__).resolve().parents[2] / "network_discovery" / "command_maps"

def _load_command_map() -> dict[str, str]:
    """Load and merge tcp_commands.json and udp_commands.json into one dict."""
    merged: dict[str, str] = {}
    for fname in ("tcp_commands.json", "udp_commands.json"):
        path = _MAP_DIR / fname
        if path.exists():
            with open(path) as f:
                merged.update(json.load(f))
    return merged

_COMMAND_MAP: dict[str, str] = _load_command_map()




# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _latest_host_subquery():
    """Subquery that returns the most recent Timestamp per Hostname."""
    return (
        sa.select(
            HostStatus.Hostname,
            sa.func.max(HostStatus.Timestamp).label("max_ts"),
        )
        .group_by(HostStatus.Hostname)
        .subquery()
    )


def _latest_service_subquery():
    """Subquery that returns the most recent Timestamp per (Hostname, Service)."""
    return (
        sa.select(
            ServiceStatus.Hostname,
            ServiceStatus.Service,
            sa.func.max(ServiceStatus.Timestamp).label("max_ts"),
        )
        .group_by(ServiceStatus.Hostname, ServiceStatus.Service)
        .subquery()
    )


def _plugin_key(service_name: str) -> str:
    """
    Resolve a Nagios service_description to its check plugin command name.

    Service descriptions follow the format {service_name}-{port}-{protocol},
    as generated by create_host_cfg.py. The bare service name is extracted by
    splitting on '-' first, then on '_' to drop any qualifier suffix:

        "http-80-TCP"                →  prefix "http"
        "ncpa-5693-TCP"              →  prefix "ncpa"
        "ncpa_cpu_usage-5693-TCP"    →  prefix "ncpa"   (dash-prefix = "ncpa_cpu_usage", then split on '_')
        "ncpa_memory_usage-5693-TCP" →  prefix "ncpa"
        "ncpa_disk_usage-5693-TCP"   →  prefix "ncpa"

    The extracted prefix is looked up in the combined TCP+UDP command map
    (command_maps/tcp_commands.json + udp_commands.json).  If a match is
    found the mapped command string is returned (e.g. "check_ncpa").

    Disk-per-partition services from create_host_cfg.py take the form
    "ncpa-{port}-TCP-disk_usage_{partition}" — the dash-split prefix is
    still "ncpa", which maps correctly.

    Falls back to "check_{prefix}" for any service not in the map so that
    unknown services are still grouped sensibly rather than silently dropped.
    """
    dash_prefix = service_name.split("-")[0].lower().strip()
    prefix = dash_prefix.split("_")[0]
    return _COMMAND_MAP.get(dash_prefix) or _COMMAND_MAP.get(prefix) or f"check_{prefix}"


def _display_name(plugin_key: str) -> str:
    """
    Derive the display name for a plugin key shown in the Service Health by
    Plugin Type section (§2.5).

    Strip the 'check_' prefix and uppercase the result.
    Examples:
        check_http  → HTTP
        check_ncpa  → NCPA
        check_ping  → PING
        http        → HTTP   (bare prefix, no check_ to strip)
    """
    if plugin_key.startswith("check_"):
        return plugin_key[len("check_"):].upper()
    return plugin_key.upper()


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------

def get_latest_hosts() -> list[HostStatus]:
    """
    Return one HostStatus row per hostname (the most recent snapshot).
    """
    subq = _latest_host_subquery()
    return db.session.scalars(
        sa.select(HostStatus).join(
            subq,
            sa.and_(
                HostStatus.Hostname == subq.c.Hostname,
                HostStatus.Timestamp == subq.c.max_ts,
            ),
        )
    ).all()


def get_latest_services() -> list[ServiceStatus]:
    """
    Return one ServiceStatus row per (hostname, service) pair (most recent snapshot).
    """
    subq = _latest_service_subquery()
    return db.session.scalars(
        sa.select(ServiceStatus).join(
            subq,
            sa.and_(
                ServiceStatus.Hostname == subq.c.Hostname,
                ServiceStatus.Service  == subq.c.Service,
                ServiceStatus.Timestamp == subq.c.max_ts,
            ),
        )
    ).all()


def host_counts(hosts: list[HostStatus]) -> dict:
    """
    Return a dict with total and per-state counts for a list of latest hosts.

    Shape:
        { "total": int, "up": int, "down": int, "unreachable": int,
          "flapping": int, "in_downtime": int }
    """
    counts = {s: 0 for s in HostStateType}
    flapping = 0
    in_downtime = 0

    for h in hosts:
        counts[h.Current_State] += 1
        if h.Is_Flapping:
            flapping += 1
        if h.Scheduled_Downtime_Depth > 0:
            in_downtime += 1

    return {
        "total":       len(hosts),
        "up":          counts[HostStateType.UP],
        "down":        counts[HostStateType.DOWN],
        "unreachable": counts[HostStateType.UNREACHABLE],
        "flapping":    flapping,
        "in_downtime": in_downtime,
    }


def service_counts(services: list[ServiceStatus]) -> dict:
    """
    Return a dict with total and per-state counts for a list of latest services.

    Shape:
        { "total": int, "ok": int, "warning": int, "critical": int,
          "unknown": int, "flapping": int, "in_downtime": int }
    """
    counts = {s: 0 for s in ServiceStateType}
    flapping = 0
    in_downtime = 0

    for s in services:
        counts[s.Current_State] += 1
        if s.Is_Flapping:
            flapping += 1
        if s.Scheduled_Downtime_Depth > 0:
            in_downtime += 1

    return {
        "total":     len(services),
        "ok":        counts[ServiceStateType.OK],
        "warning":   counts[ServiceStateType.WARNING],
        "critical":  counts[ServiceStateType.CRITICAL],
        "unknown":   counts[ServiceStateType.UNKNOWN],
        "flapping":  flapping,
        "in_downtime": in_downtime,
    }


def active_alert_count(hosts: list[HostStatus], services: list[ServiceStatus]) -> dict:
    """
    Count all entities currently in a problem state.

    Shape:
        { "total": int, "critical": int, "warning": int, "unknown": int }

    Host DOWN/UNREACHABLE states are counted under "critical" since they
    represent the most severe reachability problem.
    """
    critical = sum(
        1 for h in hosts
        if h.Current_State in (HostStateType.DOWN, HostStateType.UNREACHABLE)
    )
    warning = sum(
        1 for s in services if s.Current_State == ServiceStateType.WARNING
    )
    svc_critical = sum(
        1 for s in services if s.Current_State == ServiceStateType.CRITICAL
    )
    unknown = sum(
        1 for s in services if s.Current_State == ServiceStateType.UNKNOWN
    )
    critical += svc_critical

    return {
        "total":    critical + warning + unknown,
        "critical": critical,
        "warning":  warning,
        "unknown":  unknown,
    }


def avg_ping_metrics(hosts: list[HostStatus]) -> dict:
    """
    Compute network-wide average RTA (ms) and packet loss (%) from the latest
    host check perf data (§1.3, §2.4).

    check_ping runs as the host check in this system — its rta and pl metrics
    land in HostPerfData, not ServicePerfData. We query the HostPerfData rows
    linked to the latest HostStatus snapshot per host.

    Returns:
        {
            "configured": bool,
            "avg_rta_ms": float | None,
            "avg_packet_loss_pct": float | None,
            "host_count": int,
        }
    """
    host_ids = [h.HostStatusID for h in hosts]

    if not host_ids:
        return {"configured": False, "avg_rta_ms": None,
                "avg_packet_loss_pct": None, "host_count": 0}

    rows = db.session.execute(
        sa.select(
            HostPerfData.HostStatusID,
            HostPerfData.Metric,
            HostPerfData.Measured_Value,
        ).where(
            HostPerfData.HostStatusID.in_(host_ids),
            HostPerfData.Metric.in_(["rta", "pl"]),
        )
    ).all()

    rta_by_host: dict[int, float] = {}
    pl_by_host:  dict[int, float] = {}

    for row in rows:
        if row.Metric == "rta":
            rta_by_host[row.HostStatusID] = row.Measured_Value
        elif row.Metric == "pl":
            pl_by_host[row.HostStatusID] = row.Measured_Value

    rta_vals = list(rta_by_host.values())
    pl_vals  = list(pl_by_host.values())
    host_count = max(len(rta_vals), len(pl_vals))

    if host_count == 0:
        return {"configured": False, "avg_rta_ms": None,
                "avg_packet_loss_pct": None, "host_count": 0}

    if host_count < 2:
        return {"configured": True, "avg_rta_ms": None,
                "avg_packet_loss_pct": None, "host_count": host_count,
                "insufficient_data": True}

    avg_rta = round(sum(rta_vals) / len(rta_vals), 3) if rta_vals else None
    avg_pl  = round(sum(pl_vals)  / len(pl_vals),  3) if pl_vals  else None

    return {
        "configured":          True,
        "avg_rta_ms":          avg_rta,
        "avg_packet_loss_pct": avg_pl,
        "host_count":          host_count,
    }


def ncpa_averages(
    services: list[ServiceStatus],
    hosts: list[HostStatus],
) -> dict | None:
    """
    Compute network-wide NCPA resource averages (CPU, disk, memory) across all
    hosts with check_ncpa services (§1.4, §2.4).

    Uses the perf data linked to the latest ServiceStatus snapshot per service,
    so results always reflect the most recent check cycle only.

    Returns None when no NCPA services exist at all (conditional section —
    hide the UI block entirely).

    Returns:
        {
            "ncpa_host_count": int,
            "total_host_count": int,
            "avg_cpu_pct": float | None,
            "avg_disk_pct": float | None,
            "avg_memory_pct": float | None,
        }
    """
    ncpa_svcs = [s for s in services if _plugin_key(s.Service) == "check_ncpa"]

    if not ncpa_svcs:
        return None

    ncpa_ids = [s.ServiceStatusID for s in ncpa_svcs]

    rows = db.session.execute(
        sa.select(
            ServicePerfData.Metric,
            ServicePerfData.Measured_Value,
        ).where(
            ServicePerfData.ServiceStatusID.in_(ncpa_ids),
        )
    ).all()

    cpu_vals:  list[float] = []
    disk_vals: list[float] = []
    mem_vals:  list[float] = []

    for row in rows:
        metric = row.Metric.lower()
        val    = row.Measured_Value
        # cpu/percent
        if "cpu" in metric and "percent" in metric:
            cpu_vals.append(val)
        # disk/logical/.../used_percent
        elif "disk" in metric and ("used_percent" in metric or "percent" in metric):
            disk_vals.append(val)
        # memory/virtual/percent
        elif "memory" in metric and "percent" in metric:
            mem_vals.append(val)

    def _safe_avg(vals: list[float]) -> Optional[float]:
        if len(vals) < 2:
            return None
        return round(sum(vals) / len(vals), 2)

    ncpa_hostnames = {s.Hostname for s in ncpa_svcs}

    return {
        "ncpa_host_count":  len(ncpa_hostnames),
        "total_host_count": len(hosts),
        "avg_cpu_pct":      _safe_avg(cpu_vals),
        "avg_disk_pct":     _safe_avg(disk_vals),
        "avg_memory_pct":   _safe_avg(mem_vals),
    }


def nagios_server_resources(services: list[ServiceStatus]) -> dict:
    """
    Extract the latest check_load / check_disk / check_swap metrics for the
    Nagios server itself (hostname = NAGIOS_HOST) (§1.1, §2.4).

    Uses the perf data linked to the latest ServiceStatus snapshot per service,
    so results always reflect the most recent check cycle only.

    Always returns a result — missing plugins are represented with
    "configured: False" so the UI can show a "plugin not configured" message.

    Returns:
        {
            "cpu_load": {
                "configured": bool,
                "load1": float | None,
                "load5": float | None,
                "load15": float | None,
            },
            "disk": {
                "configured": bool,
                "mounts": [ { "mount": str, "used_bytes": float,
                              "warn": float | None, "crit": float | None } ]
            },
            "swap": {
                "configured": bool,
                "swap_used_mb": float | None,
                "warn": float | None,
                "crit": float | None,
            },
        }
    """
    # Filter to only services on the Nagios host.
    nagios_svcs = {s.Service: s for s in services if s.Hostname == NAGIOS_HOST}

    # ── check_load ──────────────────────────────────────────────────────────
    load_svc = next(
        (s for name, s in nagios_svcs.items() if _plugin_key(name) == LOAD_PLUGIN),
        None,
    )
    cpu_load: dict = {"configured": False, "load1": None, "load5": None, "load15": None}

    if load_svc:
        perf = db.session.execute(
            sa.select(ServicePerfData).where(
                ServicePerfData.ServiceStatusID == load_svc.ServiceStatusID
            )
        ).scalars().all()

        cpu_load["configured"] = True
        for p in perf:
            if p.Metric == "load1":
                cpu_load["load1"] = p.Measured_Value
            elif p.Metric == "load5":
                cpu_load["load5"] = p.Measured_Value
            elif p.Metric == "load15":
                cpu_load["load15"] = p.Measured_Value

    # ── check_disk ──────────────────────────────────────────────────────────
    disk_svc = next(
        (s for name, s in nagios_svcs.items() if _plugin_key(name) == DISK_PLUGIN),
        None,
    )
    disk: dict = {"configured": False, "mounts": []}

    if disk_svc:
        perf = db.session.execute(
            sa.select(ServicePerfData).where(
                ServicePerfData.ServiceStatusID == disk_svc.ServiceStatusID
            )
        ).scalars().all()

        disk["configured"] = True
        for p in perf:
            # Disk metric keys look like "/", "/boot", "/home", etc.
            if p.Metric.startswith("/") and "inode" not in p.Metric:
                disk["mounts"].append({
                    "mount":      p.Metric,
                    "used_bytes": p.Measured_Value,
                    "warn":       p.Warning_Threshold,
                    "crit":       p.Critical_Threshold,
                })

    # ── check_swap ──────────────────────────────────────────────────────────
    swap_svc = next(
        (s for name, s in nagios_svcs.items() if _plugin_key(name) == SWAP_PLUGIN),
        None,
    )
    swap: dict = {"configured": False, "swap_used_mb": None, "warn": None, "crit": None}

    if swap_svc:
        perf = db.session.execute(
            sa.select(ServicePerfData).where(
                ServicePerfData.ServiceStatusID == swap_svc.ServiceStatusID
            )
        ).scalars().all()

        swap["configured"] = True
        for p in perf:
            if p.Metric == "swap":
                swap["swap_used_mb"] = p.Measured_Value
                swap["warn"] = p.Warning_Threshold
                swap["crit"] = p.Critical_Threshold

    return {"cpu_load": cpu_load, "disk": disk, "swap": swap}


def service_health_by_plugin(services: list[ServiceStatus]) -> list[dict]:
    """
    Group all latest services by plugin type and produce a state breakdown (§2.5).

    Returns a list sorted by worst severity first (groups with CRITICAL services
    before WARNING, before all-OK).

    Each entry:
        {
            "display_name":  str,   # e.g. "HTTP", "NCPA", "PING"
            "total":         int,
            "ok":            int,
            "warning":       int,
            "critical":      int,
            "unknown":       int,
            "worst_state":   str,   # "ok" | "warning" | "critical" | "unknown"
        }
    """
    groups: dict[str, dict] = {}

    for svc in services:
        key = _plugin_key(svc.Service)
        if key not in groups:
            groups[key] = {
                "display_name": _display_name(key),
                "total":        0,
                "ok":           0,
                "warning":      0,
                "critical":     0,
                "unknown":      0,
            }
        g = groups[key]
        g["total"] += 1
        state = svc.Current_State
        if state == ServiceStateType.OK:
            g["ok"] += 1
        elif state == ServiceStateType.WARNING:
            g["warning"] += 1
        elif state == ServiceStateType.CRITICAL:
            g["critical"] += 1
        else:
            g["unknown"] += 1

    def _worst(g: dict) -> int:
        if g["critical"] > 0:
            return 0
        if g["warning"] > 0:
            return 1
        if g["unknown"] > 0:
            return 2
        return 3

    _worst_label = {0: "critical", 1: "warning", 2: "unknown", 3: "ok"}

    result = list(groups.values())
    for g in result:
        g["worst_state"] = _worst_label[_worst(g)]

    result.sort(key=_worst)
    return result


def perf_trends(
    hostname: Optional[str],
    service_name: Optional[str],
    metric_names: list[str],
    hours: int = 24,
    buckets: int = 24,
) -> list[dict]:
    """
    Return time-bucketed average performance data for a given host/service/metric
    combination over the last `hours` hours, divided into `buckets` buckets (§2.4).

    If `hostname` is None, aggregates across all hosts (network-wide).
    If `service_name` is None, aggregates across all services on that host.

    Each bucket:
        {
            "bucket_start": str (ISO-8601),
            "metric":       str,
            "avg_value":    float | None,   # None = no data in this bucket
            "unit":         str | None,
        }
    """
    now  = datetime.now(timezone.utc)
    start = now - timedelta(hours=hours)
    bucket_size = timedelta(hours=hours) / buckets

    # Build the service subquery to limit to the right host/service.
    svc_query = sa.select(ServiceStatus.ServiceStatusID).where(
        ServiceStatus.Timestamp >= start
    )
    if hostname:
        svc_query = svc_query.where(ServiceStatus.Hostname == hostname)
    if service_name:
        svc_query = svc_query.where(ServiceStatus.Service == service_name)
    svc_ids = db.session.scalars(svc_query).all()

    if not svc_ids:
        return []

    # Fetch all relevant perf data rows in the time window.
    perf_rows = db.session.execute(
        sa.select(
            ServicePerfData.Metric,
            ServicePerfData.Measured_Value,
            ServicePerfData.Unit,
            ServiceStatus.Timestamp,
        )
        .join(ServiceStatus, ServicePerfData.ServiceStatusID == ServiceStatus.ServiceStatusID)
        .where(
            ServicePerfData.ServiceStatusID.in_(svc_ids),
            ServicePerfData.Metric.in_(metric_names),
        )
        .order_by(ServiceStatus.Timestamp.asc())
    ).all()

    # Bucket each reading.
    # bucket_index[metric][bucket_i] = list of values
    from collections import defaultdict
    bucket_data: dict[str, dict[int, list[float]]] = defaultdict(lambda: defaultdict(list))
    unit_map: dict[str, Optional[str]] = {}

    for row in perf_rows:
        ts = row.Timestamp
        if ts.tzinfo is None:
            ts = ts.replace(tzinfo=timezone.utc)
        offset = (ts - start).total_seconds()
        bucket_i = min(int(offset / bucket_size.total_seconds()), buckets - 1)
        bucket_data[row.Metric][bucket_i].append(row.Measured_Value)
        if row.Metric not in unit_map:
            unit_map[row.Metric] = row.Unit

    result: list[dict] = []
    for metric in metric_names:
        for i in range(buckets):
            bucket_start = (start + bucket_size * i).isoformat()
            vals = bucket_data[metric].get(i, [])
            avg_val = round(sum(vals) / len(vals), 4) if vals else None
            result.append({
                "bucket_start": bucket_start,
                "metric":       metric,
                "avg_value":    avg_val,
                "unit":         unit_map.get(metric),
            })

    return result
